#生产环境
server:
  port: ${WebServer_Port}
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${Registry_Center_IP:localhost}:49999/cbb_notification?useOldAliasMetadataBehavior=true&createDatabaseIfNotExist=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: Summit2017

  redis:
    host: "${Registry_Center_IP:localhost}"
    port: 10001
eureka:
  instance:
    #使用IP注册服务
    prefer-ip-address: true
    ip-address: "${Registry_Center_IP:localhost}"
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: "${Registry_Center_URL:http://ucp:Summit2018@localhost:${Registry_Center_Port}/eureka/}"