server:
  port: 22229
spring:
  profiles:
    active: dev
    include: common
  application:
    name: "cbb-notification"
  mail:
    host: smtp.qq.com
    username: 3421988273@qq.com
    password: fdgeeukxcdncdaeg
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
  #thymeleaf
  #默认到resource/templates目录下寻找
  thymeleaf:
    suffix: .html
    check-template-location: true
    encoding: UTF-8
    content-type: text/html
    cache: false
    mode: LEGACYHTML5
  flyway:
    # 如果启动的时候需要flyway管理sql脚本的话，将enabled设置为true
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db
    encoding: UTF-8