server:
  port: 22229
spring:
  profiles:
    active: pro
    include: common
  application:
    name: "cbb-notification"
  flyway:
    # 如果启动的时候需要flyway管理sql脚本的话，将enabled设置为true
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db
    encoding: UTF-8
  mail:
    host: smtp.qq.com
    username: 3421988273@qq.com
    password: fdgeeukxcdncdaeg
#    port: 465
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
jpush:
  appKey: 39220bed9a417c2f58f86d48
  masterSecret: d456a6cf5c93a1867cfa838a
  liveTime: 300000
  #安塞现场
  #appKey: 43d2500b962982d568d6d000
  #masterSecret: 44a6260c4afd4be02f95d808
  #liveTime: 300000
  
  #thymeleaf
  #默认到resource/templates目录下寻找
  thymeleaf:
    suffix: .html
    check-template-location: true
    encoding: UTF-8
    content-type: text/html
    cache: false
    mode: LEGACYHTML5

ccb_msg:
  sms:
    #短信AccessKeyID
    access-key-id: LTAI7t9ncYG6msbg
    #AccessKeySecret
    access-key-secret: nnTrlyuApboyM2vkY5SMqZkxCsUQA0
    #查询短信状态周期
    period: 1000
    #查询短信状态最大轮询次数
    max-polling-count: 300
    #验证码超时时间，单位秒，默认10分钟
    vcod-timeout: 600



mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.summit.send.pojo