package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class AREA_CROP_PARA extends Structure {
	/** \u0368\ufffd\ufffd\ufffd\ufffd */
	public NativeLong ulChnID;
	/** \u02b9\ufffd\ufffd */
	public boolean bEnable;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_STREAM_TYPE_E
	 */
	public int enStreamType;
	/**
	 * \ufffd\u05b1\ufffd\ufffd\ufffd<br>
	 * C type : PU_RESOLUTION_TYPE_E
	 */
	public int enResolution;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u03e2<br>
	 * C type : PU_AREA_INFO_S
	 */
	public PU_AREA_INFO stAreaInfo;
	/** C type : CHAR[64] */
	public byte[] szReserved = new byte[64];
	public AREA_CROP_PARA() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulChnID", "bEnable", "enStreamType", "enResolution", "stAreaInfo", "szReserved");
	}
	/**
	 * @param ulChnID \u0368\ufffd\ufffd\ufffd\ufffd<br>
	 * @param bEnable \u02b9\ufffd\ufffd<br>
	 * @param enStreamType \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_STREAM_TYPE_E<br>
	 * @param enResolution \ufffd\u05b1\ufffd\ufffd\ufffd<br>
	 * C type : PU_RESOLUTION_TYPE_E<br>
	 * @param stAreaInfo \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u03e2<br>
	 * C type : PU_AREA_INFO_S<br>
	 * @param szReserved C type : CHAR[64]
	 */
	public AREA_CROP_PARA(NativeLong ulChnID, boolean bEnable, int enStreamType, int enResolution, PU_AREA_INFO stAreaInfo, byte szReserved[]) {
		super();
		this.ulChnID = ulChnID;
		this.bEnable = bEnable;
		this.enStreamType = enStreamType;
		this.enResolution = enResolution;
		this.stAreaInfo = stAreaInfo;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public AREA_CROP_PARA(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends AREA_CROP_PARA implements Structure.ByReference {
		
	};
	public static class ByValue extends AREA_CROP_PARA implements Structure.ByValue {
		
	};
}
