package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class GUARD_PLAN_PARA extends Structure {
	/** \u0368\ufffd\ufffdID\ufffd\ufffd\u0524\ufffd\ufffd */
	public NativeLong ulChannelId;
	/**
	 * \u04bb\ufffd\u0732\ufffd\ufffd\ufffd\ufffd\u01bb\ufffd<br>
	 * C type : PU_HOTMAP_TIME_PLAN_S[(7)]
	 */
	public PU_HOTMAP_TIME_PLAN[] astGuadTime = new PU_HOTMAP_TIME_PLAN[7];
	/** C type : CHAR[32] */
	public byte[] szReserved = new byte[32];
	public GUARD_PLAN_PARA() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulChannelId", "astGuadTime", "szReserved");
	}
	/**
	 * @param ulChannelId \u0368\ufffd\ufffdID\ufffd\ufffd\u0524\ufffd\ufffd<br>
	 * @param astGuadTime \u04bb\ufffd\u0732\ufffd\ufffd\ufffd\ufffd\u01bb\ufffd<br>
	 * C type : PU_HOTMAP_TIME_PLAN_S[(7)]<br>
	 * @param szReserved C type : CHAR[32]
	 */
	public GUARD_PLAN_PARA(NativeLong ulChannelId, PU_HOTMAP_TIME_PLAN astGuadTime[], byte szReserved[]) {
		super();
		this.ulChannelId = ulChannelId;
		if ((astGuadTime.length != this.astGuadTime.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.astGuadTime = astGuadTime;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public GUARD_PLAN_PARA(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends GUARD_PLAN_PARA implements Structure.ByReference {
		
	};
	public static class ByValue extends GUARD_PLAN_PARA implements Structure.ByValue {
		
	};
}
