package com.summit.sdk.huawei;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_ALG_INFO extends Structure {
	/**
	 * \ufffd\u3de8\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_IPS_ALGORITHM_TYPE_E
	 */
	public int enAlgType;
	/**
	 * \ufffd\u3de8\ufffd\u6c7e<br>
	 * C type : CHAR[48]
	 */
	public byte[] szAlgVer = new byte[48];
	/**
	 * \ufffd\u3de8\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : CHAR[48]
	 */
	public byte[] szAlgOwner = new byte[48];
	/** C type : CHAR[32] */
	public byte[] szReserved = new byte[32];
	public PU_ALG_INFO() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("enAlgType", "szAlgVer", "szAlgOwner", "szReserved");
	}
	/**
	 * @param enAlgType \ufffd\u3de8\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_IPS_ALGORITHM_TYPE_E<br>
	 * @param szAlgVer \ufffd\u3de8\ufffd\u6c7e<br>
	 * C type : CHAR[48]<br>
	 * @param szAlgOwner \ufffd\u3de8\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : CHAR[48]<br>
	 * @param szReserved C type : CHAR[32]
	 */
	public PU_ALG_INFO(int enAlgType, byte szAlgVer[], byte szAlgOwner[], byte szReserved[]) {
		super();
		this.enAlgType = enAlgType;
		if ((szAlgVer.length != this.szAlgVer.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szAlgVer = szAlgVer;
		if ((szAlgOwner.length != this.szAlgOwner.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szAlgOwner = szAlgOwner;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public PU_ALG_INFO(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_ALG_INFO implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_ALG_INFO implements Structure.ByValue {
		
	};
}
