package com.summit.sdk.huawei;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_AUTO_CALIBRATION_CONFIG extends Structure {
	/**
	 * \ufffd\u0536\ufffd\ufffd\uada8\u02b1\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0135\ufffdptz<br>
	 * C type : PU_PTZ_CURRENT_LOCATION_S
	 */
	public PU_PTZ_CURRENT_LOCATION stCenter;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u037c\ufffd\u6d22\u00b7\ufffd\ufffd<br>
	 * C type : CHAR[(64)]
	 */
	public byte[] szMasterScreenPicPath = new byte[64];
	/**
	 * \ufffd\u04fb\ufffd\ufffd\ufffd\ufffd\u037c\ufffd\u6d22\u00b7\ufffd\ufffd<br>
	 * C type : CHAR[(64)]
	 */
	public byte[] szSlaveScreenPicPath = new byte[64];
	public PU_AUTO_CALIBRATION_CONFIG() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("stCenter", "szMasterScreenPicPath", "szSlaveScreenPicPath");
	}
	/**
	 * @param stCenter \ufffd\u0536\ufffd\ufffd\uada8\u02b1\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0135\ufffdptz<br>
	 * C type : PU_PTZ_CURRENT_LOCATION_S<br>
	 * @param szMasterScreenPicPath \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u037c\ufffd\u6d22\u00b7\ufffd\ufffd<br>
	 * C type : CHAR[(64)]<br>
	 * @param szSlaveScreenPicPath \ufffd\u04fb\ufffd\ufffd\ufffd\ufffd\u037c\ufffd\u6d22\u00b7\ufffd\ufffd<br>
	 * C type : CHAR[(64)]
	 */
	public PU_AUTO_CALIBRATION_CONFIG(PU_PTZ_CURRENT_LOCATION stCenter, byte szMasterScreenPicPath[], byte szSlaveScreenPicPath[]) {
		super();
		this.stCenter = stCenter;
		if ((szMasterScreenPicPath.length != this.szMasterScreenPicPath.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szMasterScreenPicPath = szMasterScreenPicPath;
		if ((szSlaveScreenPicPath.length != this.szSlaveScreenPicPath.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szSlaveScreenPicPath = szSlaveScreenPicPath;
	}
	public PU_AUTO_CALIBRATION_CONFIG(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_AUTO_CALIBRATION_CONFIG implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_AUTO_CALIBRATION_CONFIG implements Structure.ByValue {
		
	};
}
