package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_BACKLIGHT_MODE extends Structure {
	/**
	 * \u0123\u02bd\ufffd\ufffd\ufffd\ufffd(\ufffd\u0631\u0561\ufffd\ufffd\ufffd)<br>
	 * C type : PU_COMMONMODE_SWITCH_E
	 */
	public int enBackLightMode;
	/** \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u03a70~255 */
	public NativeLong lBackLight;
	/**
	 * \ufffd\ufffd\ufffd\u2cb9\ufffd\ufffd\u0123\u02bd<br>
	 * C type : BACKLIGHT_MODE_E
	 */
	public int enMode;
	/**
	 * \ufffd\ufffd\ufffd\u2cb9\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_AREA_INFO_S
	 */
	public PU_AREA_INFO stAreaInfo;
	/** C type : CHAR[12] */
	public byte[] szReserve = new byte[12];
	public PU_BACKLIGHT_MODE() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("enBackLightMode", "lBackLight", "enMode", "stAreaInfo", "szReserve");
	}
	/**
	 * @param enBackLightMode \u0123\u02bd\ufffd\ufffd\ufffd\ufffd(\ufffd\u0631\u0561\ufffd\ufffd\ufffd)<br>
	 * C type : PU_COMMONMODE_SWITCH_E<br>
	 * @param lBackLight \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u03a70~255<br>
	 * @param enMode \ufffd\ufffd\ufffd\u2cb9\ufffd\ufffd\u0123\u02bd<br>
	 * C type : BACKLIGHT_MODE_E<br>
	 * @param stAreaInfo \ufffd\ufffd\ufffd\u2cb9\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_AREA_INFO_S<br>
	 * @param szReserve C type : CHAR[12]
	 */
	public PU_BACKLIGHT_MODE(int enBackLightMode, NativeLong lBackLight, int enMode, PU_AREA_INFO stAreaInfo, byte szReserve[]) {
		super();
		this.enBackLightMode = enBackLightMode;
		this.lBackLight = lBackLight;
		this.enMode = enMode;
		this.stAreaInfo = stAreaInfo;
		if ((szReserve.length != this.szReserve.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserve = szReserve;
	}
	public PU_BACKLIGHT_MODE(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_BACKLIGHT_MODE implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_BACKLIGHT_MODE implements Structure.ByValue {
		
	};
}
