package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_CREATE_HTTPS_CERT extends Structure {
	/**
	 * \u05a4\ufffd\ufffdCN<br>
	 * C type : CHAR[(128 + 4)]
	 */
	public byte[] szCommonName = new byte[128 + 4];
	/**
	 * \ufffd\ufffd\ufffd<br>
	 * C type : CHAR[(128 + 4)]
	 */
	public byte[] szCountry = new byte[128 + 4];
	/**
	 * \u02a1/\ufffd\ufffd<br>
	 * C type : CHAR[(128 + 4)]
	 */
	public byte[] szState = new byte[128 + 4];
	/**
	 * \ufffd\ufffd\ufffd\ufffd<br>
	 * C type : CHAR[(128 + 4)]
	 */
	public byte[] szLocation = new byte[128 + 4];
	/**
	 * \ufffd\ufffd\u05af<br>
	 * C type : CHAR[(128 + 4)]
	 */
	public byte[] szOrganization = new byte[128 + 4];
	/**
	 * \ufffd\ufffd\u03bb<br>
	 * C type : CHAR[(128 + 4)]
	 */
	public byte[] szUnit = new byte[128 + 4];
	/**
	 * \ufffd\u02bc\ufffd\ufffd\ufffd\u05b7<br>
	 * C type : CHAR[(128 + 4)]
	 */
	public byte[] szEmail = new byte[128 + 4];
	/** \ufffd\ufffd\u0427\ufffd\ufffd\ufffd\ufffd */
	public NativeLong ulExpiredDays;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u05a4\ufffd\ufffd\ufffdPwd<br>
	 * C type : CHAR[(64 + 4)]
	 */
	public byte[] szCreateCertPsw = new byte[64 + 4];
	/** C type : CHAR[32] */
	public byte[] szReserve = new byte[32];
	public PU_CREATE_HTTPS_CERT() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("szCommonName", "szCountry", "szState", "szLocation", "szOrganization", "szUnit", "szEmail", "ulExpiredDays", "szCreateCertPsw", "szReserve");
	}
	public PU_CREATE_HTTPS_CERT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_CREATE_HTTPS_CERT implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_CREATE_HTTPS_CERT implements Structure.ByValue {
		
	};
}
