package com.summit.sdk.huawei;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_CAMPUS_MODE_PARA extends Structure {
	/** \u0530\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04b5\ufffd\ufffd\ufffd\ufffd\u02b9\ufffd\u073f\ufffd\ufffd\ufffd */
	public boolean bEnable;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd                         // \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd:0-\ufffd\ufffd\u0226\ufffd\ufffd\ufffd\ufffd  1-\ufffd\ufffd\u01b5\ufffd\ufffd\ufffd\u07f4\ufffd\ufffd\ufffd   2-\ufffd\ufffd\ufffd\u0123\u02bd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_CAMPUS_TRIG_TYPE_E
	 */
	public int enTrigType;
	/** \ufffd\u01f7\ufffd\ufffd\u03f1\ufffd\ufffd\ufffd\ufffd\u01b3\ufffd */
	public boolean bEnableNoPlateVeh;
	/** \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u077b\u0634\ufffd */
	public boolean bEnableDataAck;
	public PU_CAMPUS_MODE_PARA() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("bEnable", "enTrigType", "bEnableNoPlateVeh", "bEnableDataAck");
	}
	/**
	 * @param bEnable \u0530\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04b5\ufffd\ufffd\ufffd\ufffd\u02b9\ufffd\u073f\ufffd\ufffd\ufffd<br>
	 * @param enTrigType \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd                         // \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd:0-\ufffd\ufffd\u0226\ufffd\ufffd\ufffd\ufffd  1-\ufffd\ufffd\u01b5\ufffd\ufffd\ufffd\u07f4\ufffd\ufffd\ufffd   2-\ufffd\ufffd\ufffd\u0123\u02bd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_CAMPUS_TRIG_TYPE_E<br>
	 * @param bEnableNoPlateVeh \ufffd\u01f7\ufffd\ufffd\u03f1\ufffd\ufffd\ufffd\ufffd\u01b3\ufffd<br>
	 * @param bEnableDataAck \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u077b\u0634\ufffd
	 */
	public PU_CAMPUS_MODE_PARA(boolean bEnable, int enTrigType, boolean bEnableNoPlateVeh, boolean bEnableDataAck) {
		super();
		this.bEnable = bEnable;
		this.enTrigType = enTrigType;
		this.bEnableNoPlateVeh = bEnableNoPlateVeh;
		this.bEnableDataAck = bEnableDataAck;
	}
	public PU_CAMPUS_MODE_PARA(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_CAMPUS_MODE_PARA implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_CAMPUS_MODE_PARA implements Structure.ByValue {
		
	};
}
