package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_DEC_PORT_ABILITY_LIST extends Structure {
	public NativeLong ulBNCNum;
	public NativeLong ulVGANum;
	public NativeLong ulHDMINum;
	public NativeLong ulDVINum;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u05a7\ufffd\u05b5\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_ENCODE_TYPE_E[4]
	 */
	public int[] enDecodeType = new int[4];
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0363\ufffdA/V/AV\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0123\u02bd:\ufffd\ufffd\ufffd\ufffd1\ufffd\ufffd2\ufffd\ufffd4\ufffd\ufffd9\ufffd\ufffd16\ufffd\u023c\ufffd\ufffd\ufffd\u0123\u02bd\ufffd\ufffd<br>
	 * C type : PU_DEC_PORT_ABILITY_S[32]
	 */
	public PU_DEC_PORT_ABILITY[] stBNCAttribute = new PU_DEC_PORT_ABILITY[32];
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0363\ufffdA/V/AV\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0123\u02bd:\ufffd\ufffd\ufffd\ufffd1\ufffd\ufffd2\ufffd\ufffd4\ufffd\ufffd9\ufffd\ufffd16\ufffd\u023c\ufffd\ufffd\ufffd\u0123\u02bd\ufffd\ufffd\ufffd\u0174\ufffd\u05a7\ufffd\u05b1\ufffd\u05be\ufffd\ufffd<br>
	 * C type : PU_DEC_PORT_ABILITY_S[8]
	 */
	public PU_DEC_PORT_ABILITY[] stVGAAttribute = new PU_DEC_PORT_ABILITY[8];
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0363\ufffdA/V/AV\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0123\u02bd:\ufffd\ufffd\ufffd\ufffd1\ufffd\ufffd2\ufffd\ufffd4\ufffd\ufffd9\ufffd\ufffd16\ufffd\u023c\ufffd\ufffd\ufffd\u0123\u02bd\ufffd\ufffd\ufffd\u0174\ufffd\u05a7\ufffd\u05b1\ufffd\u05be\ufffd\ufffd<br>
	 * C type : PU_DEC_PORT_ABILITY_S[8]
	 */
	public PU_DEC_PORT_ABILITY[] stHDMIAttribute = new PU_DEC_PORT_ABILITY[8];
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0363\ufffdA/V/AV\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0123\u02bd:\ufffd\ufffd\ufffd\ufffd1\ufffd\ufffd2\ufffd\ufffd4\ufffd\ufffd9\ufffd\ufffd16\ufffd\u023c\ufffd\ufffd\ufffd\u0123\u02bd\ufffd\ufffd\ufffd\u0174\ufffd\u05a7\ufffd\u05b1\ufffd\u05be\ufffd\ufffd** /<br>
	 * C type : PU_DEC_PORT_ABILITY_S[8]
	 */
	public PU_DEC_PORT_ABILITY[] stDVIAttribute = new PU_DEC_PORT_ABILITY[8];
	public PU_DEC_PORT_ABILITY_LIST() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulBNCNum", "ulVGANum", "ulHDMINum", "ulDVINum", "enDecodeType", "stBNCAttribute", "stVGAAttribute", "stHDMIAttribute", "stDVIAttribute");
	}
	/**
	 * @param enDecodeType \ufffd\ufffd\ufffd\ufffd\u05a7\ufffd\u05b5\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_ENCODE_TYPE_E[4]<br>
	 * @param stBNCAttribute \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0363\ufffdA/V/AV\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0123\u02bd:\ufffd\ufffd\ufffd\ufffd1\ufffd\ufffd2\ufffd\ufffd4\ufffd\ufffd9\ufffd\ufffd16\ufffd\u023c\ufffd\ufffd\ufffd\u0123\u02bd\ufffd\ufffd<br>
	 * C type : PU_DEC_PORT_ABILITY_S[32]<br>
	 * @param stVGAAttribute \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0363\ufffdA/V/AV\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0123\u02bd:\ufffd\ufffd\ufffd\ufffd1\ufffd\ufffd2\ufffd\ufffd4\ufffd\ufffd9\ufffd\ufffd16\ufffd\u023c\ufffd\ufffd\ufffd\u0123\u02bd\ufffd\ufffd\ufffd\u0174\ufffd\u05a7\ufffd\u05b1\ufffd\u05be\ufffd\ufffd<br>
	 * C type : PU_DEC_PORT_ABILITY_S[8]<br>
	 * @param stHDMIAttribute \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0363\ufffdA/V/AV\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0123\u02bd:\ufffd\ufffd\ufffd\ufffd1\ufffd\ufffd2\ufffd\ufffd4\ufffd\ufffd9\ufffd\ufffd16\ufffd\u023c\ufffd\ufffd\ufffd\u0123\u02bd\ufffd\ufffd\ufffd\u0174\ufffd\u05a7\ufffd\u05b1\ufffd\u05be\ufffd\ufffd<br>
	 * C type : PU_DEC_PORT_ABILITY_S[8]<br>
	 * @param stDVIAttribute \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0363\ufffdA/V/AV\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0123\u02bd:\ufffd\ufffd\ufffd\ufffd1\ufffd\ufffd2\ufffd\ufffd4\ufffd\ufffd9\ufffd\ufffd16\ufffd\u023c\ufffd\ufffd\ufffd\u0123\u02bd\ufffd\ufffd\ufffd\u0174\ufffd\u05a7\ufffd\u05b1\ufffd\u05be\ufffd\ufffd** /<br>
	 * C type : PU_DEC_PORT_ABILITY_S[8]
	 */
	public PU_DEC_PORT_ABILITY_LIST(NativeLong ulBNCNum, NativeLong ulVGANum, NativeLong ulHDMINum, NativeLong ulDVINum, int enDecodeType[], PU_DEC_PORT_ABILITY stBNCAttribute[], PU_DEC_PORT_ABILITY stVGAAttribute[], PU_DEC_PORT_ABILITY stHDMIAttribute[], PU_DEC_PORT_ABILITY stDVIAttribute[]) {
		super();
		this.ulBNCNum = ulBNCNum;
		this.ulVGANum = ulVGANum;
		this.ulHDMINum = ulHDMINum;
		this.ulDVINum = ulDVINum;
		if ((enDecodeType.length != this.enDecodeType.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.enDecodeType = enDecodeType;
		if ((stBNCAttribute.length != this.stBNCAttribute.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.stBNCAttribute = stBNCAttribute;
		if ((stVGAAttribute.length != this.stVGAAttribute.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.stVGAAttribute = stVGAAttribute;
		if ((stHDMIAttribute.length != this.stHDMIAttribute.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.stHDMIAttribute = stHDMIAttribute;
		if ((stDVIAttribute.length != this.stDVIAttribute.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.stDVIAttribute = stDVIAttribute;
	}
	public PU_DEC_PORT_ABILITY_LIST(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_DEC_PORT_ABILITY_LIST implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_DEC_PORT_ABILITY_LIST implements Structure.ByValue {
		
	};
}
