package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_DEC_CHANNEL_INFO extends Structure {
	/** \u0368\ufffd\ufffdID\ufffd\ufffd */
	public NativeLong ulChannelId;
	/** \ufffd\ufffd\ufffd\ufffd\u02b9\ufffd\ufffd */
	public boolean bDenoiseFlag;
	/** \u0225\ufffd\ufffd\u02b9\ufffd\ufffd */
	public boolean bDemistFlag;
	/** \u037c\ufffd\ufffd\u0174\ufffd\u05f4\u032c */
	public boolean bEnlargeStatus;
	/**
	 * OSD\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u03e2<br>
	 * C type : PU_DEC_OSD_STRING_INFO_S
	 */
	public PU_DEC_OSD_STRING_INFO stOsdTextInfo;
	public PU_DEC_CHANNEL_INFO() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulChannelId", "bDenoiseFlag", "bDemistFlag", "bEnlargeStatus", "stOsdTextInfo");
	}
	/**
	 * @param ulChannelId \u0368\ufffd\ufffdID\ufffd\ufffd<br>
	 * @param bDenoiseFlag \ufffd\ufffd\ufffd\ufffd\u02b9\ufffd\ufffd<br>
	 * @param bDemistFlag \u0225\ufffd\ufffd\u02b9\ufffd\ufffd<br>
	 * @param bEnlargeStatus \u037c\ufffd\ufffd\u0174\ufffd\u05f4\u032c<br>
	 * @param stOsdTextInfo OSD\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u03e2<br>
	 * C type : PU_DEC_OSD_STRING_INFO_S
	 */
	public PU_DEC_CHANNEL_INFO(NativeLong ulChannelId, boolean bDenoiseFlag, boolean bDemistFlag, boolean bEnlargeStatus, PU_DEC_OSD_STRING_INFO stOsdTextInfo) {
		super();
		this.ulChannelId = ulChannelId;
		this.bDenoiseFlag = bDenoiseFlag;
		this.bDemistFlag = bDemistFlag;
		this.bEnlargeStatus = bEnlargeStatus;
		this.stOsdTextInfo = stOsdTextInfo;
	}
	public PU_DEC_CHANNEL_INFO(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_DEC_CHANNEL_INFO implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_DEC_CHANNEL_INFO implements Structure.ByValue {
		
	};
}
