package com.summit.sdk.huawei;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_DST_DATE_WAY extends Structure {
	/** \ufffd\ufffd\u02beXXXX\ufffd\ufffd,0-\u00ff\ufffd\ufffd,[2014-2024]\ufffd\u05b1\ufffd\ufffd\u02be\ufffd\ufffd\u04e6\ufffd\ufffd\ufffd\ufffd\ufffd */
	public int uiYear;
	/** [0,11],\ufffd\u05b1\ufffd\ufffd\u02be1-12\ufffd\ufffd */
	public int uiMonth;
	/** [0,30],\ufffd\u05b1\ufffd\ufffd\u02be1-31\ufffd\ufffd */
	public int uiDay;
	/** [0,23],\ufffd\ufffd\u02be\u04bb\ufffd\ufffd\ufffd\u0435\u0135\ufffdX\ufffd\ufffd\u0421\u02b1 */
	public int uiHour;
	/** [0,59],\ufffd\ufffd\u02be\ufffd\ufffdX\ufffd\ufffd\u0421\u02b1\ufffd\u0135\ufffdX\ufffd\ufffd\ufffd\ufffd */
	public int uiMinute;
	/**
	 * \u0524\ufffd\ufffd<br>
	 * C type : CHAR[32]
	 */
	public byte[] szReserved = new byte[32];
	public PU_DST_DATE_WAY() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("uiYear", "uiMonth", "uiDay", "uiHour", "uiMinute", "szReserved");
	}
	/**
	 * @param uiYear \ufffd\ufffd\u02beXXXX\ufffd\ufffd,0-\u00ff\ufffd\ufffd,[2014-2024]\ufffd\u05b1\ufffd\ufffd\u02be\ufffd\ufffd\u04e6\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * @param uiMonth [0,11],\ufffd\u05b1\ufffd\ufffd\u02be1-12\ufffd\ufffd<br>
	 * @param uiDay [0,30],\ufffd\u05b1\ufffd\ufffd\u02be1-31\ufffd\ufffd<br>
	 * @param uiHour [0,23],\ufffd\ufffd\u02be\u04bb\ufffd\ufffd\ufffd\u0435\u0135\ufffdX\ufffd\ufffd\u0421\u02b1<br>
	 * @param uiMinute [0,59],\ufffd\ufffd\u02be\ufffd\ufffdX\ufffd\ufffd\u0421\u02b1\ufffd\u0135\ufffdX\ufffd\ufffd\ufffd\ufffd<br>
	 * @param szReserved \u0524\ufffd\ufffd<br>
	 * C type : CHAR[32]
	 */
	public PU_DST_DATE_WAY(int uiYear, int uiMonth, int uiDay, int uiHour, int uiMinute, byte szReserved[]) {
		super();
		this.uiYear = uiYear;
		this.uiMonth = uiMonth;
		this.uiDay = uiDay;
		this.uiHour = uiHour;
		this.uiMinute = uiMinute;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public PU_DST_DATE_WAY(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_DST_DATE_WAY implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_DST_DATE_WAY implements Structure.ByValue {
		
	};
}
