package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_DEC_AUDIO_INFO extends Structure {
	/**
	 * \ufffd\ufffd\u01b5\ufffd\u02ff\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_AUDIO_PORT_TYPE_E
	 */
	public int enAudioPortType;
	/** \ufffd\ufffd\u01b5\ufffd\u02ff\ufffd\u02b9\ufffd\ufffd\ufffd\ufffd\ufffd */
	public boolean bEnable;
	/** \ufffd\ufffd\u01b5\ufffd\ufffd\ufffd\ufffd\ufffd\u0368\ufffd\ufffd\ufffd\ufffd */
	public NativeLong ulChannelId;
	/**
	 * \ufffd\ufffd\u01b5\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_ENCODE_TYPE_E
	 */
	public int enAudioDecodeType;
	/** \ufffd\ufffd\ufffd\ufffd */
	public NativeLong ulAudioVolume;
	/**
	 * \ufffd\ufffd\u01b5\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_AUDIO_SAMPLERATE_E
	 */
	public int enAudioSampleRate;
	public PU_DEC_AUDIO_INFO() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("enAudioPortType", "bEnable", "ulChannelId", "enAudioDecodeType", "ulAudioVolume", "enAudioSampleRate");
	}
	/**
	 * @param enAudioPortType \ufffd\ufffd\u01b5\ufffd\u02ff\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_AUDIO_PORT_TYPE_E<br>
	 * @param bEnable \ufffd\ufffd\u01b5\ufffd\u02ff\ufffd\u02b9\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * @param ulChannelId \ufffd\ufffd\u01b5\ufffd\ufffd\ufffd\ufffd\ufffd\u0368\ufffd\ufffd\ufffd\ufffd<br>
	 * @param enAudioDecodeType \ufffd\ufffd\u01b5\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_ENCODE_TYPE_E<br>
	 * @param ulAudioVolume \ufffd\ufffd\ufffd\ufffd<br>
	 * @param enAudioSampleRate \ufffd\ufffd\u01b5\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_AUDIO_SAMPLERATE_E
	 */
	public PU_DEC_AUDIO_INFO(int enAudioPortType, boolean bEnable, NativeLong ulChannelId, int enAudioDecodeType, NativeLong ulAudioVolume, int enAudioSampleRate) {
		super();
		this.enAudioPortType = enAudioPortType;
		this.bEnable = bEnable;
		this.ulChannelId = ulChannelId;
		this.enAudioDecodeType = enAudioDecodeType;
		this.ulAudioVolume = ulAudioVolume;
		this.enAudioSampleRate = enAudioSampleRate;
	}
	public PU_DEC_AUDIO_INFO(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_DEC_AUDIO_INFO implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_DEC_AUDIO_INFO implements Structure.ByValue {
		
	};
}
