package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_DETECTION_AREA extends Structure {
	/** \ufffd\ufffd\ufffd\ufffd\ufffd\u03b8\ufffd\ufffd\ufffd */
	public NativeLong ulNum;
	/**
	 * \ufffd\ufffd\ufffd\u03b2\ufffd\ufffd\ufffd<br>
	 * C type : PU_MASK_PARA_S[16]
	 */
	public PU_MASK_PARA[] stMaskPara = new PU_MASK_PARA[16];
	public PU_DETECTION_AREA() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulNum", "stMaskPara");
	}
	/**
	 * @param ulNum \ufffd\ufffd\ufffd\ufffd\ufffd\u03b8\ufffd\ufffd\ufffd<br>
	 * @param stMaskPara \ufffd\ufffd\ufffd\u03b2\ufffd\ufffd\ufffd<br>
	 * C type : PU_MASK_PARA_S[16]
	 */
	public PU_DETECTION_AREA(NativeLong ulNum, PU_MASK_PARA stMaskPara[]) {
		super();
		this.ulNum = ulNum;
		if ((stMaskPara.length != this.stMaskPara.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.stMaskPara = stMaskPara;
	}
	public PU_DETECTION_AREA(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_DETECTION_AREA implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_DETECTION_AREA implements Structure.ByValue {
		
	};
}
