package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_DEC_PORT_INFO_LIST extends Structure {
	public NativeLong ulBNCNum;
	public NativeLong ulVGANum;
	public NativeLong ulHDMINum;
	public NativeLong ulDVINum;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_ENCODE_TYPE_E
	 */
	public int enDecodeType;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0363\ufffdA/V/AV    \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0123\u02bd:\ufffd\ufffd\ufffd\ufffd1\ufffd\ufffd2\ufffd\ufffd4\ufffd\ufffd9\ufffd\ufffd16\ufffd\u023c\ufffd\ufffd\ufffd\u0123\u02bd\ufffd\ufffd<br>
	 * C type : PU_DEC_PORT_INFO_S[32]
	 */
	public PU_DEC_PORT_INFO[] stBNCAttribute = new PU_DEC_PORT_INFO[32];
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0363\ufffdA/V/AV    \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0123\u02bd:\ufffd\ufffd\ufffd\ufffd1\ufffd\ufffd2\ufffd\ufffd4\ufffd\ufffd9\ufffd\ufffd16\ufffd\u023c\ufffd\ufffd\ufffd\u0123\u02bd\ufffd\ufffd\ufffd\u0174\ufffd\u05a7\ufffd\u05b1\ufffd\u05be\ufffd\ufffd<br>
	 * C type : PU_DEC_PORT_INFO_S[8]
	 */
	public PU_DEC_PORT_INFO[] stVGAAttribute = new PU_DEC_PORT_INFO[8];
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0363\ufffdA/V/AV    \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0123\u02bd:\ufffd\ufffd\ufffd\ufffd1\ufffd\ufffd2\ufffd\ufffd4\ufffd\ufffd9\ufffd\ufffd16\ufffd\u023c\ufffd\ufffd\ufffd\u0123\u02bd\ufffd\ufffd\ufffd\u0174\ufffd\u05a7\ufffd\u05b1\ufffd\u05be\ufffd\ufffd<br>
	 * C type : PU_DEC_PORT_INFO_S[8]
	 */
	public PU_DEC_PORT_INFO[] stHDMIAttribute = new PU_DEC_PORT_INFO[8];
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0363\ufffdA/V/AV   \ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0123\u02bd:\ufffd\ufffd\ufffd\ufffd1\ufffd\ufffd2\ufffd\ufffd4\ufffd\ufffd9\ufffd\ufffd16\ufffd\u023c\ufffd\ufffd\ufffd\u0123\u02bd\ufffd\ufffd\ufffd\u0174\ufffd\u05a7\ufffd\u05b1\ufffd\u05be\ufffd\ufffd** /<br>
	 * C type : PU_DEC_PORT_INFO_S[8]
	 */
	public PU_DEC_PORT_INFO[] stDVIAttribute = new PU_DEC_PORT_INFO[8];
	/**
	 * CHAR chSameVInput;                                            //VGA/HDMI/DVI \ufffd\u01f7\ufffd\u036c\u0534\u0123\u02bd\ufffd\ufffd0000 0000 \ufffd\ufffd\u036c\u0534, 0000 0111  \u036c\u0534 * /<br>
	 * C type : CHAR[32]
	 */
	public byte[] chRes = new byte[32];
	public PU_DEC_PORT_INFO_LIST() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulBNCNum", "ulVGANum", "ulHDMINum", "ulDVINum", "enDecodeType", "stBNCAttribute", "stVGAAttribute", "stHDMIAttribute", "stDVIAttribute", "chRes");
	}
	public PU_DEC_PORT_INFO_LIST(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_DEC_PORT_INFO_LIST implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_DEC_PORT_INFO_LIST implements Structure.ByValue {
		
	};
}
