package com.summit.sdk.huawei;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public abstract class PU_DAYLIGHT_SAVING_TIME extends Structure {
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u02b1\u02b5\u02a9\ufffd\ufffd\u02bd<br>
	 * C type : PU_DST_TYPE_E
	 */
	public int enDSTType;
	/** \ufffd\ufffd\ufffd\ufffd\u02b1\u02b9\ufffd\ufffd */
	public boolean bEnable;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u02b1\u02b1\ufffd\ufffd\u01ab\ufffd\ufffd<br>
	 * C type : PU_DST_OFFSET_E
	 */
	public int enOffset;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u02b1\ufffd\ufffd\u02bc\u02b1\ufffd\ufffd<br>
	 * C type : PU_DST_DATE_S
	 */
	public PU_DST_DATE stDSTStartTime;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u02b1\ufffd\ufffd\ufffd\ufffd\u02b1\ufffd\ufffd<br>
	 * C type : PU_DST_DATE_S
	 */
	public PU_DST_DATE stDSTEndTime;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u02b1\ufffd\ufffd\ufffd\u06b7\ufffd\u02bd\u02b1\ufffd\ufffd\u01ab\ufffd\ufffd<br>
	 * C type : PU_DST_OFFSET_E
	 */
	public int enDateWayOffset;
	/** Conversion Error : sizeof(int) */
	public PU_DAYLIGHT_SAVING_TIME() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("enDSTType", "bEnable", "enOffset", "stDSTStartTime", "stDSTEndTime", "enDateWayOffset");
	}
	/**
	 * @param enDSTType \ufffd\ufffd\ufffd\ufffd\u02b1\u02b5\u02a9\ufffd\ufffd\u02bd<br>
	 * C type : PU_DST_TYPE_E<br>
	 * @param bEnable \ufffd\ufffd\ufffd\ufffd\u02b1\u02b9\ufffd\ufffd<br>
	 * @param enOffset \ufffd\ufffd\ufffd\ufffd\u02b1\u02b1\ufffd\ufffd\u01ab\ufffd\ufffd<br>
	 * C type : PU_DST_OFFSET_E<br>
	 * @param stDSTStartTime \ufffd\ufffd\ufffd\ufffd\u02b1\ufffd\ufffd\u02bc\u02b1\ufffd\ufffd<br>
	 * C type : PU_DST_DATE_S<br>
	 * @param stDSTEndTime \ufffd\ufffd\ufffd\ufffd\u02b1\ufffd\ufffd\ufffd\ufffd\u02b1\ufffd\ufffd<br>
	 * C type : PU_DST_DATE_S<br>
	 * @param enDateWayOffset \ufffd\ufffd\ufffd\ufffd\u02b1\ufffd\ufffd\ufffd\u06b7\ufffd\u02bd\u02b1\ufffd\ufffd\u01ab\ufffd\ufffd<br>
	 * C type : PU_DST_OFFSET_E
	 */
	public PU_DAYLIGHT_SAVING_TIME(int enDSTType, boolean bEnable, int enOffset, PU_DST_DATE stDSTStartTime, PU_DST_DATE stDSTEndTime, int enDateWayOffset) {
		super();
		this.enDSTType = enDSTType;
		this.bEnable = bEnable;
		this.enOffset = enOffset;
		this.stDSTStartTime = stDSTStartTime;
		this.stDSTEndTime = stDSTEndTime;
		this.enDateWayOffset = enDateWayOffset;
	}
	public PU_DAYLIGHT_SAVING_TIME(Pointer peer) {
		super(peer);
	}
	public static abstract class ByReference extends PU_DAYLIGHT_SAVING_TIME implements Structure.ByReference {
		
	};
	public static abstract class ByValue extends PU_DAYLIGHT_SAVING_TIME implements Structure.ByValue {
		
	};
}
