package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_EVENT_UPLOAD_IMAGE_COMP_NOTIFY extends Structure {
	/**
	 * \u0368\ufffd\ufffd\ufffd\u00bc\ufffd<br>
	 * C type : PU_EVENT_COMMON_S
	 */
	public PU_EVENT_COMMON stPuEventCommon;
	/** \ufffd\u03f4\ufffd\ufffd\ufffd\ufffd\u0368\u05aa\ufffd\u1ef0ID,\ufffd\ufffd\ufffd\ufffd\u01f0\ufffd\u02f1\ufffd\u02b6\u04bb\ufffd\ufffd\u03a8\u04bb\ufffd\u013b\u1ef0 */
	public NativeLong ulSessionId;
	/**
	 * \u037c\u01ac\ufffd\ufffd<br>
	 * C type : CHAR[24]
	 */
	public byte[] szContentID = new byte[24];
	/** \u037c\u01ac\ufffd\ufffd\u0421 */
	public NativeLong ulContentSize;
	/**
	 * \u05e5\ufffd\ufffd\u02b1\ufffd\ufffd \ufffd\ufffd\u02bd\ufffd\ufffd"2009-07-14 15:41:14"<br>
	 * C type : CHAR[32]
	 */
	public byte[] szSnapTime = new byte[32];
	/** C type : PU_SNAPSHOT_TYPE_E */
	public int enSnapshotType;
	/** C type : CHAR[32] */
	public byte[] szReserved = new byte[32];
	public PU_EVENT_UPLOAD_IMAGE_COMP_NOTIFY() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("stPuEventCommon", "ulSessionId", "szContentID", "ulContentSize", "szSnapTime", "enSnapshotType", "szReserved");
	}
	/**
	 * @param stPuEventCommon \u0368\ufffd\ufffd\ufffd\u00bc\ufffd<br>
	 * C type : PU_EVENT_COMMON_S<br>
	 * @param ulSessionId \ufffd\u03f4\ufffd\ufffd\ufffd\ufffd\u0368\u05aa\ufffd\u1ef0ID,\ufffd\ufffd\ufffd\ufffd\u01f0\ufffd\u02f1\ufffd\u02b6\u04bb\ufffd\ufffd\u03a8\u04bb\ufffd\u013b\u1ef0<br>
	 * @param szContentID \u037c\u01ac\ufffd\ufffd<br>
	 * C type : CHAR[24]<br>
	 * @param ulContentSize \u037c\u01ac\ufffd\ufffd\u0421<br>
	 * @param szSnapTime \u05e5\ufffd\ufffd\u02b1\ufffd\ufffd \ufffd\ufffd\u02bd\ufffd\ufffd"2009-07-14 15:41:14"<br>
	 * C type : CHAR[32]<br>
	 * @param enSnapshotType C type : PU_SNAPSHOT_TYPE_E<br>
	 * @param szReserved C type : CHAR[32]
	 */
	public PU_EVENT_UPLOAD_IMAGE_COMP_NOTIFY(PU_EVENT_COMMON stPuEventCommon, NativeLong ulSessionId, byte szContentID[], NativeLong ulContentSize, byte szSnapTime[], int enSnapshotType, byte szReserved[]) {
		super();
		this.stPuEventCommon = stPuEventCommon;
		this.ulSessionId = ulSessionId;
		if ((szContentID.length != this.szContentID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szContentID = szContentID;
		this.ulContentSize = ulContentSize;
		if ((szSnapTime.length != this.szSnapTime.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szSnapTime = szSnapTime;
		this.enSnapshotType = enSnapshotType;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public PU_EVENT_UPLOAD_IMAGE_COMP_NOTIFY(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_EVENT_UPLOAD_IMAGE_COMP_NOTIFY implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_EVENT_UPLOAD_IMAGE_COMP_NOTIFY implements Structure.ByValue {
		
	};
}
