package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_FACE_RECORD extends Structure {
	/** \ufffd\ufffd\ufffd\ufffdID */
	public NativeLong ulFaceId;
	/**
	 * \ufffd\ufffd\ufffd\ufffd<br>
	 * C type : CHAR[(64)]
	 */
	public byte[] szName = new byte[64];
	/**
	 * \ufffd\u0531\ufffd<br>
	 * C type : PU_GENDER_E
	 */
	public int enGender;
	/**
	 * \ufffd\ufffd\ufffd\ufffd<br>
	 * C type : CHAR[(32)]
	 */
	public byte[] szBirthday = new byte[32];
	/**
	 * \u02a1\ufffd\ufffd<br>
	 * C type : CHAR[(32)]
	 */
	public byte[] szProvince = new byte[32];
	/**
	 * \ufffd\ufffd\ufffd\ufffd<br>
	 * C type : CHAR[(48)]
	 */
	public byte[] szCity = new byte[48];
	/**
	 * \u05a4\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_CARDTYPE_E
	 */
	public int enCardType;
	/**
	 * \u05a4\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : CHAR[(32)]
	 */
	public byte[] szCardID = new byte[32];
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u03e2\ufffd\ufffd\ufffd\ufffd\ufffd\u05b6\u03a3\ufffd\u0524\ufffd\ufffd<br>
	 * C type : CHAR[(512)]
	 */
	public byte[] szExtensionField = new byte[512];
	/**
	 * \u037c\u01ac\u00b7\ufffd\ufffd\ufffd\ufffd\ufffd\u037b\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u03f4\ufffd\u037c\u01ac\ufffd\ufffd\ufffd\u8c78\ufffd\u03f1\ufffd\ufffd\ufffd\u037c\u01ac\ufffd\ufffd\u022b\u00b7\ufffd\ufffd\ufffd\ufffd\ufffd\ufffdsdkserver\u0434\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : CHAR[128]
	 */
	public byte[] szPicPath = new byte[128];
	/** C type : CHAR[32] */
	public byte[] szReserve = new byte[32];
	public PU_FACE_RECORD() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulFaceId", "szName", "enGender", "szBirthday", "szProvince", "szCity", "enCardType", "szCardID", "szExtensionField", "szPicPath", "szReserve");
	}
	public PU_FACE_RECORD(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_FACE_RECORD implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_FACE_RECORD implements Structure.ByValue {
		
	};
}
