package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public abstract class PU_FACE_DETC_DL_PARA extends Structure {
	/** \u02b9\ufffd\ufffd */
	public boolean bEnable;
	/** \ufffd\u6faf\ufffd\ufffd\ufffd\u02b1\ufffd\ufffd */
	public NativeLong ulAlarmTime;
	/** \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd */
	public NativeLong ulSensitivity;
	/** \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd */
	public NativeLong ulFaceSensitivity;
	/** \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd */
	public NativeLong ulBodySensitivity;
	/** \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd */
	public NativeLong ulFaceKpsSensitivity;
	/** \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd */
	public NativeLong ulBodyKpsSensitivity;
	/** \ufffd\ufffd\u0421\ufffd\ufffd\ufffd\ufffd */
	public NativeLong ulMinPupilDist;
	/** \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd */
	public NativeLong ulMaxPupilDist;
	/**
	 * \ufffd\ufffd\ufffd\u0123\u02bd<br>
	 * C type : PU_FACE_DETECTION_DL_MODE_E
	 */
	public int enMode;
	/** \ufffd\ufffd\ufffd\ufffd\ufffd\u0639\ufffd */
	public boolean bFaceExposure;
	/** \ufffd\ufffd\ufffd\ufffd\ufffd\u0639\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd */
	public NativeLong ulROIMeterLevel;
	/**
	 * \u05e5\ufffd\ufffd\u0123\u02bd<br>
	 * C type : FACE_DT_CAP_MODE_E
	 */
	public int enFaceCapMode;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u05e5\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : UCHAR
	 */
	public byte ulFaceCapSensitivity;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u0639\ufffd\u02b1\ufffd\ufffd<br>
	 * C type : UCHAR
	 */
	public byte uchFaceExposureTime;
	/** \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u023f\ufffd\ufffd\ufffd \ufffd\ufffd\u04e6\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd */
	public boolean bSensitivityFlage;
	/** Conversion Error : sizeof(int) */
	public PU_FACE_DETC_DL_PARA() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("bEnable", "ulAlarmTime", "ulSensitivity", "ulFaceSensitivity", "ulBodySensitivity", "ulFaceKpsSensitivity", "ulBodyKpsSensitivity", "ulMinPupilDist", "ulMaxPupilDist", "enMode", "bFaceExposure", "ulROIMeterLevel", "enFaceCapMode", "ulFaceCapSensitivity", "uchFaceExposureTime", "bSensitivityFlage");
	}
	public PU_FACE_DETC_DL_PARA(Pointer peer) {
		super(peer);
	}
	public static abstract class ByReference extends PU_FACE_DETC_DL_PARA implements Structure.ByReference {
		
	};
	public static abstract class ByValue extends PU_FACE_DETC_DL_PARA implements Structure.ByValue {
		
	};
}
