package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_FACE_INFO_DELETE_S extends Structure {
	/** \u0368\ufffd\ufffdID */
	public NativeLong ulChannelId;
	/**
	 * \ufffd\ufffd\ufffd<br>
	 * C type : PU_FACE_LIB_S
	 */
	public PU_FACE_LIB_S stFacelib;
	/** \ufffd\ufffd\u04aa\u027e\ufffd\ufffd\ufffd\ufffd\ufffd\u013f */
	public int uFaceNum;
	/**
	 * \ufffd\ufffd\u04aa\u027e\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffdid<br>
	 * C type : UINT[(100)]
	 */
	public int[] uFaceID = new int[100];
	/** C type : CHAR[32] */
	public byte[] szReserve = new byte[32];
	public PU_FACE_INFO_DELETE_S() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulChannelId", "stFacelib", "uFaceNum", "uFaceID", "szReserve");
	}
	/**
	 * @param ulChannelId \u0368\ufffd\ufffdID<br>
	 * @param stFacelib \ufffd\ufffd\ufffd<br>
	 * C type : PU_FACE_LIB_S<br>
	 * @param uFaceNum \ufffd\ufffd\u04aa\u027e\ufffd\ufffd\ufffd\ufffd\ufffd\u013f<br>
	 * @param uFaceID \ufffd\ufffd\u04aa\u027e\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffdid<br>
	 * C type : UINT[(100)]<br>
	 * @param szReserve C type : CHAR[32]
	 */
	public PU_FACE_INFO_DELETE_S(NativeLong ulChannelId, PU_FACE_LIB_S stFacelib, int uFaceNum, int uFaceID[], byte szReserve[]) {
		super();
		this.ulChannelId = ulChannelId;
		this.stFacelib = stFacelib;
		this.uFaceNum = uFaceNum;
		if ((uFaceID.length != this.uFaceID.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.uFaceID = uFaceID;
		if ((szReserve.length != this.szReserve.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserve = szReserve;
	}
	public PU_FACE_INFO_DELETE_S(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_FACE_INFO_DELETE_S implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_FACE_INFO_DELETE_S implements Structure.ByValue {
		
	};
}
