package com.summit.sdk.huawei;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_GUARD_STATE extends Structure {
	/**
	 * \ufffd\ufffd\u0377\ufffd\ufffd\ufffd\ufffd\u05f4\u032c,ulDeviceId=0\u03aa\ufffd\ufffd\u0427<br>
	 * C type : PU_GUARD_PARA_S[4]
	 */
	public PU_GUARD_PARA[] szChannelStateList = new PU_GUARD_PARA[4];
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u8c78\ufffd\u6faf\u05f4\u032c,ulDeviceId=0\u03aa\ufffd\ufffd\u0427<br>
	 * C type : PU_GUARD_PARA_S[8]
	 */
	public PU_GUARD_PARA[] szInputStateList = new PU_GUARD_PARA[8];
	/** C type : CHAR[32] */
	public byte[] szReserve = new byte[32];
	public PU_GUARD_STATE() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("szChannelStateList", "szInputStateList", "szReserve");
	}
	/**
	 * @param szChannelStateList \ufffd\ufffd\u0377\ufffd\ufffd\ufffd\ufffd\u05f4\u032c,ulDeviceId=0\u03aa\ufffd\ufffd\u0427<br>
	 * C type : PU_GUARD_PARA_S[4]<br>
	 * @param szInputStateList \ufffd\ufffd\ufffd\ufffd\ufffd\u8c78\ufffd\u6faf\u05f4\u032c,ulDeviceId=0\u03aa\ufffd\ufffd\u0427<br>
	 * C type : PU_GUARD_PARA_S[8]<br>
	 * @param szReserve C type : CHAR[32]
	 */
	public PU_GUARD_STATE(PU_GUARD_PARA szChannelStateList[], PU_GUARD_PARA szInputStateList[], byte szReserve[]) {
		super();
		if ((szChannelStateList.length != this.szChannelStateList.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szChannelStateList = szChannelStateList;
		if ((szInputStateList.length != this.szInputStateList.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szInputStateList = szInputStateList;
		if ((szReserve.length != this.szReserve.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserve = szReserve;
	}
	public PU_GUARD_STATE(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_GUARD_STATE implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_GUARD_STATE implements Structure.ByValue {
		
	};
}
