package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_HUMANCOUNT_ALG_PARAM extends Structure {
	/** \ufffd\ufffd\ufffd\u07fc\ufffd\ufffd\ufffd\ufffd\u3de8\u02b9\ufffd\ufffd */
	public boolean enHCEnable;
	/** OSD\ufffd\ufffd\ufffd\ufffd\u02b9\ufffd\ufffd */
	public boolean enOSDEnable;
	/** \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u02b9\ufffd\ufffd */
	public boolean enClearAtZero;
	/**
	 * OSD\ufffd\ufffd\ufffd\ufffd\u03bb\ufffd\ufffd<br>
	 * C type : PU_POINT_S
	 */
	public PU_POINT stOSDLocation;
	/** \ufffd\u3de8\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd */
	public NativeLong ulSensitivity;
	/** \ufffd\u6faf\ufffd\u03f1\ufffd\ufffd\ufffd\ufffd */
	public NativeLong ulAlarmTime;
	/** \ufffd\u6faf\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u05b5\ufffd\ufffd\ufffd\ufffd\ufffd\u6faf\ufffd\ufffd */
	public NativeLong ulAlarmHumanNum;
	/** \ufffd\ufffd\u0377\ufffd\ufffd\u0421\ufffd\u07f4\ufffd */
	public NativeLong ulMinHeadSize;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u03bf\ufffd\ufffd\u07e3\ufffd\ufffd\u01bc\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u06bb\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd, \ufffd\u07f6\u03bd\u04fd\ufffd\u02ee\u01bd\ufffd\ufffd\u05b1<br>
	 * C type : PU_HC_LINE_S
	 */
	public PU_HC_LINE stRefLine;
	/**
	 * \ufffd\ufffd\ufffd\ubdfd\ufffd\ufffd(\ufffd\ufffd\u02f3\u02b1\ufffd\ufffd\u053d\ufffd\ufffd\u03aa\ufffd\ufffd,\ufffd\ufffd\ufffd\ufffd\u02b1\ufffd\ufffd\u053d\ufffd\ufffd\u03aa\ufffd\ufffd)<br>
	 * C type : PU_TRIPWIRE_DIR_E
	 */
	public int enInDir;
	/** C type : CHAR[32] */
	public byte[] szReserved = new byte[32];
	public PU_HUMANCOUNT_ALG_PARAM() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("enHCEnable", "enOSDEnable", "enClearAtZero", "stOSDLocation", "ulSensitivity", "ulAlarmTime", "ulAlarmHumanNum", "ulMinHeadSize", "stRefLine", "enInDir", "szReserved");
	}
	public PU_HUMANCOUNT_ALG_PARAM(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_HUMANCOUNT_ALG_PARAM implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_HUMANCOUNT_ALG_PARAM implements Structure.ByValue {
		
	};
}
