package com.summit.sdk.huawei;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_H264_DEC_OUTPUT_INFO extends Structure {
	/** \ufffd\ufffd\u01f0\u05a1\ufffd\u05bd\ufffd\ufffd\ufffd */
	public int uPicBytes;
	/** \ufffd\ufffd\u01f0\u05a1\ufffd\ufffdI4x4 \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd */
	public int uI4MbNum;
	/** \ufffd\ufffd\u01f0\u05a1\ufffd\ufffdI8x8 \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd */
	public int uI8MbNum;
	/** \ufffd\ufffd\u01f0\u05a1\ufffd\ufffdI16x16 \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd */
	public int uI16MbNum;
	/** \ufffd\ufffd\u01f0\u05a1\ufffd\ufffdP16x16 \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd */
	public int uP16MbNum;
	/** \ufffd\ufffd\u01f0\u05a1\ufffd\ufffdP16x8 \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd */
	public int uP16x8MbNum;
	/** \ufffd\ufffd\u01f0\u05a1\ufffd\ufffdP8x16 \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd */
	public int uP8x16MbNum;
	/** \ufffd\ufffd\u01f0\u05a1\ufffd\ufffdP8x8 \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd */
	public int uP8MbNum;
	/** \ufffd\ufffd\u01f0\u05a1\ufffd\ufffdPSkip \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd */
	public int uPskipMbNum;
	/** \ufffd\ufffd\u01f0\u05a1\ufffd\ufffdIPCM \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd */
	public int uIpcmMbNum;
	public PU_H264_DEC_OUTPUT_INFO() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("uPicBytes", "uI4MbNum", "uI8MbNum", "uI16MbNum", "uP16MbNum", "uP16x8MbNum", "uP8x16MbNum", "uP8MbNum", "uPskipMbNum", "uIpcmMbNum");
	}
	public PU_H264_DEC_OUTPUT_INFO(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_H264_DEC_OUTPUT_INFO implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_H264_DEC_OUTPUT_INFO implements Structure.ByValue {
		
	};
}
