package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_HARD_DISK_STATE extends Structure {
	/** \ufffd\u6d22\ufffd\u057c\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u07b6\ufffd */
	public NativeLong ulDiskThreshold;
	/** \u04f2\ufffd\ufffd\u05f4\u032c 0-\ufffd\ufffd */
	public NativeLong ulDiskState;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u03e2<br>
	 * C type : PU_HARD_DISK_INFO_S
	 */
	public PU_HARD_DISK_INFO stHardDiskInfo;
	/**
	 * \u0524\ufffd\ufffd\ufffd\u05b6\ufffd,szReserved[0]\ufffd\ufffd\u02beDiskID 0\ufffd\u0174\ufffd\ufffd\ufffd\u03aaSD\ufffd\ufffd\ufffd\ufffd1\ufffd\u0174\ufffd\ufffd\ufffd\u03aaEMMC<br>
	 * C type : CHAR[32]
	 */
	public byte[] szReserved = new byte[32];
	public PU_HARD_DISK_STATE() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulDiskThreshold", "ulDiskState", "stHardDiskInfo", "szReserved");
	}
	/**
	 * @param ulDiskThreshold \ufffd\u6d22\ufffd\u057c\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u07b6\ufffd<br>
	 * @param ulDiskState \u04f2\ufffd\ufffd\u05f4\u032c 0-\ufffd\ufffd<br>
	 * @param stHardDiskInfo \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u03e2<br>
	 * C type : PU_HARD_DISK_INFO_S<br>
	 * @param szReserved \u0524\ufffd\ufffd\ufffd\u05b6\ufffd,szReserved[0]\ufffd\ufffd\u02beDiskID 0\ufffd\u0174\ufffd\ufffd\ufffd\u03aaSD\ufffd\ufffd\ufffd\ufffd1\ufffd\u0174\ufffd\ufffd\ufffd\u03aaEMMC<br>
	 * C type : CHAR[32]
	 */
	public PU_HARD_DISK_STATE(NativeLong ulDiskThreshold, NativeLong ulDiskState, PU_HARD_DISK_INFO stHardDiskInfo, byte szReserved[]) {
		super();
		this.ulDiskThreshold = ulDiskThreshold;
		this.ulDiskState = ulDiskState;
		this.stHardDiskInfo = stHardDiskInfo;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public PU_HARD_DISK_STATE(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_HARD_DISK_STATE implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_HARD_DISK_STATE implements Structure.ByValue {
		
	};
}
