package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_HUMANCOUNT_PARAM extends Structure {
	/** \u0368\ufffd\ufffdID */
	public NativeLong ulChannelId;
	/**
	 * \ufffd\ufffd\ufffd\u07fc\ufffd\ufffd\ufffd\ufffd\u3de8\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_HUMANCOUNT_ALG_PARAM_S
	 */
	public PU_HUMANCOUNT_ALG_PARAM stAlgParams;
	/**
	 * \ufffd\ufffd\ufffd\u07fc\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_IGT_AERADTC_LIST_S
	 */
	public PU_IGT_AERADTC_LIST stGuardAreaList;
	/**
	 * \ufffd\ufffd\ufffd\u07fc\ufffd\ufffd\ufffd\ufffd\ufffd\u01bb\ufffd<br>
	 * C type : PU_ALARM_TIME_LIST_S
	 */
	public PU_ALARM_TIME_PARA_LIST stHCGuardPlan;
	/** C type : CHAR[32] */
	public byte[] szReserved = new byte[32];
	public PU_HUMANCOUNT_PARAM() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulChannelId", "stAlgParams", "stGuardAreaList", "stHCGuardPlan", "szReserved");
	}
	/**
	 * @param ulChannelId \u0368\ufffd\ufffdID<br>
	 * @param stAlgParams \ufffd\ufffd\ufffd\u07fc\ufffd\ufffd\ufffd\ufffd\u3de8\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_HUMANCOUNT_ALG_PARAM_S<br>
	 * @param stGuardAreaList \ufffd\ufffd\ufffd\u07fc\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_IGT_AERADTC_LIST_S<br>
	 * @param stHCGuardPlan \ufffd\ufffd\ufffd\u07fc\ufffd\ufffd\ufffd\ufffd\ufffd\u01bb\ufffd<br>
	 * C type : PU_ALARM_TIME_LIST_S<br>
	 * @param szReserved C type : CHAR[32]
	 */
	public PU_HUMANCOUNT_PARAM(NativeLong ulChannelId, PU_HUMANCOUNT_ALG_PARAM stAlgParams, PU_IGT_AERADTC_LIST stGuardAreaList, PU_ALARM_TIME_PARA_LIST stHCGuardPlan, byte szReserved[]) {
		super();
		this.ulChannelId = ulChannelId;
		this.stAlgParams = stAlgParams;
		this.stGuardAreaList = stGuardAreaList;
		this.stHCGuardPlan = stHCGuardPlan;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public PU_HUMANCOUNT_PARAM(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_HUMANCOUNT_PARAM implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_HUMANCOUNT_PARAM implements Structure.ByValue {
		
	};
}
