package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public abstract class PU_IRC_PARA extends Structure {
	/**
	 * \ufffd\ufffd\u04b9\u0123\u02bd<br>
	 * C type : PU_IRC_MODE_E
	 */
	public int enIRCMode;
	/** \ufffd\ufffd\u05ea\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd */
	public NativeLong ulDayToNightThreshold;
	/** \ufffd\ufffd\u05ea\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd */
	public NativeLong ulNightToDayThreshold;
	/** \ufffd\u2cbf\ufffd\u6faf\ufffd\ufffd\ufffd\ufffd\u05ea\ufffd\u06b0\ufffd0\ufffd\ufffd\ufffd\u0375\ufffd\u01bd 1\ufffd\ufffd\ufffd\u07f5\ufffd\u01bd */
	public NativeLong ulSwitchLevel;
	/**
	 * \ufffd\ufffd\u04b9\u0123\u02bd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u02bd\ufffd\ufffd\u012c\ufffd\ufffdIRC_LUM_TRIGGER<br>
	 * C type : PU_IRC_TRIGGER_MODE_E
	 */
	public int enIRCutSwitchMode;
	/**
	 * \u01ab\ufffd\ufffd\u01ac\ufffd\ufffd\ufffd\ufffd\u0123\u02bd<br>
	 * C type : PU_COMMONMODE_SWITCH_E
	 */
	public int enPolarzerMode;
	/** Conversion Error : sizeof(int) */
	public PU_IRC_PARA() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("enIRCMode", "ulDayToNightThreshold", "ulNightToDayThreshold", "ulSwitchLevel", "enIRCutSwitchMode", "enPolarzerMode");
	}
	/**
	 * @param enIRCMode \ufffd\ufffd\u04b9\u0123\u02bd<br>
	 * C type : PU_IRC_MODE_E<br>
	 * @param ulDayToNightThreshold \ufffd\ufffd\u05ea\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * @param ulNightToDayThreshold \ufffd\ufffd\u05ea\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * @param ulSwitchLevel \ufffd\u2cbf\ufffd\u6faf\ufffd\ufffd\ufffd\ufffd\u05ea\ufffd\u06b0\ufffd0\ufffd\ufffd\ufffd\u0375\ufffd\u01bd 1\ufffd\ufffd\ufffd\u07f5\ufffd\u01bd<br>
	 * @param enIRCutSwitchMode \ufffd\ufffd\u04b9\u0123\u02bd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u02bd\ufffd\ufffd\u012c\ufffd\ufffdIRC_LUM_TRIGGER<br>
	 * C type : PU_IRC_TRIGGER_MODE_E<br>
	 * @param enPolarzerMode \u01ab\ufffd\ufffd\u01ac\ufffd\ufffd\ufffd\ufffd\u0123\u02bd<br>
	 * C type : PU_COMMONMODE_SWITCH_E
	 */
	public PU_IRC_PARA(int enIRCMode, NativeLong ulDayToNightThreshold, NativeLong ulNightToDayThreshold, NativeLong ulSwitchLevel, int enIRCutSwitchMode, int enPolarzerMode) {
		super();
		this.enIRCMode = enIRCMode;
		this.ulDayToNightThreshold = ulDayToNightThreshold;
		this.ulNightToDayThreshold = ulNightToDayThreshold;
		this.ulSwitchLevel = ulSwitchLevel;
		this.enIRCutSwitchMode = enIRCutSwitchMode;
		this.enPolarzerMode = enPolarzerMode;
	}
	public PU_IRC_PARA(Pointer peer) {
		super(peer);
	}
	public static abstract class ByReference extends PU_IRC_PARA implements Structure.ByReference {
		
	};
	public static abstract class ByValue extends PU_IRC_PARA implements Structure.ByValue {
		
	};
}
