package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_ITS_XLW_DETECTOR_INFO extends Structure {
	/** \ufffd\u0739\ufffd\ufffd\u043c\ufffd\u00b7\ufffd\u02ff\ufffd */
	public NativeLong uiTotalNum;
	/** \ufffd\ufffd\u05ea\ufffd\u01b6\ufffd\u04e6ID */
	public NativeLong uiLeftLightNo;
	/** \u05b1\ufffd\u0435\u01b6\ufffd\u04e6ID */
	public NativeLong uiStraitLightNo;
	/** \ufffd\ufffd\u05ea\ufffd\u01b6\ufffd\u04e6ID */
	public NativeLong uiRightLightNo;
	/** \ufffd\ufffd\u0377\ufffd\u0235\u01b6\ufffd\u04e6ID */
	public NativeLong uiTurnRoundLightNo;
	public PU_ITS_XLW_DETECTOR_INFO() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("uiTotalNum", "uiLeftLightNo", "uiStraitLightNo", "uiRightLightNo", "uiTurnRoundLightNo");
	}
	/**
	 * @param uiTotalNum \ufffd\u0739\ufffd\ufffd\u043c\ufffd\u00b7\ufffd\u02ff\ufffd<br>
	 * @param uiLeftLightNo \ufffd\ufffd\u05ea\ufffd\u01b6\ufffd\u04e6ID<br>
	 * @param uiStraitLightNo \u05b1\ufffd\u0435\u01b6\ufffd\u04e6ID<br>
	 * @param uiRightLightNo \ufffd\ufffd\u05ea\ufffd\u01b6\ufffd\u04e6ID<br>
	 * @param uiTurnRoundLightNo \ufffd\ufffd\u0377\ufffd\u0235\u01b6\ufffd\u04e6ID
	 */
	public PU_ITS_XLW_DETECTOR_INFO(NativeLong uiTotalNum, NativeLong uiLeftLightNo, NativeLong uiStraitLightNo, NativeLong uiRightLightNo, NativeLong uiTurnRoundLightNo) {
		super();
		this.uiTotalNum = uiTotalNum;
		this.uiLeftLightNo = uiLeftLightNo;
		this.uiStraitLightNo = uiStraitLightNo;
		this.uiRightLightNo = uiRightLightNo;
		this.uiTurnRoundLightNo = uiTurnRoundLightNo;
	}
	public PU_ITS_XLW_DETECTOR_INFO(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_ITS_XLW_DETECTOR_INFO implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_ITS_XLW_DETECTOR_INFO implements Structure.ByValue {
		
	};
}
