package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_ITS_DT_LINE_PARAM extends Structure {
	/** \u0368\ufffd\ufffdID */
	public NativeLong ulChannelId;
	/**
	 * ITS\u04b5\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : EN_ITS_TYPE
	 */
	public int enITSType;
	/** ITS\u04b5\ufffd\ufffd\ufffd\u01f7\ufffd\u02b9\ufffd\ufffd */
	public boolean bEnable;
	/**
	 * ITS\ufffd\ufffd\u01b5\ufffd\u7faf\ufffd\ufffd\ufffd\ufffd\u07f2\ufffd\ufffd\ufffd<br>
	 * C type : PU_ITS_EPOLICE_DT_LINE_PARAM_S
	 */
	public tagItsEPoliceDtLineParam stEPolice;
	public PU_ITS_DT_LINE_PARAM() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulChannelId", "enITSType", "bEnable", "stEPolice");
	}
	/**
	 * @param ulChannelId \u0368\ufffd\ufffdID<br>
	 * @param enITSType ITS\u04b5\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : EN_ITS_TYPE<br>
	 * @param bEnable ITS\u04b5\ufffd\ufffd\ufffd\u01f7\ufffd\u02b9\ufffd\ufffd<br>
	 * @param stEPolice ITS\ufffd\ufffd\u01b5\ufffd\u7faf\ufffd\ufffd\ufffd\ufffd\u07f2\ufffd\ufffd\ufffd<br>
	 * C type : PU_ITS_EPOLICE_DT_LINE_PARAM_S
	 */
	public PU_ITS_DT_LINE_PARAM(NativeLong ulChannelId, int enITSType, boolean bEnable, tagItsEPoliceDtLineParam stEPolice) {
		super();
		this.ulChannelId = ulChannelId;
		this.enITSType = enITSType;
		this.bEnable = bEnable;
		this.stEPolice = stEPolice;
	}
	public PU_ITS_DT_LINE_PARAM(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_ITS_DT_LINE_PARAM implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_ITS_DT_LINE_PARAM implements Structure.ByValue {
		
	};
}
