package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_IPCA_RULES extends Structure {
	public boolean bEnable;
	/** \ufffd\ufffd\ufffd\ufffd */
	public NativeLong ulPeriod;
	/** \u0534\ufffd\u02ff\ufffd */
	public short usSrcPort;
	/** \u013f\ufffd\u0136\u02ff\ufffd */
	public short usDstPort;
	/**
	 * \u0534IP<br>
	 * C type : CHAR[16]
	 */
	public byte[] szSrcIP = new byte[16];
	/**
	 * \u013f\ufffd\ufffdIP<br>
	 * C type : CHAR[16]
	 */
	public byte[] szDstIP = new byte[16];
	/**
	 * \u042d\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_PROTOCOL_TYPE_E
	 */
	public int enProtocolType;
	/** \ufffd\ufffd\u052a\ufffd\ufffd\ufffd\ufffd\ufffd\u03a8\u04bb\ufffd\ufffd\u02b6 */
	public NativeLong ulInstanceId;
	/**
	 * MAC<br>
	 * C type : CHAR[16]
	 */
	public byte[] szMcpIp = new byte[16];
	/**
	 * DCP<br>
	 * C type : CHAR[16]
	 */
	public byte[] szDcpIp = new byte[16];
	/** TLP */
	public NativeLong ulTlpId;
	/** MCP PORT */
	public NativeLong ulMcpPort;
	/** C type : CHAR[32] */
	public byte[] szReserve = new byte[32];
	public PU_IPCA_RULES() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("bEnable", "ulPeriod", "usSrcPort", "usDstPort", "szSrcIP", "szDstIP", "enProtocolType", "ulInstanceId", "szMcpIp", "szDcpIp", "ulTlpId", "ulMcpPort", "szReserve");
	}
	public PU_IPCA_RULES(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_IPCA_RULES implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_IPCA_RULES implements Structure.ByValue {
		
	};
}
