package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_ITGT_QUEUE_DETECT_PARAM extends Structure {
	/** \u0368\ufffd\ufffdID */
	public NativeLong ulChannelId;
	/**
	 * \ufffd\u0176\u04f3\ufffd\ufffd\ufffd\ufffd\u3de8\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_ITGT_QUEUEDETECT_ALG_PARAM_S
	 */
	public PU_ITGT_QUEUEDETECT_ALG_PARAM stAlgParams;
	/**
	 * \ufffd\u0176\u04f3\ufffd\ufffd\u023c\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_IGT_AERADTC_LIST_S
	 */
	public PU_IGT_AERADTC_LIST stAreaList;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u01bb\ufffd<br>
	 * C type : PU_ALARM_TIME_LIST_S
	 */
	public PU_ALARM_TIME_PARA_LIST stGuardPlan;
	/** C type : CHAR[32] */
	public byte[] szReserve = new byte[32];
	public PU_ITGT_QUEUE_DETECT_PARAM() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulChannelId", "stAlgParams", "stAreaList", "stGuardPlan", "szReserve");
	}
	/**
	 * @param ulChannelId \u0368\ufffd\ufffdID<br>
	 * @param stAlgParams \ufffd\u0176\u04f3\ufffd\ufffd\ufffd\ufffd\u3de8\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_ITGT_QUEUEDETECT_ALG_PARAM_S<br>
	 * @param stAreaList \ufffd\u0176\u04f3\ufffd\ufffd\u023c\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_IGT_AERADTC_LIST_S<br>
	 * @param stGuardPlan \ufffd\ufffd\ufffd\ufffd\ufffd\u01bb\ufffd<br>
	 * C type : PU_ALARM_TIME_LIST_S<br>
	 * @param szReserve C type : CHAR[32]
	 */
	public PU_ITGT_QUEUE_DETECT_PARAM(NativeLong ulChannelId, PU_ITGT_QUEUEDETECT_ALG_PARAM stAlgParams, PU_IGT_AERADTC_LIST stAreaList, PU_ALARM_TIME_PARA_LIST stGuardPlan, byte szReserve[]) {
		super();
		this.ulChannelId = ulChannelId;
		this.stAlgParams = stAlgParams;
		this.stAreaList = stAreaList;
		this.stGuardPlan = stGuardPlan;
		if ((szReserve.length != this.szReserve.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserve = szReserve;
	}
	public PU_ITGT_QUEUE_DETECT_PARAM(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_ITGT_QUEUE_DETECT_PARAM implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_ITGT_QUEUE_DETECT_PARAM implements Structure.ByValue {
		
	};
}
