package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_ITS_RADA_CTRL_CSRIM extends Structure {
	/**
	 * @see PU_ITS_SERIAL_PORT_E<br>
	 * \ufffd\ufffd\ufffd\u06ba\ufffd<br>
	 * C type : PU_ITS_SERIAL_PORT_E
	 */
	public int enSerialPortId;
	/** \ufffd\ufffd\ufffd\ufffd\ufffd\u01f7\ufffd\u02b9\ufffd\ufffd */
	public NativeLong uiRoadEnable;
	/** \ufffd\ufffd\u00b7ID\ufffd\ufffd\u02b9\ufffd\ufffdbitmap 0\u03bb\ufffd\ufffd1\ufffd\ufffd\u02be1\ufffd\ufffd\ufffd\ufffd\u02b9\ufffd\u0723\ufffd\ufffd\u0534\ufffd\ufffd\ufffd\ufffd\ufffd */
	public NativeLong uiLaneId;
	/** \ufffd\ufffd\u02bc\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd */
	public NativeLong uiLaneIdBase;
	/** \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd */
	public NativeLong uiLaneNum;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0223\ufffdWEB\ufffd\ufffd\ufffd\ufffd\u02b9\ufffd\ufffdcm\ufffd\ufffd\ufffd\ufffd\u05ea\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : ULONG[4]
	 */
	public NativeLong[] uiLaneWidth = new NativeLong[4];
	/** \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0421\ufffd\ufffd\ufffd\ub8ecWEB\ufffd\ufffd\ufffd\ufffd\u02b9\ufffd\ufffdcm\ufffd\ufffd\ufffd\ufffd\u05ea\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd */
	public NativeLong uiTrigMinInterval;
	/** \ufffd\ufffd\u05f0\ufffd\u07f6\u0223\ufffd WEB\ufffd\ufffd\ufffd\ufffd\u02b9\ufffd\ufffdcm\ufffd\ufffd\ufffd\ufffd\u05ea\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd */
	public NativeLong uiInstallHeight;
	/** \ufffd\u05f4\ufffd\ufffd\ufffd\ubcf5\ufffd\ufffd\ufffd\ufffd\ufffd\u0135\ufffd\ufffd\u01ab\ufffd\ufffd, WEB\ufffd\ufffd\ufffd\ufffd\u02b9\ufffd\ufffdcm\ufffd\ufffd\ufffd\ufffd\u05ea\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd */
	public NativeLong iInstallHOffset;
	/** \ufffd\u05f4\ufffd\ufffd\ufffd\ufffd\u4dfd\ufffd\ufffd\u0373\ufffd\ufffd\ufffd\u05ae\ufffd\ufffd\ufffd\u01ab\u05ea\ufffd\u01f6\ufffd */
	public NativeLong iDeflectionAngle;
	/** \ufffd\u05f4\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd */
	public NativeLong uiSensitivity;
	/** \ufffd\u05f4\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0235\u013b\ufffd\ufffd\ufffd */
	public NativeLong uiSensitiveBase;
	/** \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u07a3\ufffd\ufffd\ufffd\ufffd\u0675\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u07bd\ufffd\ufffd\ufffd\ufffd\u1d25\ufffd\ufffd(km/h) */
	public NativeLong uiTrigMinSpeed;
	/** \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u07a3\ufffd\ufffd\ufffd\ufffd\u0678\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u07bd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0676\u0231\ufffd\ufffd\ufffd */
	public NativeLong uiTrigMaxSpeed;
	/**
	 * @see PU_ITS_DETECT_DIR_E<br>
	 * \u033d\ufffd\u2dfd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_ITS_DETECT_DIR_E
	 */
	public int eDetectDir;
	/** C type : CHAR[32] */
	public byte[] szReserve = new byte[32];
	public PU_ITS_RADA_CTRL_CSRIM() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("enSerialPortId", "uiRoadEnable", "uiLaneId", "uiLaneIdBase", "uiLaneNum", "uiLaneWidth", "uiTrigMinInterval", "uiInstallHeight", "iInstallHOffset", "iDeflectionAngle", "uiSensitivity", "uiSensitiveBase", "uiTrigMinSpeed", "uiTrigMaxSpeed", "eDetectDir", "szReserve");
	}
	public PU_ITS_RADA_CTRL_CSRIM(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_ITS_RADA_CTRL_CSRIM implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_ITS_RADA_CTRL_CSRIM implements Structure.ByValue {
		
	};
}
