package com.summit.sdk.huawei;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_ITS_RESTRICTED_PARA_UNIT extends Structure {
	/**
	 * \ufffd\ufffd\ufffd\u01b5\ufffd\u03b2\ufffd\u0163\ufffd\u05a7\ufffd\ufffd0~9\u04bb\ufffd\ufffd10\ufffd\ufffd<br>
	 * C type : BOOL[(10)]
	 */
	public boolean[] abRestrictedNum = new boolean[10];
	/**
	 * \ufffd\ufffd\ufffd\u01b5\ufffd\ufffd\ufffd\ufffd\u06ba\ufffd\u02b1\ufffd\ufffd\ufffd<br>
	 * C type : PU_ITS_RESTRICTED_DATA_S
	 */
	public PU_ITS_RESTRICTED_DATA stRestrictedDate;
	/**
	 * \ufffd\ufffd\ufffd\u0633\ufffd\ufffd\ufffd<br>
	 * C type : PU_ITS_RESTRICTED_REGION_S[(32)]
	 */
	public PU_ITS_RESTRICTED_REGION[] astLocalPlate = new PU_ITS_RESTRICTED_REGION[32];
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u01b5\ufffd\u03b2\ufffd\u0163\ufffd\u05a7\ufffd\ufffd0~9\u04bb\ufffd\ufffd10\ufffd\ufffd<br>
	 * C type : BOOL[(10)]
	 */
	public boolean[] abLocalRestrictedNum = new boolean[10];
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u01b5\ufffd\u03b2\ufffd\u0163\ufffd\u05a7\ufffd\ufffd0~9\u04bb\ufffd\ufffd10\ufffd\ufffd<br>
	 * C type : BOOL[(10)]
	 */
	public boolean[] abNonLocalRestrictedNum = new boolean[10];
	public PU_ITS_RESTRICTED_PARA_UNIT() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("abRestrictedNum", "stRestrictedDate", "astLocalPlate", "abLocalRestrictedNum", "abNonLocalRestrictedNum");
	}
	/**
	 * @param abRestrictedNum \ufffd\ufffd\ufffd\u01b5\ufffd\u03b2\ufffd\u0163\ufffd\u05a7\ufffd\ufffd0~9\u04bb\ufffd\ufffd10\ufffd\ufffd<br>
	 * C type : BOOL[(10)]<br>
	 * @param stRestrictedDate \ufffd\ufffd\ufffd\u01b5\ufffd\ufffd\ufffd\ufffd\u06ba\ufffd\u02b1\ufffd\ufffd\ufffd<br>
	 * C type : PU_ITS_RESTRICTED_DATA_S<br>
	 * @param astLocalPlate \ufffd\ufffd\ufffd\u0633\ufffd\ufffd\ufffd<br>
	 * C type : PU_ITS_RESTRICTED_REGION_S[(32)]<br>
	 * @param abLocalRestrictedNum \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u01b5\ufffd\u03b2\ufffd\u0163\ufffd\u05a7\ufffd\ufffd0~9\u04bb\ufffd\ufffd10\ufffd\ufffd<br>
	 * C type : BOOL[(10)]<br>
	 * @param abNonLocalRestrictedNum \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u01b5\ufffd\u03b2\ufffd\u0163\ufffd\u05a7\ufffd\ufffd0~9\u04bb\ufffd\ufffd10\ufffd\ufffd<br>
	 * C type : BOOL[(10)]
	 */
	public PU_ITS_RESTRICTED_PARA_UNIT(boolean abRestrictedNum[], PU_ITS_RESTRICTED_DATA stRestrictedDate, PU_ITS_RESTRICTED_REGION astLocalPlate[], boolean abLocalRestrictedNum[], boolean abNonLocalRestrictedNum[]) {
		super();
		if ((abRestrictedNum.length != this.abRestrictedNum.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.abRestrictedNum = abRestrictedNum;
		this.stRestrictedDate = stRestrictedDate;
		if ((astLocalPlate.length != this.astLocalPlate.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.astLocalPlate = astLocalPlate;
		if ((abLocalRestrictedNum.length != this.abLocalRestrictedNum.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.abLocalRestrictedNum = abLocalRestrictedNum;
		if ((abNonLocalRestrictedNum.length != this.abNonLocalRestrictedNum.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.abNonLocalRestrictedNum = abNonLocalRestrictedNum;
	}
	public PU_ITS_RESTRICTED_PARA_UNIT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_ITS_RESTRICTED_PARA_UNIT implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_ITS_RESTRICTED_PARA_UNIT implements Structure.ByValue {
		
	};
}
