package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_ITS_RESTRICTED_PARA extends Structure {
	/** \u0368\ufffd\ufffdID */
	public NativeLong ulChannelId;
	/** \ufffd\ufffd\ufffd\u00f5\ufffd\u03b2\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd */
	public int iRestrictedNum;
	/**
	 * \u03b2\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_ITS_RESTRICTED_PARA_UNIT_S[(30)]
	 */
	public PU_ITS_RESTRICTED_PARA_UNIT[] astRestricteds = new PU_ITS_RESTRICTED_PARA_UNIT[30];
	/** C type : CHAR[256] */
	public byte[] szReserved = new byte[256];
	public PU_ITS_RESTRICTED_PARA() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulChannelId", "iRestrictedNum", "astRestricteds", "szReserved");
	}
	/**
	 * @param ulChannelId \u0368\ufffd\ufffdID<br>
	 * @param iRestrictedNum \ufffd\ufffd\ufffd\u00f5\ufffd\u03b2\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * @param astRestricteds \u03b2\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_ITS_RESTRICTED_PARA_UNIT_S[(30)]<br>
	 * @param szReserved C type : CHAR[256]
	 */
	public PU_ITS_RESTRICTED_PARA(NativeLong ulChannelId, int iRestrictedNum, PU_ITS_RESTRICTED_PARA_UNIT astRestricteds[], byte szReserved[]) {
		super();
		this.ulChannelId = ulChannelId;
		this.iRestrictedNum = iRestrictedNum;
		if ((astRestricteds.length != this.astRestricteds.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.astRestricteds = astRestricteds;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public PU_ITS_RESTRICTED_PARA(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_ITS_RESTRICTED_PARA implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_ITS_RESTRICTED_PARA implements Structure.ByValue {
		
	};
}
