package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_ISP_ALG_INFO extends Structure {
	/** \u0524\ufffd\ufffd\u0368\ufffd\ufffdID */
	public NativeLong ulChannelId;
	/**
	 * \ufffd\u3de8\ufffd\u6c7e\ufffd\ufffd\u03e2\ufffd\ufffd\u03aa\ufffd\u053a\ufffd\ufffd\ufffd\ufffd\u4ffc\ufffd\u01e3\ufffd\u0524\ufffd\ufffd64\ufffd\ufffd\ufffd\u3de8\ufffd\ufffd\u013f\u01f0\u05bb\ufffd\u0433\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04e6\u04bb\ufffd\ufffd\ufffd\u3de8<br>
	 * C type : PU_ALG_INFO_S[64]
	 */
	public PU_ALG_INFO[] szAlgInfos = new PU_ALG_INFO[64];
	/** C type : CHAR[32] */
	public byte[] szReserved = new byte[32];
	public PU_ISP_ALG_INFO() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulChannelId", "szAlgInfos", "szReserved");
	}
	/**
	 * @param ulChannelId \u0524\ufffd\ufffd\u0368\ufffd\ufffdID<br>
	 * @param szAlgInfos \ufffd\u3de8\ufffd\u6c7e\ufffd\ufffd\u03e2\ufffd\ufffd\u03aa\ufffd\u053a\ufffd\ufffd\ufffd\ufffd\u4ffc\ufffd\u01e3\ufffd\u0524\ufffd\ufffd64\ufffd\ufffd\ufffd\u3de8\ufffd\ufffd\u013f\u01f0\u05bb\ufffd\u0433\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u04e6\u04bb\ufffd\ufffd\ufffd\u3de8<br>
	 * C type : PU_ALG_INFO_S[64]<br>
	 * @param szReserved C type : CHAR[32]
	 */
	public PU_ISP_ALG_INFO(NativeLong ulChannelId, PU_ALG_INFO szAlgInfos[], byte szReserved[]) {
		super();
		this.ulChannelId = ulChannelId;
		if ((szAlgInfos.length != this.szAlgInfos.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szAlgInfos = szAlgInfos;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public PU_ISP_ALG_INFO(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_ISP_ALG_INFO implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_ISP_ALG_INFO implements Structure.ByValue {
		
	};
}
