package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_ISP_PROFILES_PARA extends Structure {
	/** \u0368\ufffd\ufffd\ufffd\ufffd */
	public NativeLong ulChannelID;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_OPT_TYPE_E
	 */
	public int enOptionType;
	/**
	 * ISP\ufffd\u05f2\u0373\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_ISP_SCENE_PARA_S
	 */
	public PU_ISP_SCENE_PARA stClassiscalScenePara;
	/**
	 * \u0524\ufffd\ufffd\ufffd\u05b6\ufffd,[0]\ufffd\ufffd\u02be\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0363\ufffd\ufffd\ufffdPU_SCENE_PARAM_TYPE_E<br>
	 * C type : CHAR[32]
	 */
	public byte[] szReserved = new byte[32];
	public PU_ISP_PROFILES_PARA() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulChannelID", "enOptionType", "stClassiscalScenePara", "szReserved");
	}
	/**
	 * @param ulChannelID \u0368\ufffd\ufffd\ufffd\ufffd<br>
	 * @param enOptionType \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_OPT_TYPE_E<br>
	 * @param stClassiscalScenePara ISP\ufffd\u05f2\u0373\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_ISP_SCENE_PARA_S<br>
	 * @param szReserved \u0524\ufffd\ufffd\ufffd\u05b6\ufffd,[0]\ufffd\ufffd\u02be\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0363\ufffd\ufffd\ufffdPU_SCENE_PARAM_TYPE_E<br>
	 * C type : CHAR[32]
	 */
	public PU_ISP_PROFILES_PARA(NativeLong ulChannelID, int enOptionType, PU_ISP_SCENE_PARA stClassiscalScenePara, byte szReserved[]) {
		super();
		this.ulChannelID = ulChannelID;
		this.enOptionType = enOptionType;
		this.stClassiscalScenePara = stClassiscalScenePara;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public PU_ISP_PROFILES_PARA(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_ISP_PROFILES_PARA implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_ISP_PROFILES_PARA implements Structure.ByValue {
		
	};
}
