package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_INVADE_POINT extends Structure {
	/** \ufffd\ufffdX\ufffd\ufffd\ufffd\ufffd\ufffd(0-352) */
	public NativeLong ulPosX;
	/** \ufffd\ufffdY\ufffd\ufffd\ufffd\ufffd\ufffd(0-288) */
	public NativeLong ulPosY;
	public PU_INVADE_POINT() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulPosX", "ulPosY");
	}
	/**
	 * @param ulPosX \ufffd\ufffdX\ufffd\ufffd\ufffd\ufffd\ufffd(0-352)<br>
	 * @param ulPosY \ufffd\ufffdY\ufffd\ufffd\ufffd\ufffd\ufffd(0-288)
	 */
	public PU_INVADE_POINT(NativeLong ulPosX, NativeLong ulPosY) {
		super();
		this.ulPosX = ulPosX;
		this.ulPosY = ulPosY;
	}
	public PU_INVADE_POINT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_INVADE_POINT implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_INVADE_POINT implements Structure.ByValue {
		
	};
}
