package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_ISP_HLC extends Structure {
	/**
	 * \u01ff\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0123\u02bd(\ufffd\u0631\u0561\ufffd\ufffd\ufffd)<br>
	 * C type : PU_COMMONMODE_SWITCH_E
	 */
	public int enHlc;
	/** panasonic\ufffd\u023c\ufffd1-3 */
	public NativeLong ulHlcLevel;
	/** C type : CHAR[32] */
	public byte[] szReserve = new byte[32];
	public PU_ISP_HLC() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("enHlc", "ulHlcLevel", "szReserve");
	}
	/**
	 * @param enHlc \u01ff\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0123\u02bd(\ufffd\u0631\u0561\ufffd\ufffd\ufffd)<br>
	 * C type : PU_COMMONMODE_SWITCH_E<br>
	 * @param ulHlcLevel panasonic\ufffd\u023c\ufffd1-3<br>
	 * @param szReserve C type : CHAR[32]
	 */
	public PU_ISP_HLC(int enHlc, NativeLong ulHlcLevel, byte szReserve[]) {
		super();
		this.enHlc = enHlc;
		this.ulHlcLevel = ulHlcLevel;
		if ((szReserve.length != this.szReserve.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserve = szReserve;
	}
	public PU_ISP_HLC(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_ISP_HLC implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_ISP_HLC implements Structure.ByValue {
		
	};
}
