package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_ITS_RESTRICTED_DATA extends Structure {
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u02bd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u03b2\ufffd\u017b\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_ITS_RESTRICTED_INDEX_TYPE_E
	 */
	public int enIndexType;
	/**
	 * \u02b9\ufffd\ufffd, \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd 7 \ufffd\ufffd, \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd10\ufffd\ufffd<br>
	 * C type : BOOL[(10)]
	 */
	public boolean[] abRestrictedU = new boolean[10];
	/** \u03b2\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u02bc\u02b1\ufffd\ufffd */
	public NativeLong ulStartTime;
	/** \u03b2\ufffd\ufffd\ufffd\ufffd\ufffd\u043d\ufffd\ufffd\ufffd\u02b1\ufffd\ufffd */
	public NativeLong ulEndTime;
	public PU_ITS_RESTRICTED_DATA() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("enIndexType", "abRestrictedU", "ulStartTime", "ulEndTime");
	}
	/**
	 * @param enIndexType \ufffd\ufffd\ufffd\ufffd\u02bd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u03b2\ufffd\u017b\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_ITS_RESTRICTED_INDEX_TYPE_E<br>
	 * @param abRestrictedU \u02b9\ufffd\ufffd, \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd 7 \ufffd\ufffd, \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd10\ufffd\ufffd<br>
	 * C type : BOOL[(10)]<br>
	 * @param ulStartTime \u03b2\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u02bc\u02b1\ufffd\ufffd<br>
	 * @param ulEndTime \u03b2\ufffd\ufffd\ufffd\ufffd\ufffd\u043d\ufffd\ufffd\ufffd\u02b1\ufffd\ufffd
	 */
	public PU_ITS_RESTRICTED_DATA(int enIndexType, boolean abRestrictedU[], NativeLong ulStartTime, NativeLong ulEndTime) {
		super();
		this.enIndexType = enIndexType;
		if ((abRestrictedU.length != this.abRestrictedU.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.abRestrictedU = abRestrictedU;
		this.ulStartTime = ulStartTime;
		this.ulEndTime = ulEndTime;
	}
	public PU_ITS_RESTRICTED_DATA(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_ITS_RESTRICTED_DATA implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_ITS_RESTRICTED_DATA implements Structure.ByValue {
		
	};
}
