package com.summit.sdk.huawei;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_ITS_LANE_INFO_BASE_UNIT extends Structure {
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_ITS_ROAD_DIR_TYPE_E
	 */
	public int enLaneDirType;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u02bb\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_ITS_ROAD_DRV_DIR_E
	 */
	public int enLaneDrvDir;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u01b5\ufffd\ufffd\ufffd\u02f6\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_ITS_CAR_DRV_DIR_E
	 */
	public int enCarDrvDir;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u037e<br>
	 * C type : PU_ITS_ROAD_PURPOSE_E
	 */
	public int enLanePurpose;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_ITS_ROAD_ATTRIBUTE_E
	 */
	public int enLaneAttribute;
	/** \ufffd\ufffd\ufffd\u04f3\ufffd\ufffd\ufffd\ufffd\ufffd, OSD \ufffd\ufffd\ufffd\u04e3\ufffd\u04bb\ufffd\ufffd\ufffd\ufffd\u02b5\ufffd\u02b3\ufffd\ufffd\ufffd\u01a5\ufffd\ufffd */
	public int iOSDLaneNO;
	/** \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd, \ufffd\ufffd\ufffd\u06b6\ufffd\u04e6\ufffd\u05f4\uf862\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffdIO \ufffd\ufffd\ufffd\ufffd */
	public int iBindingDeviceCode;
	/** \u0524\u00bc\ufffd\ufffd\u02bc\u02b1\ufffd\ufffd */
	public int iPreRecordStart;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0363\ufffd\ufffd\ufffd\ufffd\u06b5\ufffd\u0377\u03a5\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : ITS_ROAD_SIDE_SCENE_E
	 */
	public int enLaneSideScene;
	/** C type : CHAR[32 - 1] */
	public byte[] szReserve = new byte[32 - 1];
	public PU_ITS_LANE_INFO_BASE_UNIT() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("enLaneDirType", "enLaneDrvDir", "enCarDrvDir", "enLanePurpose", "enLaneAttribute", "iOSDLaneNO", "iBindingDeviceCode", "iPreRecordStart", "enLaneSideScene", "szReserve");
	}
	public PU_ITS_LANE_INFO_BASE_UNIT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_ITS_LANE_INFO_BASE_UNIT implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_ITS_LANE_INFO_BASE_UNIT implements Structure.ByValue {
		
	};
}
