package com.summit.sdk.huawei;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_ISP_PARTICULAR_PARA_EX extends Structure {
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffdISP\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_ISP_PARTICULAR_PARA_TYPE_E
	 */
	public int enISPParamType;
	/**
	 * ISP\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_SNAPSHOT_PARTICULAR_PARA_S
	 */
	public PU_SNAPSHOT_PARTICULAR_PARA stISPParam;
	public PU_ISP_PARTICULAR_PARA_EX() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("enISPParamType", "stISPParam");
	}
	/**
	 * @param enISPParamType \ufffd\ufffd\ufffd\ufffd\ufffd\ufffdISP\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_ISP_PARTICULAR_PARA_TYPE_E<br>
	 * @param stISPParam ISP\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_SNAPSHOT_PARTICULAR_PARA_S
	 */
	public PU_ISP_PARTICULAR_PARA_EX(int enISPParamType, PU_SNAPSHOT_PARTICULAR_PARA stISPParam) {
		super();
		this.enISPParamType = enISPParamType;
		this.stISPParam = stISPParam;
	}
	public PU_ISP_PARTICULAR_PARA_EX(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_ISP_PARTICULAR_PARA_EX implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_ISP_PARTICULAR_PARA_EX implements Structure.ByValue {
		
	};
}
