package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_INVADE_PARA extends Structure {
	/** \u02b9\ufffd\ufffd */
	public NativeLong lEnable;
	/** \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd */
	public NativeLong ulSensitivity;
	/** \ufffd\u6faf\ufffd\ufffd\ufffd\u02b1\ufffd\ufffd\ufffd\ufffd1~255s\ufffd\ufffd\u00ffx\ufffd\ufffd\ufffd\ufffd\u04bb\ufffd\ufffd\ufffd\u01f7\ufffd\ufffd\u06b8\u6faf\u05f4\u032c */
	public NativeLong ulDeteInterval;
	/** \u013f\ufffd\ufffd\ufffd\ufffd\u0421\ufffd\u07f4\ufffd(5-20) */
	public NativeLong ulMiniSize;
	/** \u013f\ufffd\ufffd\ufffd\ufffd\ufffd\u07f4\ufffd(10-30) */
	public NativeLong ulMaxSize;
	/**
	 * \ufffd\ufffd\ufffd\u05bc\ufffd\ufffd\ufffd\ufffd\ufffd\u0431\ufffd<br>
	 * C type : PU_INVADE_LINE_LIST_S
	 */
	public PU_INVADE_LINE_LIST stLineList;
	public PU_INVADE_PARA() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("lEnable", "ulSensitivity", "ulDeteInterval", "ulMiniSize", "ulMaxSize", "stLineList");
	}
	/**
	 * @param lEnable \u02b9\ufffd\ufffd<br>
	 * @param ulSensitivity \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * @param ulDeteInterval \ufffd\u6faf\ufffd\ufffd\ufffd\u02b1\ufffd\ufffd\ufffd\ufffd1~255s\ufffd\ufffd\u00ffx\ufffd\ufffd\ufffd\ufffd\u04bb\ufffd\ufffd\ufffd\u01f7\ufffd\ufffd\u06b8\u6faf\u05f4\u032c<br>
	 * @param ulMiniSize \u013f\ufffd\ufffd\ufffd\ufffd\u0421\ufffd\u07f4\ufffd(5-20)<br>
	 * @param ulMaxSize \u013f\ufffd\ufffd\ufffd\ufffd\ufffd\u07f4\ufffd(10-30)<br>
	 * @param stLineList \ufffd\ufffd\ufffd\u05bc\ufffd\ufffd\ufffd\ufffd\ufffd\u0431\ufffd<br>
	 * C type : PU_INVADE_LINE_LIST_S
	 */
	public PU_INVADE_PARA(NativeLong lEnable, NativeLong ulSensitivity, NativeLong ulDeteInterval, NativeLong ulMiniSize, NativeLong ulMaxSize, PU_INVADE_LINE_LIST stLineList) {
		super();
		this.lEnable = lEnable;
		this.ulSensitivity = ulSensitivity;
		this.ulDeteInterval = ulDeteInterval;
		this.ulMiniSize = ulMiniSize;
		this.ulMaxSize = ulMaxSize;
		this.stLineList = stLineList;
	}
	public PU_INVADE_PARA(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_INVADE_PARA implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_INVADE_PARA implements Structure.ByValue {
		
	};
}
