package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_INVADE_ALARM_PARA extends Structure {
	/** \ufffd\ufffd\u01b5\u0368\ufffd\ufffdID */
	public NativeLong ulChannel;
	/**
	 * \ufffd\ufffd\ufffd\u05bc\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_INVADE_PARA_S
	 */
	public PU_INVADE_PARA stInvadePara;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u02b1\ufffd\ufffd\ufffd\u0431\ufffd<br>
	 * C type : PU_ALARM_TIME_LIST_S
	 */
	public PU_ALARM_TIME_PARA_LIST stAlarmTimeList;
	public PU_INVADE_ALARM_PARA() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulChannel", "stInvadePara", "stAlarmTimeList");
	}
	/**
	 * @param ulChannel \ufffd\ufffd\u01b5\u0368\ufffd\ufffdID<br>
	 * @param stInvadePara \ufffd\ufffd\ufffd\u05bc\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_INVADE_PARA_S<br>
	 * @param stAlarmTimeList \ufffd\ufffd\ufffd\ufffd\u02b1\ufffd\ufffd\ufffd\u0431\ufffd<br>
	 * C type : PU_ALARM_TIME_LIST_S
	 */
	public PU_INVADE_ALARM_PARA(NativeLong ulChannel, PU_INVADE_PARA stInvadePara, PU_ALARM_TIME_PARA_LIST stAlarmTimeList) {
		super();
		this.ulChannel = ulChannel;
		this.stInvadePara = stInvadePara;
		this.stAlarmTimeList = stAlarmTimeList;
	}
	public PU_INVADE_ALARM_PARA(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_INVADE_ALARM_PARA implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_INVADE_ALARM_PARA implements Structure.ByValue {
		
	};
}
