package com.summit.sdk.huawei;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_ITS_DEV_INFO extends Structure {
	/**
	 * @see PU_EXTRA_DEVICE_TYPE_E<br>
	 * \ufffd\ufffd\ufffd\ufffd\u042d\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_EXTRA_DEVICE_TYPE_E
	 */
	public int enDeviceProtelType;
	/**
	 * \ufffd\u05f4\ufffd\ufffd\u8c78\ufffd\ufffd\u03e2<br>
	 * C type : PU_RADAR_CTRL_INFO_S
	 */
	public PU_RADAR_CTRL_INFO stRadarInfo;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u042d\ufffd\ufffd<br>
	 * C type : PU_VEHICLE_DETECTOR_INFO_S
	 */
	public PU_VEHICLE_DETECTOR_INFO stVehicleDetectorInfo;
	/**
	 * IO\u042d\ufffd\ufffd<br>
	 * C type : PU_IO_DETECTOR_INFO_S
	 */
	public PU_IO_DETECTOR_INFO stIODetectorInfo;
	/** C type : CHAR[32] */
	public byte[] szReserve = new byte[32];
	public PU_ITS_DEV_INFO() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("enDeviceProtelType", "stRadarInfo", "stVehicleDetectorInfo", "stIODetectorInfo", "szReserve");
	}
	/**
	 * @param enDeviceProtelType @see PU_EXTRA_DEVICE_TYPE_E<br>
	 * \ufffd\ufffd\ufffd\ufffd\u042d\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_EXTRA_DEVICE_TYPE_E<br>
	 * @param stRadarInfo \ufffd\u05f4\ufffd\ufffd\u8c78\ufffd\ufffd\u03e2<br>
	 * C type : PU_RADAR_CTRL_INFO_S<br>
	 * @param stVehicleDetectorInfo \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u042d\ufffd\ufffd<br>
	 * C type : PU_VEHICLE_DETECTOR_INFO_S<br>
	 * @param stIODetectorInfo IO\u042d\ufffd\ufffd<br>
	 * C type : PU_IO_DETECTOR_INFO_S<br>
	 * @param szReserve C type : CHAR[32]
	 */
	public PU_ITS_DEV_INFO(int enDeviceProtelType, PU_RADAR_CTRL_INFO stRadarInfo, PU_VEHICLE_DETECTOR_INFO stVehicleDetectorInfo, PU_IO_DETECTOR_INFO stIODetectorInfo, byte szReserve[]) {
		super();
		this.enDeviceProtelType = enDeviceProtelType;
		this.stRadarInfo = stRadarInfo;
		this.stVehicleDetectorInfo = stVehicleDetectorInfo;
		this.stIODetectorInfo = stIODetectorInfo;
		if ((szReserve.length != this.szReserve.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserve = szReserve;
	}
	public PU_ITS_DEV_INFO(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_ITS_DEV_INFO implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_ITS_DEV_INFO implements Structure.ByValue {
		
	};
}
