package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_MASTER_SLAVE_CALIBRATION_STATUS extends Structure {
	/** \ufffd\ufffd\ufffd\u04f9\ufffd\ufffd\ufffdID, \ufffd\ufffd\u0579\u0524\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u01f0\ufffd\ufffd\u02b9\ufffd\ufffd */
	public NativeLong ulGroupID;
	/** C type : PU_CALIBRATION_STATUS_E */
	public int enStatus;
	/** C type : CHAR[32] */
	public byte[] szReserved = new byte[32];
	public PU_MASTER_SLAVE_CALIBRATION_STATUS() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulGroupID", "enStatus", "szReserved");
	}
	/**
	 * @param ulGroupID \ufffd\ufffd\ufffd\u04f9\ufffd\ufffd\ufffdID, \ufffd\ufffd\u0579\u0524\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u01f0\ufffd\ufffd\u02b9\ufffd\ufffd<br>
	 * @param enStatus C type : PU_CALIBRATION_STATUS_E<br>
	 * @param szReserved C type : CHAR[32]
	 */
	public PU_MASTER_SLAVE_CALIBRATION_STATUS(NativeLong ulGroupID, int enStatus, byte szReserved[]) {
		super();
		this.ulGroupID = ulGroupID;
		this.enStatus = enStatus;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public PU_MASTER_SLAVE_CALIBRATION_STATUS(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_MASTER_SLAVE_CALIBRATION_STATUS implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_MASTER_SLAVE_CALIBRATION_STATUS implements Structure.ByValue {
		
	};
}
