package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_MASK_AREA_PARA extends Structure {
	/** C type : PU_IGT_POINT_S[4] */
	public PU_IGT_POINT[] stAreaPara = new PU_IGT_POINT[4];
	/** \ufffd\ufffd\u026b */
	public NativeLong ulColor;
	/**
	 * \u0378\ufffd\ufffd\ufffd\u0223\ufffd\ufffd\u0772\ufffd\u05a7\ufffd\ufffd<br>
	 * C type : UCHAR
	 */
	public byte ucAlpha;
	/** C type : CHAR[32] */
	public byte[] szReserve = new byte[32];
	public PU_MASK_AREA_PARA() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("stAreaPara", "ulColor", "ucAlpha", "szReserve");
	}
	/**
	 * @param stAreaPara C type : PU_IGT_POINT_S[4]<br>
	 * @param ulColor \ufffd\ufffd\u026b<br>
	 * @param ucAlpha \u0378\ufffd\ufffd\ufffd\u0223\ufffd\ufffd\u0772\ufffd\u05a7\ufffd\ufffd<br>
	 * C type : UCHAR<br>
	 * @param szReserve C type : CHAR[32]
	 */
	public PU_MASK_AREA_PARA(PU_IGT_POINT stAreaPara[], NativeLong ulColor, byte ucAlpha, byte szReserve[]) {
		super();
		if ((stAreaPara.length != this.stAreaPara.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.stAreaPara = stAreaPara;
		this.ulColor = ulColor;
		this.ucAlpha = ucAlpha;
		if ((szReserve.length != this.szReserve.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserve = szReserve;
	}
	public PU_MASK_AREA_PARA(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_MASK_AREA_PARA implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_MASK_AREA_PARA implements Structure.ByValue {
		
	};
}
