package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.Union;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_MASTER_SLAVE_CALIBRATION extends Structure {
	/** \ufffd\ufffd\ufffd\u04f9\ufffd\ufffd\ufffdID, \ufffd\ufffd\u0579\u0524\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u01f0\ufffd\ufffd\u02b9\ufffd\ufffd */
	public NativeLong ulGroupID;
	/**
	 * \ufffd\uada8\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_CALIBRATION_TYPE_E
	 */
	public int enType;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u0377\ufffd\ufffd\u03e2<br>
	 * C type : PU_CALIBRATION_LEN_INFO_S
	 */
	public PU_CALIBRATION_LEN_INFO stMasterLen;
	/**
	 * \ufffd\u04fe\ufffd\u0377\ufffd\ufffd\u03e2<br>
	 * C type : PU_CALIBRATION_LEN_INFO_S
	 */
	public PU_CALIBRATION_LEN_INFO stSlaveLen;
	/** C type : config_union */
	public config_union config;
	/** C type : CHAR[32] */
	public byte[] szReserved = new byte[32];
	/** <i>native declaration : E:\video\HWPuSDK.h:10143</i> */
	public static class config_union extends Union {
		/**
		 * \ufffd\u05b6\ufffd\ufffd\uada8\ufffd\ufffd\ufffd\ufffd<br>
		 * C type : PU_MANUAL_CALIBRATION_CONFIG_S
		 */
		public PU_MANUAL_CALIBRATION_CONFIG stManual;
		/**
		 * \ufffd\u0536\ufffd\ufffd\uada8\ufffd\ufffd\ufffd\ufffd<br>
		 * C type : PU_AUTO_CALIBRATION_CONFIG_S
		 */
		public PU_AUTO_CALIBRATION_CONFIG stAuto;
		public config_union() {
			super();
		}
		/**
		 * @param stManual \ufffd\u05b6\ufffd\ufffd\uada8\ufffd\ufffd\ufffd\ufffd<br>
		 * C type : PU_MANUAL_CALIBRATION_CONFIG_S
		 */
		public config_union(PU_MANUAL_CALIBRATION_CONFIG stManual) {
			super();
			this.stManual = stManual;
			setType(PU_MANUAL_CALIBRATION_CONFIG.class);
		}
		/**
		 * @param stAuto \ufffd\u0536\ufffd\ufffd\uada8\ufffd\ufffd\ufffd\ufffd<br>
		 * C type : PU_AUTO_CALIBRATION_CONFIG_S
		 */
		public config_union(PU_AUTO_CALIBRATION_CONFIG stAuto) {
			super();
			this.stAuto = stAuto;
			setType(PU_AUTO_CALIBRATION_CONFIG.class);
		}
		public config_union(Pointer peer) {
			super(peer);
		}
		public static class ByReference extends config_union implements Structure.ByReference {
			
		};
		public static class ByValue extends config_union implements Structure.ByValue {
			
		};
	};
	public PU_MASTER_SLAVE_CALIBRATION() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulGroupID", "enType", "stMasterLen", "stSlaveLen", "config", "szReserved");
	}
	/**
	 * @param ulGroupID \ufffd\ufffd\ufffd\u04f9\ufffd\ufffd\ufffdID, \ufffd\ufffd\u0579\u0524\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u01f0\ufffd\ufffd\u02b9\ufffd\ufffd<br>
	 * @param enType \ufffd\uada8\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_CALIBRATION_TYPE_E<br>
	 * @param stMasterLen \ufffd\ufffd\ufffd\ufffd\u0377\ufffd\ufffd\u03e2<br>
	 * C type : PU_CALIBRATION_LEN_INFO_S<br>
	 * @param stSlaveLen \ufffd\u04fe\ufffd\u0377\ufffd\ufffd\u03e2<br>
	 * C type : PU_CALIBRATION_LEN_INFO_S<br>
	 * @param config C type : config_union<br>
	 * @param szReserved C type : CHAR[32]
	 */
	public PU_MASTER_SLAVE_CALIBRATION(NativeLong ulGroupID, int enType, PU_CALIBRATION_LEN_INFO stMasterLen, PU_CALIBRATION_LEN_INFO stSlaveLen, config_union config, byte szReserved[]) {
		super();
		this.ulGroupID = ulGroupID;
		this.enType = enType;
		this.stMasterLen = stMasterLen;
		this.stSlaveLen = stSlaveLen;
		this.config = config;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public PU_MASTER_SLAVE_CALIBRATION(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_MASTER_SLAVE_CALIBRATION implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_MASTER_SLAVE_CALIBRATION implements Structure.ByValue {
		
	};
}
