package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_MASTER_SLAVE_PER_GROUP_PARA extends Structure {
	/**
	 * \ufffd\ufffd\ufffd\u04fd\ufffd\u026b<br>
	 * C type : PU_MASTER_SLAVE_ROLE_E
	 */
	public int enRole;
	/** \ufffd\ufffd\ufffd\u04f9\ufffd\ufffd\ufffdID, \ufffd\ufffd\u0579\u0524\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u01f0\ufffd\ufffd\u02b9\ufffd\ufffd */
	public NativeLong ulGroupID;
	/**
	 * \ufffd\ufffd\ufffd\ufffdIP<br>
	 * C type : CHAR[16]
	 */
	public byte[] szMasterIP = new byte[16];
	/**
	 * \ufffd\u04fb\ufffdIP<br>
	 * C type : CHAR[16]
	 */
	public byte[] szSlaveIP = new byte[16];
	/** \ufffd\u04fb\ufffd\u02ff\u06ba\ufffd */
	public int iSlavePort;
	/** C type : CHAR[32] */
	public byte[] szReserved = new byte[32];
	public PU_MASTER_SLAVE_PER_GROUP_PARA() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("enRole", "ulGroupID", "szMasterIP", "szSlaveIP", "iSlavePort", "szReserved");
	}
	/**
	 * @param enRole \ufffd\ufffd\ufffd\u04fd\ufffd\u026b<br>
	 * C type : PU_MASTER_SLAVE_ROLE_E<br>
	 * @param ulGroupID \ufffd\ufffd\ufffd\u04f9\ufffd\ufffd\ufffdID, \ufffd\ufffd\u0579\u0524\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u01f0\ufffd\ufffd\u02b9\ufffd\ufffd<br>
	 * @param szMasterIP \ufffd\ufffd\ufffd\ufffdIP<br>
	 * C type : CHAR[16]<br>
	 * @param szSlaveIP \ufffd\u04fb\ufffdIP<br>
	 * C type : CHAR[16]<br>
	 * @param iSlavePort \ufffd\u04fb\ufffd\u02ff\u06ba\ufffd<br>
	 * @param szReserved C type : CHAR[32]
	 */
	public PU_MASTER_SLAVE_PER_GROUP_PARA(int enRole, NativeLong ulGroupID, byte szMasterIP[], byte szSlaveIP[], int iSlavePort, byte szReserved[]) {
		super();
		this.enRole = enRole;
		this.ulGroupID = ulGroupID;
		if ((szMasterIP.length != this.szMasterIP.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szMasterIP = szMasterIP;
		if ((szSlaveIP.length != this.szSlaveIP.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szSlaveIP = szSlaveIP;
		this.iSlavePort = iSlavePort;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public PU_MASTER_SLAVE_PER_GROUP_PARA(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_MASTER_SLAVE_PER_GROUP_PARA implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_MASTER_SLAVE_PER_GROUP_PARA implements Structure.ByValue {
		
	};
}
