package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_MEDIA_PLAY_STOP_INFO extends Structure {
	/** \u0368\ufffd\ufffd\ufffd\ufffd */
	public NativeLong ulChannelId;
	/** \u00fd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u03a8\u04bb\ufffd\ufffd\u05be */
	public NativeLong ulSessionId;
	/**
	 * \ufffd\ufffd\ufffd\ufffd<br>
	 * C type : CHAR[32]
	 */
	public byte[] szReserved = new byte[32];
	public PU_MEDIA_PLAY_STOP_INFO() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulChannelId", "ulSessionId", "szReserved");
	}
	/**
	 * @param ulChannelId \u0368\ufffd\ufffd\ufffd\ufffd<br>
	 * @param ulSessionId \u00fd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u03a8\u04bb\ufffd\ufffd\u05be<br>
	 * @param szReserved \ufffd\ufffd\ufffd\ufffd<br>
	 * C type : CHAR[32]
	 */
	public PU_MEDIA_PLAY_STOP_INFO(NativeLong ulChannelId, NativeLong ulSessionId, byte szReserved[]) {
		super();
		this.ulChannelId = ulChannelId;
		this.ulSessionId = ulSessionId;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public PU_MEDIA_PLAY_STOP_INFO(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_MEDIA_PLAY_STOP_INFO implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_MEDIA_PLAY_STOP_INFO implements Structure.ByValue {
		
	};
}
