package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_MEDIA_PLAY_RSP extends Structure {
	/** \u00fd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u03a8\u04bb\ufffd\ufffd\u05be */
	public NativeLong ulSessionId;
	/**
	 * \ufffd\ufffd\ufffd\u0376\u02f5\u0136\u02ff\ufffd\ufffd\ufffd\u03e2<br>
	 * C type : PU_PORT_INFO_S
	 */
	public PU_PORT_INFO stPeerPortInfo;
	/**
	 * \ufffd\ufffd\ufffd\u0376\u02f5\ufffdIP<br>
	 * C type : CHAR[16]
	 */
	public byte[] szPeerIp = new byte[16];
	/**
	 * \ufffd\ufffd\u01b5\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_ENCODE_TYPE_E
	 */
	public int enVideoEncodeType;
	/**
	 * \ufffd\ufffd\u01b5\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_ENCODE_TYPE_E
	 */
	public int enAudioEncodeType;
	/**
	 * \u00bc\ufffd\ufffd\u02b5\ufffd\u02bf\ufffd\u02bc\u02b1\ufffd\ufffd<br>
	 * C type : PU_TIME_S
	 */
	public PU_TIME stStartTime;
	/**
	 * \u00bc\ufffd\ufffd\u02b5\ufffd\u02bd\ufffd\ufffd\ufffd\u02b1\ufffd\ufffd<br>
	 * C type : PU_TIME_S
	 */
	public PU_TIME stEndTime;
	/** C type : CHAR[32] */
	public byte[] szReserved = new byte[32];
	public PU_MEDIA_PLAY_RSP() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulSessionId", "stPeerPortInfo", "szPeerIp", "enVideoEncodeType", "enAudioEncodeType", "stStartTime", "stEndTime", "szReserved");
	}
	/**
	 * @param ulSessionId \u00fd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u03a8\u04bb\ufffd\ufffd\u05be<br>
	 * @param stPeerPortInfo \ufffd\ufffd\ufffd\u0376\u02f5\u0136\u02ff\ufffd\ufffd\ufffd\u03e2<br>
	 * C type : PU_PORT_INFO_S<br>
	 * @param szPeerIp \ufffd\ufffd\ufffd\u0376\u02f5\ufffdIP<br>
	 * C type : CHAR[16]<br>
	 * @param enVideoEncodeType \ufffd\ufffd\u01b5\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_ENCODE_TYPE_E<br>
	 * @param enAudioEncodeType \ufffd\ufffd\u01b5\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_ENCODE_TYPE_E<br>
	 * @param stStartTime \u00bc\ufffd\ufffd\u02b5\ufffd\u02bf\ufffd\u02bc\u02b1\ufffd\ufffd<br>
	 * C type : PU_TIME_S<br>
	 * @param stEndTime \u00bc\ufffd\ufffd\u02b5\ufffd\u02bd\ufffd\ufffd\ufffd\u02b1\ufffd\ufffd<br>
	 * C type : PU_TIME_S<br>
	 * @param szReserved C type : CHAR[32]
	 */
	public PU_MEDIA_PLAY_RSP(NativeLong ulSessionId, PU_PORT_INFO stPeerPortInfo, byte szPeerIp[], int enVideoEncodeType, int enAudioEncodeType, PU_TIME stStartTime, PU_TIME stEndTime, byte szReserved[]) {
		super();
		this.ulSessionId = ulSessionId;
		this.stPeerPortInfo = stPeerPortInfo;
		if ((szPeerIp.length != this.szPeerIp.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szPeerIp = szPeerIp;
		this.enVideoEncodeType = enVideoEncodeType;
		this.enAudioEncodeType = enAudioEncodeType;
		this.stStartTime = stStartTime;
		this.stEndTime = stEndTime;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public PU_MEDIA_PLAY_RSP(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_MEDIA_PLAY_RSP implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_MEDIA_PLAY_RSP implements Structure.ByValue {
		
	};
}
