package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_OSD_PICTURE_PARA extends Structure {
	public NativeLong ulChannelID;
	/** \u02b9\ufffd\ufffd\ufffd\ufffd\ufffd */
	public boolean bEnable;
	/**
	 * \u037c\u01ac\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u03e2<br>
	 * C type : PU_AREA_INFO_S
	 */
	public PU_AREA_INFO stAreaInfo;
	/**
	 * \u037c\u01ac\ufffd\ufffd\u00b7\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : CHAR[128]
	 */
	public byte[] szPicFileName = new byte[128];
	/** C type : CHAR[32] */
	public byte[] szReserve = new byte[32];
	public PU_OSD_PICTURE_PARA() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulChannelID", "bEnable", "stAreaInfo", "szPicFileName", "szReserve");
	}
	/**
	 * @param bEnable \u02b9\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * @param stAreaInfo \u037c\u01ac\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u03e2<br>
	 * C type : PU_AREA_INFO_S<br>
	 * @param szPicFileName \u037c\u01ac\ufffd\ufffd\u00b7\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : CHAR[128]<br>
	 * @param szReserve C type : CHAR[32]
	 */
	public PU_OSD_PICTURE_PARA(NativeLong ulChannelID, boolean bEnable, PU_AREA_INFO stAreaInfo, byte szPicFileName[], byte szReserve[]) {
		super();
		this.ulChannelID = ulChannelID;
		this.bEnable = bEnable;
		this.stAreaInfo = stAreaInfo;
		if ((szPicFileName.length != this.szPicFileName.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szPicFileName = szPicFileName;
		if ((szReserve.length != this.szReserve.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserve = szReserve;
	}
	public PU_OSD_PICTURE_PARA(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_OSD_PICTURE_PARA implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_OSD_PICTURE_PARA implements Structure.ByValue {
		
	};
}
