package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_PRE_CHANNEL_INFO extends Structure {
	/** \u0368\ufffd\ufffdid */
	public NativeLong ulChannelID;
	/**
	 * \u0368\ufffd\ufffd\u05f4\u032c<br>
	 * C type : PU_CHANNEL_STATUS_E
	 */
	public int enSlaveChanStatus;
	/** C type : CHAR[32] */
	public byte[] szReserved = new byte[32];
	public PU_PRE_CHANNEL_INFO() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulChannelID", "enSlaveChanStatus", "szReserved");
	}
	/**
	 * @param ulChannelID \u0368\ufffd\ufffdid<br>
	 * @param enSlaveChanStatus \u0368\ufffd\ufffd\u05f4\u032c<br>
	 * C type : PU_CHANNEL_STATUS_E<br>
	 * @param szReserved C type : CHAR[32]
	 */
	public PU_PRE_CHANNEL_INFO(NativeLong ulChannelID, int enSlaveChanStatus, byte szReserved[]) {
		super();
		this.ulChannelID = ulChannelID;
		this.enSlaveChanStatus = enSlaveChanStatus;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public PU_PRE_CHANNEL_INFO(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_PRE_CHANNEL_INFO implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_PRE_CHANNEL_INFO implements Structure.ByValue {
		
	};
}
