package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_PTZ_PRESET_FREEZE extends Structure {
	/** \u0368\ufffd\ufffdID */
	public NativeLong ulChannelID;
	/** \u02b9\ufffd\ufffd */
	public boolean bFreezeEnable;
	public PU_PTZ_PRESET_FREEZE() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulChannelID", "bFreezeEnable");
	}
	/**
	 * @param ulChannelID \u0368\ufffd\ufffdID<br>
	 * @param bFreezeEnable \u02b9\ufffd\ufffd
	 */
	public PU_PTZ_PRESET_FREEZE(NativeLong ulChannelID, boolean bFreezeEnable) {
		super();
		this.ulChannelID = ulChannelID;
		this.bFreezeEnable = bFreezeEnable;
	}
	public PU_PTZ_PRESET_FREEZE(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_PTZ_PRESET_FREEZE implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_PTZ_PRESET_FREEZE implements Structure.ByValue {
		
	};
}
