package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_PTZ_PARA extends Structure {
	/** \ufffd\ufffd\u0328\ufffd\ufffd\ufffd */
	public NativeLong ulPtzId;
	/** \ufffd\ufffd\ufffd\u06b1\ufffd\ufffd */
	public NativeLong ulSerialPort;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_PTZ_DECODER_TYPE_E
	 */
	public int enDecoderType;
	/** \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u05b7 */
	public NativeLong ulDecoderAddress;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u0123\u02bd<br>
	 * C type : PU_PTZ_CONTROL_MODE_E
	 */
	public int enPtzControlMode;
	/** \ufffd\u01f7\ufffd\u02b9\ufffd\ufffd */
	public boolean bEnable;
	public PU_PTZ_PARA() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulPtzId", "ulSerialPort", "enDecoderType", "ulDecoderAddress", "enPtzControlMode", "bEnable");
	}
	/**
	 * @param ulPtzId \ufffd\ufffd\u0328\ufffd\ufffd\ufffd<br>
	 * @param ulSerialPort \ufffd\ufffd\ufffd\u06b1\ufffd\ufffd<br>
	 * @param enDecoderType \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_PTZ_DECODER_TYPE_E<br>
	 * @param ulDecoderAddress \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u05b7<br>
	 * @param enPtzControlMode \ufffd\ufffd\ufffd\ufffd\ufffd\u0123\u02bd<br>
	 * C type : PU_PTZ_CONTROL_MODE_E<br>
	 * @param bEnable \ufffd\u01f7\ufffd\u02b9\ufffd\ufffd
	 */
	public PU_PTZ_PARA(NativeLong ulPtzId, NativeLong ulSerialPort, int enDecoderType, NativeLong ulDecoderAddress, int enPtzControlMode, boolean bEnable) {
		super();
		this.ulPtzId = ulPtzId;
		this.ulSerialPort = ulSerialPort;
		this.enDecoderType = enDecoderType;
		this.ulDecoderAddress = ulDecoderAddress;
		this.enPtzControlMode = enPtzControlMode;
		this.bEnable = bEnable;
	}
	public PU_PTZ_PARA(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_PTZ_PARA implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_PTZ_PARA implements Structure.ByValue {
		
	};
}
