package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_PIC_SIZE extends Structure {
	/** \u037c\u01ac\ufffd\ufffd\ufffd */
	public NativeLong ulWidth;
	/** \u037c\u01ac\ufffd\u07f6\ufffd */
	public NativeLong ulHeight;
	public PU_PIC_SIZE() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulWidth", "ulHeight");
	}
	/**
	 * @param ulWidth \u037c\u01ac\ufffd\ufffd\ufffd<br>
	 * @param ulHeight \u037c\u01ac\ufffd\u07f6\ufffd
	 */
	public PU_PIC_SIZE(NativeLong ulWidth, NativeLong ulHeight) {
		super();
		this.ulWidth = ulWidth;
		this.ulHeight = ulHeight;
	}
	public PU_PIC_SIZE(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_PIC_SIZE implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_PIC_SIZE implements Structure.ByValue {
		
	};
}
