package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_PTZ_PRESET_PARA extends Structure {
	/** \u0368\ufffd\ufffdID */
	public NativeLong ulChannelId;
	/**
	 * \u0524\ufffd\ufffd\u03bb\ufffd\ufffd\ufffd<br>
	 * C type : CHAR[32]
	 */
	public byte[] szPresetName = new byte[32];
	/** \u0524\ufffd\ufffd\u03bb\ufffd\ufffd\ufffd\ufffd */
	public NativeLong ulIndex;
	/**
	 * \u0524\ufffd\ufffd\u03bb\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_PTZ_PRESET_CMD_E
	 */
	public int enPresetCmd;
	public PU_PTZ_PRESET_PARA() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulChannelId", "szPresetName", "ulIndex", "enPresetCmd");
	}
	/**
	 * @param ulChannelId \u0368\ufffd\ufffdID<br>
	 * @param szPresetName \u0524\ufffd\ufffd\u03bb\ufffd\ufffd\ufffd<br>
	 * C type : CHAR[32]<br>
	 * @param ulIndex \u0524\ufffd\ufffd\u03bb\ufffd\ufffd\ufffd\ufffd<br>
	 * @param enPresetCmd \u0524\ufffd\ufffd\u03bb\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_PTZ_PRESET_CMD_E
	 */
	public PU_PTZ_PRESET_PARA(NativeLong ulChannelId, byte szPresetName[], NativeLong ulIndex, int enPresetCmd) {
		super();
		this.ulChannelId = ulChannelId;
		if ((szPresetName.length != this.szPresetName.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szPresetName = szPresetName;
		this.ulIndex = ulIndex;
		this.enPresetCmd = enPresetCmd;
	}
	public PU_PTZ_PRESET_PARA(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_PTZ_PRESET_PARA implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_PTZ_PRESET_PARA implements Structure.ByValue {
		
	};
}
