package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_ROI_METER_MODE extends Structure {
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_COMMONMODE_SWITCH_E
	 */
	public int enRoiMeter;
	/** \ufffd\ufffd\ufffd\ufffd1~100 */
	public NativeLong ulRoiMeterLevel;
	public PU_ROI_METER_MODE() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("enRoiMeter", "ulRoiMeterLevel");
	}
	/**
	 * @param enRoiMeter \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_COMMONMODE_SWITCH_E<br>
	 * @param ulRoiMeterLevel \ufffd\ufffd\ufffd\ufffd1~100
	 */
	public PU_ROI_METER_MODE(int enRoiMeter, NativeLong ulRoiMeterLevel) {
		super();
		this.enRoiMeter = enRoiMeter;
		this.ulRoiMeterLevel = ulRoiMeterLevel;
	}
	public PU_ROI_METER_MODE(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_ROI_METER_MODE implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_ROI_METER_MODE implements Structure.ByValue {
		
	};
}
