package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_RADA_PARA_CHUANSU extends Structure {
	/**
	 * @see PU_ITS_RADAR_WORK_TYPE_E<br>
	 * \ufffd\u05f4\ufe64\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_ITS_RADAR_WORK_TYPE_E
	 */
	public int enRadarWorkType;
	/**
	 * @see PU_ITS_RADAR_MSG_SENDTYPE_E<br>
	 * \ufffd\u05f4\ufffd\ufffd\ufffd\u03e2\ufffd\ufffd\ufffd\u0377\ufffd\u02bd<br>
	 * C type : PU_ITS_RADAR_MSG_SENDTYPE_E
	 */
	public int enMsgSendType;
	/**
	 * @see PU_ITS_DETECT_DIR_E<br>
	 * \u033d\ufffd\u2dfd\ufffd\ufffd<br>
	 * C type : PU_ITS_DETECT_DIR_E
	 */
	public int enDetectDir;
	/** \ufffd\ufffd\ufffd\ufffd\u01f6\ufffd, \ufffd\ufffd\ufffd\ufffd\u05f4\ufffd\ufffd\ufffd\u067a\ufffd\u02b5\ufffd\ufffd\ufffd\u0676\u0232\ufffd\u04bb\ufffd\u00a3\ufffd\ufffd\ufffd\u04aa\ufffd\ufffd\ufffd\ufffd\u01f6\ufffd */
	public NativeLong uiFixedAngle;
	/** \ufffd\u05f4\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd */
	public NativeLong uiSensitivity;
	/** \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0421\ufffd\ufffd\ufffd\ufffd */
	public NativeLong uiTrigMinInterval;
	/** \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0421\ufffd\u0676\u0223\ufffd\ufffd\ufffd\ufffd\u0675\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u07bd\ufffd\ufffd\ufffd\ufffd\u1d25\ufffd\ufffd */
	public NativeLong uiTrigMinSpeed;
	/** \ufffd\ufffd\u05f0\ufffd\u07f6\ufffd */
	public NativeLong uiHardwareHeight;
	public PU_RADA_PARA_CHUANSU() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("enRadarWorkType", "enMsgSendType", "enDetectDir", "uiFixedAngle", "uiSensitivity", "uiTrigMinInterval", "uiTrigMinSpeed", "uiHardwareHeight");
	}
	/**
	 * @param enRadarWorkType @see PU_ITS_RADAR_WORK_TYPE_E<br>
	 * \ufffd\u05f4\ufe64\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_ITS_RADAR_WORK_TYPE_E<br>
	 * @param enMsgSendType @see PU_ITS_RADAR_MSG_SENDTYPE_E<br>
	 * \ufffd\u05f4\ufffd\ufffd\ufffd\u03e2\ufffd\ufffd\ufffd\u0377\ufffd\u02bd<br>
	 * C type : PU_ITS_RADAR_MSG_SENDTYPE_E<br>
	 * @param enDetectDir @see PU_ITS_DETECT_DIR_E<br>
	 * \u033d\ufffd\u2dfd\ufffd\ufffd<br>
	 * C type : PU_ITS_DETECT_DIR_E<br>
	 * @param uiFixedAngle \ufffd\ufffd\ufffd\ufffd\u01f6\ufffd, \ufffd\ufffd\ufffd\ufffd\u05f4\ufffd\ufffd\ufffd\u067a\ufffd\u02b5\ufffd\ufffd\ufffd\u0676\u0232\ufffd\u04bb\ufffd\u00a3\ufffd\ufffd\ufffd\u04aa\ufffd\ufffd\ufffd\ufffd\u01f6\ufffd<br>
	 * @param uiSensitivity \ufffd\u05f4\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * @param uiTrigMinInterval \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0421\ufffd\ufffd\ufffd\ufffd<br>
	 * @param uiTrigMinSpeed \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0421\ufffd\u0676\u0223\ufffd\ufffd\ufffd\ufffd\u0675\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u07bd\ufffd\ufffd\ufffd\ufffd\u1d25\ufffd\ufffd<br>
	 * @param uiHardwareHeight \ufffd\ufffd\u05f0\ufffd\u07f6\ufffd
	 */
	public PU_RADA_PARA_CHUANSU(int enRadarWorkType, int enMsgSendType, int enDetectDir, NativeLong uiFixedAngle, NativeLong uiSensitivity, NativeLong uiTrigMinInterval, NativeLong uiTrigMinSpeed, NativeLong uiHardwareHeight) {
		super();
		this.enRadarWorkType = enRadarWorkType;
		this.enMsgSendType = enMsgSendType;
		this.enDetectDir = enDetectDir;
		this.uiFixedAngle = uiFixedAngle;
		this.uiSensitivity = uiSensitivity;
		this.uiTrigMinInterval = uiTrigMinInterval;
		this.uiTrigMinSpeed = uiTrigMinSpeed;
		this.uiHardwareHeight = uiHardwareHeight;
	}
	public PU_RADA_PARA_CHUANSU(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_RADA_PARA_CHUANSU implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_RADA_PARA_CHUANSU implements Structure.ByValue {
		
	};
}
