package com.summit.sdk.huawei;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_RESOLUTION_INFO extends Structure {
	/**
	 * \ufffd\u8c78\ufffd\ufffd\u01b5\ufffd\u05b1\ufffd\ufffd\u02bb\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_RESOLUTION_BASIC_PARA_S[PU_VIEDO_STREAM_TRIPLE]
	 */
	public PU_RESOLUTION_BASIC_PARA[] astResolutionPara = new PU_RESOLUTION_BASIC_PARA[(int)com.summit.sdk.huawei.HWPuSDKLibrary.PU_STREAM_MODE_E.PU_VIEDO_STREAM_TRIPLE];
	/** C type : CHAR[32] */
	public byte[] szReserved = new byte[32];
	public PU_RESOLUTION_INFO() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("astResolutionPara", "szReserved");
	}
	/**
	 * @param astResolutionPara \ufffd\u8c78\ufffd\ufffd\u01b5\ufffd\u05b1\ufffd\ufffd\u02bb\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_RESOLUTION_BASIC_PARA_S[PU_VIEDO_STREAM_TRIPLE]<br>
	 * @param szReserved C type : CHAR[32]
	 */
	public PU_RESOLUTION_INFO(PU_RESOLUTION_BASIC_PARA astResolutionPara[], byte szReserved[]) {
		super();
		if ((astResolutionPara.length != this.astResolutionPara.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.astResolutionPara = astResolutionPara;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public PU_RESOLUTION_INFO(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_RESOLUTION_INFO implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_RESOLUTION_INFO implements Structure.ByValue {
		
	};
}
