package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_SNAPSHOT_SPACE extends Structure {
	/** \u05e5\ufffd\u013f\u057c\ufffd\u057c\ufffd\u0677\u05b1\ufffd(\u0421\ufffd\ufffd\ufffd(2\u03bb\ufffd\ufffd\u0427,\ufffd\ufffd\u0237\ufffd\ufffd\ufffd\u0677\ufffd\u03bb,1\ufffd\ufffd\u02be0.01%)) */
	public NativeLong ulPercentDecimal;
	/** \u05e5\ufffd\u013f\u057c\ufffd\u057c\ufffd\u0677\u05b1\ufffd(\ufffd\ufffd\ufffd\ufffd\ufffd) */
	public NativeLong ulPercentInt;
	public PU_SNAPSHOT_SPACE() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulPercentDecimal", "ulPercentInt");
	}
	/**
	 * @param ulPercentDecimal \u05e5\ufffd\u013f\u057c\ufffd\u057c\ufffd\u0677\u05b1\ufffd(\u0421\ufffd\ufffd\ufffd(2\u03bb\ufffd\ufffd\u0427,\ufffd\ufffd\u0237\ufffd\ufffd\ufffd\u0677\ufffd\u03bb,1\ufffd\ufffd\u02be0.01%))<br>
	 * @param ulPercentInt \u05e5\ufffd\u013f\u057c\ufffd\u057c\ufffd\u0677\u05b1\ufffd(\ufffd\ufffd\ufffd\ufffd\ufffd)
	 */
	public PU_SNAPSHOT_SPACE(NativeLong ulPercentDecimal, NativeLong ulPercentInt) {
		super();
		this.ulPercentDecimal = ulPercentDecimal;
		this.ulPercentInt = ulPercentInt;
	}
	public PU_SNAPSHOT_SPACE(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_SNAPSHOT_SPACE implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_SNAPSHOT_SPACE implements Structure.ByValue {
		
	};
}
