package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_STREAM_PROFILES_PARA extends Structure {
	/** \u03a8\u04bb\ufffd\ufffd\u02b6 1-4\ufffd\u01fb\ufffd\ufffd\ufffd\ufffd\u00f2\ufffd\ufffd\ufffd\u027e\ufffd\ufffd,0\ufffd\ufffd\u02be\ufffd\u0536\ufffd\ufffd\ufffd\ufffd\ufffd */
	public NativeLong ulIndex;
	/**
	 * \ufffd\ufffd\ufffd<br>
	 * C type : CHAR[(64 + 4)]
	 */
	public byte[] szName = new byte[64 + 4];
	/**
	 * \ufffd\ufffd\ufffd\ufffd<br>
	 * C type : CHAR[(64 + 4) * 2]
	 */
	public byte[] szDescrip = new byte[(64 + 4) * 2];
	/**
	 * \ufffd\ufffd\u01b5\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_VIDEO_ENCODE_PARA_S
	 */
	public PU_VIDEO_ENCODE_PARA stVideoEncodePara;
	/**
	 * \ufffd\ufffd\u01b5\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_AUDIO_INFO_S
	 */
	public PU_AUDIO_INFO stAudioInfo;
	/** \ufffd\ufffd\u01b5\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u01ff */
	public boolean bAiVqeStatus;
	/** \ufffd\ufffd\ufffd\ufffd\u0123\u02bd */
	public boolean bCorridorEnable;
	/**
	 * \u0524\ufffd\ufffd<br>
	 * C type : CHAR[32]
	 */
	public byte[] szReserve = new byte[32];
	public PU_STREAM_PROFILES_PARA() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulIndex", "szName", "szDescrip", "stVideoEncodePara", "stAudioInfo", "bAiVqeStatus", "bCorridorEnable", "szReserve");
	}
	/**
	 * @param ulIndex \u03a8\u04bb\ufffd\ufffd\u02b6 1-4\ufffd\u01fb\ufffd\ufffd\ufffd\ufffd\u00f2\ufffd\ufffd\ufffd\u027e\ufffd\ufffd,0\ufffd\ufffd\u02be\ufffd\u0536\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * @param szName \ufffd\ufffd\ufffd<br>
	 * C type : CHAR[(64 + 4)]<br>
	 * @param szDescrip \ufffd\ufffd\ufffd\ufffd<br>
	 * C type : CHAR[(64 + 4) * 2]<br>
	 * @param stVideoEncodePara \ufffd\ufffd\u01b5\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_VIDEO_ENCODE_PARA_S<br>
	 * @param stAudioInfo \ufffd\ufffd\u01b5\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_AUDIO_INFO_S<br>
	 * @param bAiVqeStatus \ufffd\ufffd\u01b5\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u01ff<br>
	 * @param bCorridorEnable \ufffd\ufffd\ufffd\ufffd\u0123\u02bd<br>
	 * @param szReserve \u0524\ufffd\ufffd<br>
	 * C type : CHAR[32]
	 */
	public PU_STREAM_PROFILES_PARA(NativeLong ulIndex, byte szName[], byte szDescrip[], PU_VIDEO_ENCODE_PARA stVideoEncodePara, PU_AUDIO_INFO stAudioInfo, boolean bAiVqeStatus, boolean bCorridorEnable, byte szReserve[]) {
		super();
		this.ulIndex = ulIndex;
		if ((szName.length != this.szName.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szName = szName;
		if ((szDescrip.length != this.szDescrip.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szDescrip = szDescrip;
		this.stVideoEncodePara = stVideoEncodePara;
		this.stAudioInfo = stAudioInfo;
		this.bAiVqeStatus = bAiVqeStatus;
		this.bCorridorEnable = bCorridorEnable;
		if ((szReserve.length != this.szReserve.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserve = szReserve;
	}
	public PU_STREAM_PROFILES_PARA(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_STREAM_PROFILES_PARA implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_STREAM_PROFILES_PARA implements Structure.ByValue {
		
	};
}
