package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_STREAMPROFILES_INFO_LIST extends Structure {
	/** \ufffd\ufffd\ufffd\u05f2\u0378\ufffd\ufffd\ufffd */
	public NativeLong ulStreamProfilesNum;
	/** \ufffd\ufffd\u01f0\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u05f2\ufffd */
	public NativeLong ulStreamId;
	/**
	 * \ufffd\ufffd\u03e2\ufffd\u0431\ufffd<br>
	 * C type : PU_STREAMPROFILES_INFO_S[8]
	 */
	public PU_STREAMPROFILES_INFO[] szStreamProfile = new PU_STREAMPROFILES_INFO[8];
	/**
	 * \u0524\ufffd\ufffd\ufffd\u05b6\ufffd<br>
	 * C type : CHAR[32]
	 */
	public byte[] szReserved = new byte[32];
	public PU_STREAMPROFILES_INFO_LIST() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulStreamProfilesNum", "ulStreamId", "szStreamProfile", "szReserved");
	}
	/**
	 * @param ulStreamProfilesNum \ufffd\ufffd\ufffd\u05f2\u0378\ufffd\ufffd\ufffd<br>
	 * @param ulStreamId \ufffd\ufffd\u01f0\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u05f2\ufffd<br>
	 * @param szStreamProfile \ufffd\ufffd\u03e2\ufffd\u0431\ufffd<br>
	 * C type : PU_STREAMPROFILES_INFO_S[8]<br>
	 * @param szReserved \u0524\ufffd\ufffd\ufffd\u05b6\ufffd<br>
	 * C type : CHAR[32]
	 */
	public PU_STREAMPROFILES_INFO_LIST(NativeLong ulStreamProfilesNum, NativeLong ulStreamId, PU_STREAMPROFILES_INFO szStreamProfile[], byte szReserved[]) {
		super();
		this.ulStreamProfilesNum = ulStreamProfilesNum;
		this.ulStreamId = ulStreamId;
		if ((szStreamProfile.length != this.szStreamProfile.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szStreamProfile = szStreamProfile;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public PU_STREAMPROFILES_INFO_LIST(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_STREAMPROFILES_INFO_LIST implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_STREAMPROFILES_INFO_LIST implements Structure.ByValue {
		
	};
}
