package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_SNAPSHOT_QUAILTY_PARA extends Structure {
	/** \u0368\ufffd\ufffd\ufffd\ufffd(\ufffd\u0772\ufffd\u05a7\ufffd\ufffd) */
	public NativeLong ulChannelID;
	/**
	 * \u05e5\ufffd\ufffd\u037c\u01ac\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_SNAPSHOT_QUALITY_E
	 */
	public int enQuality;
	/**
	 * \u0524\ufffd\ufffd<br>
	 * C type : CHAR[32]
	 */
	public byte[] szReserved = new byte[32];
	public PU_SNAPSHOT_QUAILTY_PARA() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulChannelID", "enQuality", "szReserved");
	}
	/**
	 * @param ulChannelID \u0368\ufffd\ufffd\ufffd\ufffd(\ufffd\u0772\ufffd\u05a7\ufffd\ufffd)<br>
	 * @param enQuality \u05e5\ufffd\ufffd\u037c\u01ac\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_SNAPSHOT_QUALITY_E<br>
	 * @param szReserved \u0524\ufffd\ufffd<br>
	 * C type : CHAR[32]
	 */
	public PU_SNAPSHOT_QUAILTY_PARA(NativeLong ulChannelID, int enQuality, byte szReserved[]) {
		super();
		this.ulChannelID = ulChannelID;
		this.enQuality = enQuality;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public PU_SNAPSHOT_QUAILTY_PARA(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_SNAPSHOT_QUAILTY_PARA implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_SNAPSHOT_QUAILTY_PARA implements Structure.ByValue {
		
	};
}
