package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_SYSTEM_TIME extends Structure {
	/**
	 * UTC\u02b1\ufffd\ufffd<br>
	 * C type : PU_TIME_S
	 */
	public PU_TIME stSystime;
	/** \u02b1\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd */
	public NativeLong lTimeZone;
	/** \u02b1\ufffd\ufffd\ufffd\u0421\ufffd\ufffd\ufffd */
	public NativeLong ulDotTimeZone;
	/** C type : CHAR[32] */
	public byte[] szReserve = new byte[32];
	public PU_SYSTEM_TIME() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("stSystime", "lTimeZone", "ulDotTimeZone", "szReserve");
	}
	/**
	 * @param stSystime UTC\u02b1\ufffd\ufffd<br>
	 * C type : PU_TIME_S<br>
	 * @param lTimeZone \u02b1\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * @param ulDotTimeZone \u02b1\ufffd\ufffd\ufffd\u0421\ufffd\ufffd\ufffd<br>
	 * @param szReserve C type : CHAR[32]
	 */
	public PU_SYSTEM_TIME(PU_TIME stSystime, NativeLong lTimeZone, NativeLong ulDotTimeZone, byte szReserve[]) {
		super();
		this.stSystime = stSystime;
		this.lTimeZone = lTimeZone;
		this.ulDotTimeZone = ulDotTimeZone;
		if ((szReserve.length != this.szReserve.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserve = szReserve;
	}
	public PU_SYSTEM_TIME(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_SYSTEM_TIME implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_SYSTEM_TIME implements Structure.ByValue {
		
	};
}
