package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_SLAVE_DEVICE_INFO extends Structure {
	/** \ufffd\ufffd\ufffd\u8c78ID */
	public NativeLong ulSlaveID;
	/** \ufffd\u01f7\ufffd\ufffd\ufffd\u0427\ufffd\ufffd\u05be\u03bb */
	public boolean bValid;
	/**
	 * \ufffd\ufffd\ufffd\u8c78IP\ufffd\ufffd\u05b7<br>
	 * C type : CHAR[16]
	 */
	public byte[] szIPAddress = new byte[16];
	/**
	 * \ufffd\ufffd\ufffd\u8c78\ufffd\ufffd\ufffd,\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd32\ufffd\u05bd\ufffd\ufffd\u05b7\ufffd<br>
	 * C type : CHAR[(32 + 4)]
	 */
	public byte[] szSlaveName = new byte[32 + 4];
	/** C type : CHAR[32] */
	public byte[] szReserved = new byte[32];
	public PU_SLAVE_DEVICE_INFO() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulSlaveID", "bValid", "szIPAddress", "szSlaveName", "szReserved");
	}
	/**
	 * @param ulSlaveID \ufffd\ufffd\ufffd\u8c78ID<br>
	 * @param bValid \ufffd\u01f7\ufffd\ufffd\ufffd\u0427\ufffd\ufffd\u05be\u03bb<br>
	 * @param szIPAddress \ufffd\ufffd\ufffd\u8c78IP\ufffd\ufffd\u05b7<br>
	 * C type : CHAR[16]<br>
	 * @param szSlaveName \ufffd\ufffd\ufffd\u8c78\ufffd\ufffd\ufffd,\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd32\ufffd\u05bd\ufffd\ufffd\u05b7\ufffd<br>
	 * C type : CHAR[(32 + 4)]<br>
	 * @param szReserved C type : CHAR[32]
	 */
	public PU_SLAVE_DEVICE_INFO(NativeLong ulSlaveID, boolean bValid, byte szIPAddress[], byte szSlaveName[], byte szReserved[]) {
		super();
		this.ulSlaveID = ulSlaveID;
		this.bValid = bValid;
		if ((szIPAddress.length != this.szIPAddress.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szIPAddress = szIPAddress;
		if ((szSlaveName.length != this.szSlaveName.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szSlaveName = szSlaveName;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public PU_SLAVE_DEVICE_INFO(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_SLAVE_DEVICE_INFO implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_SLAVE_DEVICE_INFO implements Structure.ByValue {
		
	};
}
