package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_SUPPLEMENT_LAMP_ATTR extends Structure {
	/** \u0368\ufffd\ufffdID */
	public NativeLong ulChannelId;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u01b5\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_STROBE_LAMP_ATTR_S[(3)]
	 */
	public PU_STROBE_LAMP_ATTR[] stStrobeLampAttr = new PU_STROBE_LAMP_ATTR[3];
	/**
	 * \ufffd\ufffd\ufffd\u00f5\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_EXT_LAMP_ATTR_S[(8)]
	 */
	public PU_EXT_LAMP_ATTR[] stExtLampAttr = new PU_EXT_LAMP_ATTR[8];
	/** C type : CHAR[32] */
	public byte[] szReserved = new byte[32];
	public PU_SUPPLEMENT_LAMP_ATTR() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulChannelId", "stStrobeLampAttr", "stExtLampAttr", "szReserved");
	}
	/**
	 * @param ulChannelId \u0368\ufffd\ufffdID<br>
	 * @param stStrobeLampAttr \ufffd\ufffd\ufffd\ufffd\u01b5\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_STROBE_LAMP_ATTR_S[(3)]<br>
	 * @param stExtLampAttr \ufffd\ufffd\ufffd\u00f5\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_EXT_LAMP_ATTR_S[(8)]<br>
	 * @param szReserved C type : CHAR[32]
	 */
	public PU_SUPPLEMENT_LAMP_ATTR(NativeLong ulChannelId, PU_STROBE_LAMP_ATTR stStrobeLampAttr[], PU_EXT_LAMP_ATTR stExtLampAttr[], byte szReserved[]) {
		super();
		this.ulChannelId = ulChannelId;
		if ((stStrobeLampAttr.length != this.stStrobeLampAttr.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.stStrobeLampAttr = stStrobeLampAttr;
		if ((stExtLampAttr.length != this.stExtLampAttr.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.stExtLampAttr = stExtLampAttr;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public PU_SUPPLEMENT_LAMP_ATTR(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_SUPPLEMENT_LAMP_ATTR implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_SUPPLEMENT_LAMP_ATTR implements Structure.ByValue {
		
	};
}
