package com.summit.sdk.huawei;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_SNMPV3_USER_INFO extends Structure {
	/**
	 * \ufffd\u00fb\ufffd\ufffd\ufffd<br>
	 * C type : CHAR[32]
	 */
	public byte[] szUserName = new byte[32];
	/** \ufffd\u01f7\ufffd\ufffd\ufffd\u04aa\u05b8\ufffd\ufffdENGINEID(\ufffd\ufffd\u02b1\u05bb\ufffd\ufffd\ufffd\ufffd\ufffd\ufffdTrap\u02b1\u02b9\ufffd\ufffd) */
	public boolean bEngineIdEnable;
	/**
	 * ENGINEID(\ufffd\ufffd\u02b1\u05bb\ufffd\ufffd\ufffd\ufffd\ufffd\ufffdTrap\u02b1\u02b9\ufffd\ufffd)<br>
	 * C type : CHAR[(32 + 1)]
	 */
	public byte[] szEngineId = new byte[32 + 1];
	/** \ufffd\u01f7\ufffd\ufffd\ufffd\u04aa\u05b8\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd(\ufffd\ufffd\u02b1\u05bb\ufffd\ufffd\ufffd\ufffd\ufffd\ufffdTrap\u02b1\u02b9\ufffd\ufffd) */
	public boolean bContextEnable;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd(\ufffd\ufffd\u02b1\u05bb\ufffd\ufffd\ufffd\ufffd\ufffd\ufffdTrap\u02b1\u02b9\ufffd\ufffd)<br>
	 * C type : CHAR[(16 + 1)]
	 */
	public byte[] szContextName = new byte[16 + 1];
	/**
	 * \ufffd\ufffd\u05a4Pwd(\ufffd\ufffd\ufffd\ufffdWEB\ufffd\ufffd\ufffd\u00f5\ufffd\u02b1\ufffd\ufffd\u03aa\u052d\ufffd\ufffd\ufffd\u00b7\ufffd;\ufffd\ufffd\u00bc\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u013c\ufffd\ufffd\ufffd\u03aa\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u02bd)<br>
	 * C type : CHAR[(64 + 4)]
	 */
	public byte[] szAuthPassword = new byte[64 + 4];
	/**
	 * \ufffd\ufffd\u053f(\ufffd\ufffd\ufffd\ufffdWEB\ufffd\ufffd\ufffd\u00f5\ufffd\u02b1\ufffd\ufffd\u03aa\u052d\ufffd\ufffd\ufffd\u00b7\ufffd;\ufffd\ufffd\u00bc\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u013c\ufffd\ufffd\ufffd\u03aa\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u02bd)<br>
	 * C type : CHAR[(64 + 4)]
	 */
	public byte[] szPrivKey = new byte[64 + 4];
	/**
	 * \ufffd\ufffd\u022b\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_SNMPV3_SECURITY_LEVEL_E
	 */
	public int enSecurityLevel;
	/**
	 * \ufffd\ufffd\u05a4\u042d\ufffd\ufffd<br>
	 * C type : PU_SNMPV3_AUTH_PROTOCOL_E
	 */
	public int enAuthProtocol;
	/**
	 * \ufffd\ufffd\u053f\u042d\ufffd\ufffd<br>
	 * C type : PU_SNMPV3_PRIV_PROTOCOL_E
	 */
	public int enPrivProtocol;
	/** C type : CHAR[32] */
	public byte[] szReserved = new byte[32];
	public PU_SNMPV3_USER_INFO() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("szUserName", "bEngineIdEnable", "szEngineId", "bContextEnable", "szContextName", "szAuthPassword", "szPrivKey", "enSecurityLevel", "enAuthProtocol", "enPrivProtocol", "szReserved");
	}
	public PU_SNMPV3_USER_INFO(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_SNMPV3_USER_INFO implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_SNMPV3_USER_INFO implements Structure.ByValue {
		
	};
}
