package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_SLAVE_RTSP_STATUS extends Structure {
	/** \ufffd\ufffd\ufffd\u8c78id\ufffd\ufffd\u03a8\u04bb\ufffd\ufffd\u02b6 */
	public NativeLong ulSlaveID;
	/**
	 * \u05f4\u032c\u05b5<br>
	 * C type : PU_SLAVE_RTSP_STATUS_TYPE_E
	 */
	public int enStatus;
	public PU_SLAVE_RTSP_STATUS() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulSlaveID", "enStatus");
	}
	/**
	 * @param ulSlaveID \ufffd\ufffd\ufffd\u8c78id\ufffd\ufffd\u03a8\u04bb\ufffd\ufffd\u02b6<br>
	 * @param enStatus \u05f4\u032c\u05b5<br>
	 * C type : PU_SLAVE_RTSP_STATUS_TYPE_E
	 */
	public PU_SLAVE_RTSP_STATUS(NativeLong ulSlaveID, int enStatus) {
		super();
		this.ulSlaveID = ulSlaveID;
		this.enStatus = enStatus;
	}
	public PU_SLAVE_RTSP_STATUS(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_SLAVE_RTSP_STATUS implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_SLAVE_RTSP_STATUS implements Structure.ByValue {
		
	};
}
