package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_SERIAL_PORT_PARA extends Structure {
	/** \ufffd\ufffd\ufffd\u06b1\ufffd\ufffd */
	public NativeLong ulSerialPort;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_SERIAL_PORT_MODE_E
	 */
	public int enPortMode;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_BAUD_RATE_E
	 */
	public int enBaudRate;
	/**
	 * \ufffd\ufffd\ufffd\u03bb<br>
	 * C type : PU_DATA_BIT_E
	 */
	public int enDataBit;
	/**
	 * \u0423\ufffd\ufffd\u03bb<br>
	 * C type : PU_PARITY_BIT_E
	 */
	public int enParityBit;
	/**
	 * \u0363\u05b9\u03bb<br>
	 * C type : PU_STOP_BIT_E
	 */
	public int enStopBit;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_FLOW_CONTROL_E
	 */
	public int enFlowControl;
	public PU_SERIAL_PORT_PARA() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulSerialPort", "enPortMode", "enBaudRate", "enDataBit", "enParityBit", "enStopBit", "enFlowControl");
	}
	/**
	 * @param ulSerialPort \ufffd\ufffd\ufffd\u06b1\ufffd\ufffd<br>
	 * @param enPortMode \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_SERIAL_PORT_MODE_E<br>
	 * @param enBaudRate \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_BAUD_RATE_E<br>
	 * @param enDataBit \ufffd\ufffd\ufffd\u03bb<br>
	 * C type : PU_DATA_BIT_E<br>
	 * @param enParityBit \u0423\ufffd\ufffd\u03bb<br>
	 * C type : PU_PARITY_BIT_E<br>
	 * @param enStopBit \u0363\u05b9\u03bb<br>
	 * C type : PU_STOP_BIT_E<br>
	 * @param enFlowControl \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_FLOW_CONTROL_E
	 */
	public PU_SERIAL_PORT_PARA(NativeLong ulSerialPort, int enPortMode, int enBaudRate, int enDataBit, int enParityBit, int enStopBit, int enFlowControl) {
		super();
		this.ulSerialPort = ulSerialPort;
		this.enPortMode = enPortMode;
		this.enBaudRate = enBaudRate;
		this.enDataBit = enDataBit;
		this.enParityBit = enParityBit;
		this.enStopBit = enStopBit;
		this.enFlowControl = enFlowControl;
	}
	public PU_SERIAL_PORT_PARA(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_SERIAL_PORT_PARA implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_SERIAL_PORT_PARA implements Structure.ByValue {
		
	};
}
