package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_STREAM_SMOOTH_PARA_EX extends Structure {
	public NativeLong ulChannelId;
	public boolean bEnable;
	/** \ufffd\ufffd\ufffd\ufffd\u01bd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd,\ufffd\ufffd\u03a71-8,\ufffd\ufffd\u04e6\ufffd\u8c78\ufffd\ufffd\ufffd\ufffd1.5-5.0,\ufffd\ufffd\ufffd\ufffd0.5 */
	public NativeLong ulUpperCoefficient;
	/** C type : CHAR[32] */
	public byte[] szReserved = new byte[32];
	public PU_STREAM_SMOOTH_PARA_EX() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulChannelId", "bEnable", "ulUpperCoefficient", "szReserved");
	}
	/**
	 * @param ulUpperCoefficient \ufffd\ufffd\ufffd\ufffd\u01bd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd,\ufffd\ufffd\u03a71-8,\ufffd\ufffd\u04e6\ufffd\u8c78\ufffd\ufffd\ufffd\ufffd1.5-5.0,\ufffd\ufffd\ufffd\ufffd0.5<br>
	 * @param szReserved C type : CHAR[32]
	 */
	public PU_STREAM_SMOOTH_PARA_EX(NativeLong ulChannelId, boolean bEnable, NativeLong ulUpperCoefficient, byte szReserved[]) {
		super();
		this.ulChannelId = ulChannelId;
		this.bEnable = bEnable;
		this.ulUpperCoefficient = ulUpperCoefficient;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public PU_STREAM_SMOOTH_PARA_EX(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_STREAM_SMOOTH_PARA_EX implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_STREAM_SMOOTH_PARA_EX implements Structure.ByValue {
		
	};
}
