package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_TD_TOUR_PLAN_ONE_DAY_PARAMS extends Structure {
	/** \u0472\ufffd\ufffd\ufffd\ufffd\u02bc\u02b1\ufffd\ufffd(\ufffd\ufffd\ufffd\ufffd) */
	public NativeLong ulBeginTime;
	/** \u0472\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u02b1\ufffd\ufffd (\ufffd\ufffd\ufffd\ufffd) */
	public NativeLong ulEndTime;
	/** \u00ff\ufffd\ufffd\u0472\ufffd\ufffd\ufffd\u01bb\ufffd\ufffd\ufffd\ufffd\u0472\ufffd\ufffd\ufffd\ucf23\ufffd\ufffd\ufffd\ufffd\ufffd */
	public NativeLong ulSceneNum;
	/**
	 * \u00ff\ufffd\ufffd\u0472\ufffd\ufffd\ufffd\u01bb\ufffd<br>
	 * C type : PU_TD_TOUR_TRACK_POINT_PARAMS_S[(16)]
	 */
	public PU_TD_TOUR_TRACK_POINT_PARAMS[] stTourTrackPoint = new PU_TD_TOUR_TRACK_POINT_PARAMS[16];
	public PU_TD_TOUR_PLAN_ONE_DAY_PARAMS() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulBeginTime", "ulEndTime", "ulSceneNum", "stTourTrackPoint");
	}
	/**
	 * @param ulBeginTime \u0472\ufffd\ufffd\ufffd\ufffd\u02bc\u02b1\ufffd\ufffd(\ufffd\ufffd\ufffd\ufffd)<br>
	 * @param ulEndTime \u0472\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u02b1\ufffd\ufffd (\ufffd\ufffd\ufffd\ufffd)<br>
	 * @param ulSceneNum \u00ff\ufffd\ufffd\u0472\ufffd\ufffd\ufffd\u01bb\ufffd\ufffd\ufffd\ufffd\u0472\ufffd\ufffd\ufffd\ucf23\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * @param stTourTrackPoint \u00ff\ufffd\ufffd\u0472\ufffd\ufffd\ufffd\u01bb\ufffd<br>
	 * C type : PU_TD_TOUR_TRACK_POINT_PARAMS_S[(16)]
	 */
	public PU_TD_TOUR_PLAN_ONE_DAY_PARAMS(NativeLong ulBeginTime, NativeLong ulEndTime, NativeLong ulSceneNum, PU_TD_TOUR_TRACK_POINT_PARAMS stTourTrackPoint[]) {
		super();
		this.ulBeginTime = ulBeginTime;
		this.ulEndTime = ulEndTime;
		this.ulSceneNum = ulSceneNum;
		if ((stTourTrackPoint.length != this.stTourTrackPoint.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.stTourTrackPoint = stTourTrackPoint;
	}
	public PU_TD_TOUR_PLAN_ONE_DAY_PARAMS(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_TD_TOUR_PLAN_ONE_DAY_PARAMS implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_TD_TOUR_PLAN_ONE_DAY_PARAMS implements Structure.ByValue {
		
	};
}
