package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_TEMPERATURE_ALARM_PARA extends Structure {
	/** \u02b9\ufffd\ufffd */
	public NativeLong lEnable;
	/** \ufffd\u6faf\ufffd\ufffd\ufffd\u02b1\ufffd\ufffd\ufffd\ufffd1~256,\u00ffx\ufffd\ufffd\ufffd\ufffd\u04bb\ufffd\ufffd\ufffd\u01f7\ufffd\ufffd\u06b8\u6faf\u05f4\u032c */
	public NativeLong ulDeteInterval;
	public NativeLong lTemperatureMax;
	public NativeLong lTemperatureMin;
	public PU_TEMPERATURE_ALARM_PARA() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("lEnable", "ulDeteInterval", "lTemperatureMax", "lTemperatureMin");
	}
	/**
	 * @param lEnable \u02b9\ufffd\ufffd<br>
	 * @param ulDeteInterval \ufffd\u6faf\ufffd\ufffd\ufffd\u02b1\ufffd\ufffd\ufffd\ufffd1~256,\u00ffx\ufffd\ufffd\ufffd\ufffd\u04bb\ufffd\ufffd\ufffd\u01f7\ufffd\ufffd\u06b8\u6faf\u05f4\u032c
	 */
	public PU_TEMPERATURE_ALARM_PARA(NativeLong lEnable, NativeLong ulDeteInterval, NativeLong lTemperatureMax, NativeLong lTemperatureMin) {
		super();
		this.lEnable = lEnable;
		this.ulDeteInterval = ulDeteInterval;
		this.lTemperatureMax = lTemperatureMax;
		this.lTemperatureMin = lTemperatureMin;
	}
	public PU_TEMPERATURE_ALARM_PARA(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_TEMPERATURE_ALARM_PARA implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_TEMPERATURE_ALARM_PARA implements Structure.ByValue {
		
	};
}
