package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_TYPICAL_SCENE_LIST_EX_OUT extends Structure {
	/** \ufffd\ufffd\ufffd\ufffd\ufffd\u0138\ufffd\u0368\ufffd\ufffd */
	public NativeLong ulChannelId;
	/** \ufffd\ufffd\ufffd\u0373\ufffd\ufffd\ufffd\ufffd\u05f2\u0378\ufffd\ufffd\ufffd */
	public NativeLong ulTypicalScenesNum;
	/**
	 * \ufffd\ufffd\u01f0\ufffd\ufffd\ufffd\ufffd\u0135\ufffd\ufffd\u0373\ufffd\ufffd\ufffd\ufffd\u05f2\ufffd<br>
	 * C type : PU_TYPICAL_SCENE_MODE_E
	 */
	public int enSceneMode;
	/**
	 * \ufffd\ufffd\u03e2\ufffd\u0431\ufffd<br>
	 * C type : PU_TYPICAL_SCENE_INFO_S*
	 */
	public com.summit.sdk.huawei.PU_TYPICAL_SCENE_INFO.ByReference pstTypicalSceneInfo;
	/**
	 * \u0524\ufffd\ufffd\ufffd\u05b6\ufffd,[0]\ufffd\ufffd\u02be\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0363\ufffd\ufffd\ufffdPU_SCENE_PARAM_TYPE_E<br>
	 * C type : CHAR[32]
	 */
	public byte[] szReserved = new byte[32];
	public PU_TYPICAL_SCENE_LIST_EX_OUT() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulChannelId", "ulTypicalScenesNum", "enSceneMode", "pstTypicalSceneInfo", "szReserved");
	}
	/**
	 * @param ulChannelId \ufffd\ufffd\ufffd\ufffd\ufffd\u0138\ufffd\u0368\ufffd\ufffd<br>
	 * @param ulTypicalScenesNum \ufffd\ufffd\ufffd\u0373\ufffd\ufffd\ufffd\ufffd\u05f2\u0378\ufffd\ufffd\ufffd<br>
	 * @param enSceneMode \ufffd\ufffd\u01f0\ufffd\ufffd\ufffd\ufffd\u0135\ufffd\ufffd\u0373\ufffd\ufffd\ufffd\ufffd\u05f2\ufffd<br>
	 * C type : PU_TYPICAL_SCENE_MODE_E<br>
	 * @param pstTypicalSceneInfo \ufffd\ufffd\u03e2\ufffd\u0431\ufffd<br>
	 * C type : PU_TYPICAL_SCENE_INFO_S*<br>
	 * @param szReserved \u0524\ufffd\ufffd\ufffd\u05b6\ufffd,[0]\ufffd\ufffd\u02be\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0363\ufffd\ufffd\ufffdPU_SCENE_PARAM_TYPE_E<br>
	 * C type : CHAR[32]
	 */
	public PU_TYPICAL_SCENE_LIST_EX_OUT(NativeLong ulChannelId, NativeLong ulTypicalScenesNum, int enSceneMode, com.summit.sdk.huawei.PU_TYPICAL_SCENE_INFO.ByReference pstTypicalSceneInfo, byte szReserved[]) {
		super();
		this.ulChannelId = ulChannelId;
		this.ulTypicalScenesNum = ulTypicalScenesNum;
		this.enSceneMode = enSceneMode;
		this.pstTypicalSceneInfo = pstTypicalSceneInfo;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public PU_TYPICAL_SCENE_LIST_EX_OUT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_TYPICAL_SCENE_LIST_EX_OUT implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_TYPICAL_SCENE_LIST_EX_OUT implements Structure.ByValue {
		
	};
}
