package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_TD_SCENE_ENABLE_INFO extends Structure {
	/** \u0368\ufffd\ufffdID */
	public NativeLong ulChannelId;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u02b9\ufffd\ufffd<br>
	 * C type : BOOL[(16)]
	 */
	public boolean[] abSceneEnable = new boolean[16];
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : CHAR[(16)][(64 + 1)]
	 */
	public byte[] szSceneName = new byte[((16) * (64 + 1))];
	public PU_TD_SCENE_ENABLE_INFO() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulChannelId", "abSceneEnable", "szSceneName");
	}
	/**
	 * @param ulChannelId \u0368\ufffd\ufffdID<br>
	 * @param abSceneEnable \ufffd\ufffd\ufffd\ufffd\u02b9\ufffd\ufffd<br>
	 * C type : BOOL[(16)]<br>
	 * @param szSceneName \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : CHAR[(16)][(64 + 1)]
	 */
	public PU_TD_SCENE_ENABLE_INFO(NativeLong ulChannelId, boolean abSceneEnable[], byte szSceneName[]) {
		super();
		this.ulChannelId = ulChannelId;
		if ((abSceneEnable.length != this.abSceneEnable.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.abSceneEnable = abSceneEnable;
		if ((szSceneName.length != this.szSceneName.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szSceneName = szSceneName;
	}
	public PU_TD_SCENE_ENABLE_INFO(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_TD_SCENE_ENABLE_INFO implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_TD_SCENE_ENABLE_INFO implements Structure.ByValue {
		
	};
}
