package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_TD_MANUAL_DETECTION_PARAMSV2 extends Structure {
	/** \u0368\ufffd\ufffdID */
	public NativeLong ulChannelId;
	/** \ufffd\u04ff\u06b0\u6c7e\ufffd\u0163\ufffd\ufffd\u00fb\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0434 */
	public int iVersion;
	/** C type : PU_TD_TRAFFIC_DOME_ILLEGAL_PARKINK_PARAMS_S */
	public PU_TD_TRAFFIC_DOME_ILLEGAL_PARKINK_PARAMS stIllegalParking;
	public PU_TD_MANUAL_DETECTION_PARAMSV2() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulChannelId", "iVersion", "stIllegalParking");
	}
	/**
	 * @param ulChannelId \u0368\ufffd\ufffdID<br>
	 * @param iVersion \ufffd\u04ff\u06b0\u6c7e\ufffd\u0163\ufffd\ufffd\u00fb\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u0434<br>
	 * @param stIllegalParking C type : PU_TD_TRAFFIC_DOME_ILLEGAL_PARKINK_PARAMS_S
	 */
	public PU_TD_MANUAL_DETECTION_PARAMSV2(NativeLong ulChannelId, int iVersion, PU_TD_TRAFFIC_DOME_ILLEGAL_PARKINK_PARAMS stIllegalParking) {
		super();
		this.ulChannelId = ulChannelId;
		this.iVersion = iVersion;
		this.stIllegalParking = stIllegalParking;
	}
	public PU_TD_MANUAL_DETECTION_PARAMSV2(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_TD_MANUAL_DETECTION_PARAMSV2 implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_TD_MANUAL_DETECTION_PARAMSV2 implements Structure.ByValue {
		
	};
}
