package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_TIME_PLAN extends Structure {
	/** \ufffd\ufffd\ufffd\u06bf\ufffd\ufffd\u01a3\ufffd0\ufffd\ufffd\ufffd\ufffd\u04bb\ufffd\u03a3\ufffd1\ufffd\ufffd\u00ff\ufffd\u0736\ufffd\ufffd\ufffd\ufffd\ufffd\u02b1\ufffd\ufffd\ufffd */
	public NativeLong ulCycle;
	/** \ufffd\ufffd\ufffd\u06a3\ufffd 0:\u04bb\ufffd\ufffd\u022b\ufffd\ufffd 1~7:\ufffd\ufffd\u02be\ufffd\ufffd\ufffd\ufffd */
	public NativeLong ulPeriod;
	/**
	 * \ufffd\ufffd\u02bc\u02b1\ufffd\ufffd:  UTC \u02b1\ufffd\ufffd<br>
	 * C type : PU_TIME_S
	 */
	public PU_TIME stStartTime;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u02b1\ufffd\ufffd:  UTC \u02b1\ufffd\ufffd<br>
	 * C type : PU_TIME_S
	 */
	public PU_TIME stEndTime;
	/** C type : CHAR[32] */
	public byte[] szReserved = new byte[32];
	public PU_TIME_PLAN() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulCycle", "ulPeriod", "stStartTime", "stEndTime", "szReserved");
	}
	/**
	 * @param ulCycle \ufffd\ufffd\ufffd\u06bf\ufffd\ufffd\u01a3\ufffd0\ufffd\ufffd\ufffd\ufffd\u04bb\ufffd\u03a3\ufffd1\ufffd\ufffd\u00ff\ufffd\u0736\ufffd\ufffd\ufffd\ufffd\ufffd\u02b1\ufffd\ufffd\ufffd<br>
	 * @param ulPeriod \ufffd\ufffd\ufffd\u06a3\ufffd 0:\u04bb\ufffd\ufffd\u022b\ufffd\ufffd 1~7:\ufffd\ufffd\u02be\ufffd\ufffd\ufffd\ufffd<br>
	 * @param stStartTime \ufffd\ufffd\u02bc\u02b1\ufffd\ufffd:  UTC \u02b1\ufffd\ufffd<br>
	 * C type : PU_TIME_S<br>
	 * @param stEndTime \ufffd\ufffd\ufffd\ufffd\u02b1\ufffd\ufffd:  UTC \u02b1\ufffd\ufffd<br>
	 * C type : PU_TIME_S<br>
	 * @param szReserved C type : CHAR[32]
	 */
	public PU_TIME_PLAN(NativeLong ulCycle, NativeLong ulPeriod, PU_TIME stStartTime, PU_TIME stEndTime, byte szReserved[]) {
		super();
		this.ulCycle = ulCycle;
		this.ulPeriod = ulPeriod;
		this.stStartTime = stStartTime;
		this.stEndTime = stEndTime;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public PU_TIME_PLAN(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_TIME_PLAN implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_TIME_PLAN implements Structure.ByValue {
		
	};
}
