package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_TD_TRAFFIC_DOME_MANUAL_TRACK_EVIDENCE_SWITCH extends Structure {
	/** \u0368\ufffd\ufffdID */
	public NativeLong ulChannelId;
	/** \ufffd\udabe\udebb\ufffd\u0631\ufffd */
	public boolean bEnable;
	public PU_TD_TRAFFIC_DOME_MANUAL_TRACK_EVIDENCE_SWITCH() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulChannelId", "bEnable");
	}
	/**
	 * @param ulChannelId \u0368\ufffd\ufffdID<br>
	 * @param bEnable \ufffd\udabe\udebb\ufffd\u0631\ufffd
	 */
	public PU_TD_TRAFFIC_DOME_MANUAL_TRACK_EVIDENCE_SWITCH(NativeLong ulChannelId, boolean bEnable) {
		super();
		this.ulChannelId = ulChannelId;
		this.bEnable = bEnable;
	}
	public PU_TD_TRAFFIC_DOME_MANUAL_TRACK_EVIDENCE_SWITCH(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_TD_TRAFFIC_DOME_MANUAL_TRACK_EVIDENCE_SWITCH implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_TD_TRAFFIC_DOME_MANUAL_TRACK_EVIDENCE_SWITCH implements Structure.ByValue {
		
	};
}
