package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_TRANSPARENT_CMD extends Structure {
	/** \ufffd\ufffd\ufffd\u06b1\ufffd\ufffd */
	public NativeLong ulSerialPort;
	/** \u0378\ufffd\ufffd\u0368\ufffd\ufffd\ufffd\ufffd\ufffd\uece4\ufffd\ufffd */
	public NativeLong ulCmdLen;
	/**
	 * \u0378\ufffd\ufffd\u0368\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : CHAR[256]
	 */
	public byte[] szTransparentCmd = new byte[256];
	/** C type : CHAR[32] */
	public byte[] szReserve = new byte[32];
	public PU_TRANSPARENT_CMD() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulSerialPort", "ulCmdLen", "szTransparentCmd", "szReserve");
	}
	/**
	 * @param ulSerialPort \ufffd\ufffd\ufffd\u06b1\ufffd\ufffd<br>
	 * @param ulCmdLen \u0378\ufffd\ufffd\u0368\ufffd\ufffd\ufffd\ufffd\ufffd\uece4\ufffd\ufffd<br>
	 * @param szTransparentCmd \u0378\ufffd\ufffd\u0368\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : CHAR[256]<br>
	 * @param szReserve C type : CHAR[32]
	 */
	public PU_TRANSPARENT_CMD(NativeLong ulSerialPort, NativeLong ulCmdLen, byte szTransparentCmd[], byte szReserve[]) {
		super();
		this.ulSerialPort = ulSerialPort;
		this.ulCmdLen = ulCmdLen;
		if ((szTransparentCmd.length != this.szTransparentCmd.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szTransparentCmd = szTransparentCmd;
		if ((szReserve.length != this.szReserve.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserve = szReserve;
	}
	public PU_TRANSPARENT_CMD(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_TRANSPARENT_CMD implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_TRANSPARENT_CMD implements Structure.ByValue {
		
	};
}
