package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_TD_LINE_PARAMV2 extends Structure {
	/** \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd */
	public NativeLong ulLaneNum;
	/**
	 * \ufffd\u07f2\ufffd\ufffd\ufffd\u02b9\ufffd\u0731\ufffd<br>
	 * C type : PU_TD_DTLINE_ENABLEV2_S
	 */
	public PU_TD_DTLINE_ENABLEV2 stEnableList;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd = \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd+1<br>
	 * C type : ROAD_PROPERTY_UNIT_S[(6)]
	 */
	public tagRoadPropertyUnit[] stLane = new tagRoadPropertyUnit[6];
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u04b1\u07fd\ufffd\ufffd\ufffd<br>
	 * C type : ROAD_PROPERTY_UNIT_S
	 */
	public tagRoadPropertyUnit stLaneRhtBorderLine;
	public PU_TD_LINE_PARAMV2() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulLaneNum", "stEnableList", "stLane", "stLaneRhtBorderLine");
	}
	/**
	 * @param ulLaneNum \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * @param stEnableList \ufffd\u07f2\ufffd\ufffd\ufffd\u02b9\ufffd\u0731\ufffd<br>
	 * C type : PU_TD_DTLINE_ENABLEV2_S<br>
	 * @param stLane \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd = \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd+1<br>
	 * C type : ROAD_PROPERTY_UNIT_S[(6)]<br>
	 * @param stLaneRhtBorderLine \ufffd\ufffd\ufffd\ufffd\ufffd\u04b1\u07fd\ufffd\ufffd\ufffd<br>
	 * C type : ROAD_PROPERTY_UNIT_S
	 */
	public PU_TD_LINE_PARAMV2(NativeLong ulLaneNum, PU_TD_DTLINE_ENABLEV2 stEnableList, tagRoadPropertyUnit stLane[], tagRoadPropertyUnit stLaneRhtBorderLine) {
		super();
		this.ulLaneNum = ulLaneNum;
		this.stEnableList = stEnableList;
		if ((stLane.length != this.stLane.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.stLane = stLane;
		this.stLaneRhtBorderLine = stLaneRhtBorderLine;
	}
	public PU_TD_LINE_PARAMV2(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_TD_LINE_PARAMV2 implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_TD_LINE_PARAMV2 implements Structure.ByValue {
		
	};
}
