package com.summit.sdk.huawei;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_TD_TRAFFIC_DOME_OVERLAY_INTELLIGENT_INFO extends Structure {
	/** \ufffd\ufffd\ufffd\ufffd\u05e5\u037c\ufffd\ufffd\ufffd\ufffd\u013f\ufffd\ufffd\ufffd\ufffd\u03e2 */
	public boolean bNearSnapAddTargetInfoFlag;
	/** \ufffd\ufffd\ufffd\ufffd\u05e5\u037c\ufffd\ufffd\ufffd\u04f9\ufffd\ufffd\ufffd\ufffd\ufffd\u03e2 */
	public boolean bNearSnapAddRuleInfoFlag;
	/** \u0536\ufffd\ufffd\u037c\ufffd\ufffd\ufffd\ufffd\u013f\ufffd\ufffd\ufffd\ufffd\u03e2 */
	public boolean bFarSnapAddTargetInfoFlag;
	/** \u0536\ufffd\ufffd\u037c\ufffd\ufffd\ufffd\u04f9\ufffd\ufffd\ufffd\ufffd\ufffd\u03e2 */
	public boolean bFarSnapAddRuleInfoFlag;
	public PU_TD_TRAFFIC_DOME_OVERLAY_INTELLIGENT_INFO() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("bNearSnapAddTargetInfoFlag", "bNearSnapAddRuleInfoFlag", "bFarSnapAddTargetInfoFlag", "bFarSnapAddRuleInfoFlag");
	}
	/**
	 * @param bNearSnapAddTargetInfoFlag \ufffd\ufffd\ufffd\ufffd\u05e5\u037c\ufffd\ufffd\ufffd\ufffd\u013f\ufffd\ufffd\ufffd\ufffd\u03e2<br>
	 * @param bNearSnapAddRuleInfoFlag \ufffd\ufffd\ufffd\ufffd\u05e5\u037c\ufffd\ufffd\ufffd\u04f9\ufffd\ufffd\ufffd\ufffd\ufffd\u03e2<br>
	 * @param bFarSnapAddTargetInfoFlag \u0536\ufffd\ufffd\u037c\ufffd\ufffd\ufffd\ufffd\u013f\ufffd\ufffd\ufffd\ufffd\u03e2<br>
	 * @param bFarSnapAddRuleInfoFlag \u0536\ufffd\ufffd\u037c\ufffd\ufffd\ufffd\u04f9\ufffd\ufffd\ufffd\ufffd\ufffd\u03e2
	 */
	public PU_TD_TRAFFIC_DOME_OVERLAY_INTELLIGENT_INFO(boolean bNearSnapAddTargetInfoFlag, boolean bNearSnapAddRuleInfoFlag, boolean bFarSnapAddTargetInfoFlag, boolean bFarSnapAddRuleInfoFlag) {
		super();
		this.bNearSnapAddTargetInfoFlag = bNearSnapAddTargetInfoFlag;
		this.bNearSnapAddRuleInfoFlag = bNearSnapAddRuleInfoFlag;
		this.bFarSnapAddTargetInfoFlag = bFarSnapAddTargetInfoFlag;
		this.bFarSnapAddRuleInfoFlag = bFarSnapAddRuleInfoFlag;
	}
	public PU_TD_TRAFFIC_DOME_OVERLAY_INTELLIGENT_INFO(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_TD_TRAFFIC_DOME_OVERLAY_INTELLIGENT_INFO implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_TD_TRAFFIC_DOME_OVERLAY_INTELLIGENT_INFO implements Structure.ByValue {
		
	};
}
