package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_TEMPERATURE_PARA extends Structure {
	/** \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u00b6\ufffd\u05b5 */
	public NativeLong lIntTemp;
	/** \u0421\ufffd\ufffd\ufffd\ufffd\u00b6\ufffd\u05b5 */
	public NativeLong ulDotTemp;
	public PU_TEMPERATURE_PARA() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("lIntTemp", "ulDotTemp");
	}
	/**
	 * @param lIntTemp \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u00b6\ufffd\u05b5<br>
	 * @param ulDotTemp \u0421\ufffd\ufffd\ufffd\ufffd\u00b6\ufffd\u05b5
	 */
	public PU_TEMPERATURE_PARA(NativeLong lIntTemp, NativeLong ulDotTemp) {
		super();
		this.lIntTemp = lIntTemp;
		this.ulDotTemp = ulDotTemp;
	}
	public PU_TEMPERATURE_PARA(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_TEMPERATURE_PARA implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_TEMPERATURE_PARA implements Structure.ByValue {
		
	};
}
