package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_TD_SCENE_APP_PARAMSV2 extends Structure {
	/** \u0368\ufffd\ufffdID */
	public NativeLong ulChannelId;
	/** \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd */
	public NativeLong ulIndex;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u07f2\ufffd\ufffd\ufffd<br>
	 * C type : PU_TD_LINE_PARAMV2_S
	 */
	public PU_TD_LINE_PARAMV2 stLaneLine;
	/**
	 * \ufffd\ufffd\u02b9\ufffd\u00e3\ufffd\ufffd\ufffd\u04aa\ufffd\ufffd\ufffd\u01fc\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u8c78\u02b9\ufffd\ufffd<br>
	 * C type : PU_TD_ILLEGAL_PARKINK_PARAMS_S
	 */
	public PU_TD_ILLEGAL_PARKINK_PARAMS stIllegalParking;
	/**
	 * \u03a5\ufffd\ufffd\u0221\u05a4\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_TD_TRAFFIC_DOME_ILLEGAL_EVIDENCE_PARAMS_S
	 */
	public PU_TD_TRAFFIC_DOME_ILLEGAL_EVIDENCE_PARAMS stIllegalEviParams;
	/**
	 * \ufffd\ufffd\u0368\ufffd\u00bc\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_TD_TRAFFIC_DOME_TRAFFIC_EVENT_PARAMS_S
	 */
	public PU_TD_TRAFFIC_DOME_TRAFFIC_EVENT_PARAMS stTrafficEventParams;
	/**
	 * \ufffd\ufffd\u0368\ufffd\ufffd\u0772\u027c\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_TD_TRAFFIC_DOME_TRAFFIC_DATA_COLLECT_PARAMS_S
	 */
	public PU_TD_TRAFFIC_DOME_TRAFFIC_DATA_COLLECT_PARAMS stTrafficDataCollectParams;
	public PU_TD_SCENE_APP_PARAMSV2() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulChannelId", "ulIndex", "stLaneLine", "stIllegalParking", "stIllegalEviParams", "stTrafficEventParams", "stTrafficDataCollectParams");
	}
	/**
	 * @param ulChannelId \u0368\ufffd\ufffdID<br>
	 * @param ulIndex \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * @param stLaneLine \ufffd\ufffd\ufffd\ufffd\ufffd\u07f2\ufffd\ufffd\ufffd<br>
	 * C type : PU_TD_LINE_PARAMV2_S<br>
	 * @param stIllegalParking \ufffd\ufffd\u02b9\ufffd\u00e3\ufffd\ufffd\ufffd\u04aa\ufffd\ufffd\ufffd\u01fc\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u8c78\u02b9\ufffd\ufffd<br>
	 * C type : PU_TD_ILLEGAL_PARKINK_PARAMS_S<br>
	 * @param stIllegalEviParams \u03a5\ufffd\ufffd\u0221\u05a4\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_TD_TRAFFIC_DOME_ILLEGAL_EVIDENCE_PARAMS_S<br>
	 * @param stTrafficEventParams \ufffd\ufffd\u0368\ufffd\u00bc\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_TD_TRAFFIC_DOME_TRAFFIC_EVENT_PARAMS_S<br>
	 * @param stTrafficDataCollectParams \ufffd\ufffd\u0368\ufffd\ufffd\u0772\u027c\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_TD_TRAFFIC_DOME_TRAFFIC_DATA_COLLECT_PARAMS_S
	 */
	public PU_TD_SCENE_APP_PARAMSV2(NativeLong ulChannelId, NativeLong ulIndex, PU_TD_LINE_PARAMV2 stLaneLine, PU_TD_ILLEGAL_PARKINK_PARAMS stIllegalParking, PU_TD_TRAFFIC_DOME_ILLEGAL_EVIDENCE_PARAMS stIllegalEviParams, PU_TD_TRAFFIC_DOME_TRAFFIC_EVENT_PARAMS stTrafficEventParams, PU_TD_TRAFFIC_DOME_TRAFFIC_DATA_COLLECT_PARAMS stTrafficDataCollectParams) {
		super();
		this.ulChannelId = ulChannelId;
		this.ulIndex = ulIndex;
		this.stLaneLine = stLaneLine;
		this.stIllegalParking = stIllegalParking;
		this.stIllegalEviParams = stIllegalEviParams;
		this.stTrafficEventParams = stTrafficEventParams;
		this.stTrafficDataCollectParams = stTrafficDataCollectParams;
	}
	public PU_TD_SCENE_APP_PARAMSV2(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_TD_SCENE_APP_PARAMSV2 implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_TD_SCENE_APP_PARAMSV2 implements Structure.ByValue {
		
	};
}
