package com.summit.sdk.huawei;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_UPGRADE_ITGT_MODEL_PARA extends Structure {
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_UPGRADE_ITGT_TYPE_E
	 */
	public int enUpgradeItgtType;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u00b7\ufffd\ufffd<br>
	 * C type : CHAR[300]
	 */
	public byte[] szModelPath = new byte[300];
	/** C type : CHAR[32] */
	public byte[] szReserve = new byte[32];
	public PU_UPGRADE_ITGT_MODEL_PARA() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("enUpgradeItgtType", "szModelPath", "szReserve");
	}
	/**
	 * @param enUpgradeItgtType \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_UPGRADE_ITGT_TYPE_E<br>
	 * @param szModelPath \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u00b7\ufffd\ufffd<br>
	 * C type : CHAR[300]<br>
	 * @param szReserve C type : CHAR[32]
	 */
	public PU_UPGRADE_ITGT_MODEL_PARA(int enUpgradeItgtType, byte szModelPath[], byte szReserve[]) {
		super();
		this.enUpgradeItgtType = enUpgradeItgtType;
		if ((szModelPath.length != this.szModelPath.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szModelPath = szModelPath;
		if ((szReserve.length != this.szReserve.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserve = szReserve;
	}
	public PU_UPGRADE_ITGT_MODEL_PARA(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_UPGRADE_ITGT_MODEL_PARA implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_UPGRADE_ITGT_MODEL_PARA implements Structure.ByValue {
		
	};
}
