package com.summit.sdk.huawei;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.Union;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a>
 * that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>
 * , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_UserData extends Structure {
    /**
     * C type : LAYER_THREE_TYPE_E
     */
    public int eType;
    /**
     * C type : _unMetadata
     */
    public _unMetadata unMetaData = new _unMetadata();

    public PU_UserData() {
        this.setAlignType(ALIGN_NONE);
    }

    public PU_UserData(Pointer peer) {
        super(peer);
        read();
    }


    @Override
    public void read() {
        super.read();
        switch (eType) {
            case HWPuSDKLibrary.LAYER_THREE_TYPE.FACE_PIC:
                unMetaData.setType(ST_BINARY.class);
                unMetaData.read();
                break;
            case HWPuSDKLibrary.LAYER_THREE_TYPE.FACE_INFO:
                unMetaData.setType(META_FACE_INFO.class);
                unMetaData.read();
                break;
            case HWPuSDKLibrary.LAYER_THREE_TYPE.FACE_FEATURE:
                unMetaData.setType(META_FACE_ATTRIBUTES.class);
                unMetaData.read();
                break;
            case HWPuSDKLibrary.LAYER_THREE_TYPE.FACE_PANORAMA:
                unMetaData.setType(ST_BINARY.class);
                unMetaData.read();
                break;
            case HWPuSDKLibrary.LAYER_THREE_TYPE.FACE_MATCH:
                unMetaData.setType(ST_BINARY.class);
                unMetaData.read();
                break;
            case HWPuSDKLibrary.LAYER_THREE_TYPE.FACE_MATCHRATE:
                unMetaData.setType(Integer.TYPE);
                unMetaData.read();
                break;
            case HWPuSDKLibrary.LAYER_THREE_TYPE.FACE_LIB_NAME:
                unMetaData.setType(ST_BINARY.class);
                unMetaData.read();
                break;
            default:
                break;
        }
    }

    @Override
    protected List<String> getFieldOrder() {
        return Arrays.asList("eType", "unMetaData");
    }

    /**
     * <i>native declaration : E:\video\HWPuSDK.h:3192</i>
     */
    public static class _unMetadata extends Union {
        public boolean bBoolValue;
        public byte charValue;
        /**
         * C type : UCHAR
         */
        public byte ucharValue;
        public short shortValue;
        public short ushortValue;
        public int IntValue;
        public int uIntValue;
        public long longlongValue;
        public long uLonglongValue;
        /**
         * C type : ST_BINARY
         */
        public ST_BINARY stBinay;
        /**
         * C type : META_RECT_S
         */
        public META_RECT_S stRec;
        /**
         * C type : META_POINT_S
         */
        public META_POINT_S stPoint;
        /**
         * C type : META_LINE_S
         */
        public META_LINE_S stLine;
        /**
         * C type : META_POLYGON_S
         */
        public META_POLYGON_S stPolyGon;
        /**
         * C type : META_COLOR_S
         */
        public META_COLOR_S stColor;
        /**
         * C type : META_HUMAN_ATTRIBUTES_S
         */
        public META_HUMAN_ATTRIBUTES stHumanAttr;
        /**
         * C type : META_FACE_ATTRIBUTES_S
         */
        public META_FACE_ATTRIBUTES stFaceAttr;
        /**
         * C type : META_FACE_INFO_S
         */
        public META_FACE_INFO stFaceInfo;
        /**
         * C type : CHAR[1]
         */
        public byte[] szUserData = new byte[1];

        public _unMetadata() {
            this.setAlignType(ALIGN_NONE);
        }

        public static class ByReference extends _unMetadata implements Structure.ByReference {

        }

        ;

        public static class ByValue extends _unMetadata implements Structure.ByValue {

        }

        ;
    }

    public static class ByReference extends PU_UserData implements Structure.ByReference {

    }

    ;

    public static class ByValue extends PU_UserData implements Structure.ByValue {

    }

    ;
}
