package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_VIDEODIAGNOSIS_PARA extends Structure {
	/** \u0368\ufffd\ufffd\ufffd\ufffd */
	public NativeLong ulChnID;
	/**
	 * \ufffd\u6faf\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_ALARM_VIDEODIAGNOSIS_TYPE_E
	 */
	public int enAlarmType;
	/** \u02b9\ufffd\ufffd */
	public boolean bEnable;
	/** \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd */
	public NativeLong ulSensitivity;
	/** \ufffd\u6faf\ufffd\u03f1\ufffd\ufffd\ufffd\ufffd */
	public NativeLong ulAlarmInterval;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u02b1\ufffd\ufffd\ufffd\u0431\ufffd<br>
	 * C type : PU_ALARM_TIME_LIST_S
	 */
	public PU_ALARM_TIME_PARA_LIST stAlarmTimeList;
	/** C type : CHAR[32] */
	public byte[] szReserved = new byte[32];
	public PU_VIDEODIAGNOSIS_PARA() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulChnID", "enAlarmType", "bEnable", "ulSensitivity", "ulAlarmInterval", "stAlarmTimeList", "szReserved");
	}
	/**
	 * @param ulChnID \u0368\ufffd\ufffd\ufffd\ufffd<br>
	 * @param enAlarmType \ufffd\u6faf\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_ALARM_VIDEODIAGNOSIS_TYPE_E<br>
	 * @param bEnable \u02b9\ufffd\ufffd<br>
	 * @param ulSensitivity \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * @param ulAlarmInterval \ufffd\u6faf\ufffd\u03f1\ufffd\ufffd\ufffd\ufffd<br>
	 * @param stAlarmTimeList \ufffd\ufffd\ufffd\ufffd\u02b1\ufffd\ufffd\ufffd\u0431\ufffd<br>
	 * C type : PU_ALARM_TIME_LIST_S<br>
	 * @param szReserved C type : CHAR[32]
	 */
	public PU_VIDEODIAGNOSIS_PARA(NativeLong ulChnID, int enAlarmType, boolean bEnable, NativeLong ulSensitivity, NativeLong ulAlarmInterval, PU_ALARM_TIME_PARA_LIST stAlarmTimeList, byte szReserved[]) {
		super();
		this.ulChnID = ulChnID;
		this.enAlarmType = enAlarmType;
		this.bEnable = bEnable;
		this.ulSensitivity = ulSensitivity;
		this.ulAlarmInterval = ulAlarmInterval;
		this.stAlarmTimeList = stAlarmTimeList;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public PU_VIDEODIAGNOSIS_PARA(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_VIDEODIAGNOSIS_PARA implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_VIDEODIAGNOSIS_PARA implements Structure.ByValue {
		
	};
}
