package com.summit.sdk.huawei;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_VERTICAL_LIMIT extends Structure {
	/** \ufffd\ufffd\u05b1\ufffd\ufffd\u03bb */
	public int iVerticalLimit;
	/** C type : CHAR[32] */
	public byte[] szReserve = new byte[32];
	public PU_VERTICAL_LIMIT() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("iVerticalLimit", "szReserve");
	}
	/**
	 * @param iVerticalLimit \ufffd\ufffd\u05b1\ufffd\ufffd\u03bb<br>
	 * @param szReserve C type : CHAR[32]
	 */
	public PU_VERTICAL_LIMIT(int iVerticalLimit, byte szReserve[]) {
		super();
		this.iVerticalLimit = iVerticalLimit;
		if ((szReserve.length != this.szReserve.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserve = szReserve;
	}
	public PU_VERTICAL_LIMIT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_VERTICAL_LIMIT implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_VERTICAL_LIMIT implements Structure.ByValue {
		
	};
}
