package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public abstract class PU_VIDEO_DISPLAY_INFO extends Structure {
	/** \u0368\ufffd\ufffdID */
	public NativeLong ulChannelId;
	/** \ufffd\ufffd\ufffd\ufffd */
	public NativeLong lBrightValue;
	/** \u026b\ufffd\ufffd */
	public NativeLong lHueValue;
	/** \ufffd\ufffd\ufffd\u0376\ufffd */
	public NativeLong lSaturationValue;
	/** \ufffd\u0531\u0236\ufffd */
	public NativeLong lContrastValue;
	/** \ufffd\ufffd\ufffd */
	public NativeLong lSharpValue;
	/**
	 * \ufffd\ufffd\u023f\ufffd\ufffd\ufffd<br>
	 * C type : PU_COMMONMODE_SWITCH_E
	 */
	public int enSharpSwitch;
	/** \ufffd\u07b8\ufffd\u03bb\ufffd\ufffd00000\ufffd\ufffd\ufffd\u04f5\ufffd\u03bb\ufffd\ufffd\ufffd\ufffd\u03aa\ufffd\ufffd\u0223\ufffd\u026b\ufffd\u0223\ufffd\ufffd\ufffd\ufffd\u0376\u0223\ufffd\ufffd\u0531\u0236\u0223\ufffd\ufffd\ufffd\ufffd\u0223\ufffd\ufffd\ufffd\u03bb\ufffd\u07b8\ufffd\ufffd\ufffd1\ufffd\ufffd\u02be\ufffd\u07b8\u0123\ufffd\ufffd\ufffd0\ufffd\ufffd\ufffd\u07b8\ufffd */
	public NativeLong ulBitMap;
	/** Conversion Error : sizeof(ULONG) */
	public PU_VIDEO_DISPLAY_INFO() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulChannelId", "lBrightValue", "lHueValue", "lSaturationValue", "lContrastValue", "lSharpValue", "enSharpSwitch", "ulBitMap");
	}
	/**
	 * @param ulChannelId \u0368\ufffd\ufffdID<br>
	 * @param lBrightValue \ufffd\ufffd\ufffd\ufffd<br>
	 * @param lHueValue \u026b\ufffd\ufffd<br>
	 * @param lSaturationValue \ufffd\ufffd\ufffd\u0376\ufffd<br>
	 * @param lContrastValue \ufffd\u0531\u0236\ufffd<br>
	 * @param lSharpValue \ufffd\ufffd\ufffd<br>
	 * @param enSharpSwitch \ufffd\ufffd\u023f\ufffd\ufffd\ufffd<br>
	 * C type : PU_COMMONMODE_SWITCH_E<br>
	 * @param ulBitMap \ufffd\u07b8\ufffd\u03bb\ufffd\ufffd00000\ufffd\ufffd\ufffd\u04f5\ufffd\u03bb\ufffd\ufffd\ufffd\ufffd\u03aa\ufffd\ufffd\u0223\ufffd\u026b\ufffd\u0223\ufffd\ufffd\ufffd\ufffd\u0376\u0223\ufffd\ufffd\u0531\u0236\u0223\ufffd\ufffd\ufffd\ufffd\u0223\ufffd\ufffd\ufffd\u03bb\ufffd\u07b8\ufffd\ufffd\ufffd1\ufffd\ufffd\u02be\ufffd\u07b8\u0123\ufffd\ufffd\ufffd0\ufffd\ufffd\ufffd\u07b8\ufffd
	 */
	public PU_VIDEO_DISPLAY_INFO(NativeLong ulChannelId, NativeLong lBrightValue, NativeLong lHueValue, NativeLong lSaturationValue, NativeLong lContrastValue, NativeLong lSharpValue, int enSharpSwitch, NativeLong ulBitMap) {
		super();
		this.ulChannelId = ulChannelId;
		this.lBrightValue = lBrightValue;
		this.lHueValue = lHueValue;
		this.lSaturationValue = lSaturationValue;
		this.lContrastValue = lContrastValue;
		this.lSharpValue = lSharpValue;
		this.enSharpSwitch = enSharpSwitch;
		this.ulBitMap = ulBitMap;
	}
	public PU_VIDEO_DISPLAY_INFO(Pointer peer) {
		super(peer);
	}
	public static abstract class ByReference extends PU_VIDEO_DISPLAY_INFO implements Structure.ByReference {
		
	};
	public static abstract class ByValue extends PU_VIDEO_DISPLAY_INFO implements Structure.ByValue {
		
	};
}
