package com.summit.sdk.huawei;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PU_VEHICLE_INFO extends Structure {
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u03bb\ufffd\ufffd<br>
	 * C type : PU_AREA_INFO_S
	 */
	public PU_AREA_INFO stVehicleLoc;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u026b<br>
	 * C type : PU_VEHICLE_COLOR_E
	 */
	public int enVehicleColor;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_VEHICLE_TYPE_E
	 */
	public int enVehicleType;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\u03bb\ufffd\ufffd<br>
	 * C type : PU_AREA_INFO_S
	 */
	public PU_AREA_INFO stVehicleFaceLoc;
	/**
	 * \u0524\ufffd\ufffd\ufffd\u05b6\ufffd<br>
	 * C type : CHAR[64]
	 */
	public byte[] szReserved = new byte[64];
	public PU_VEHICLE_INFO() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("stVehicleLoc", "enVehicleColor", "enVehicleType", "stVehicleFaceLoc", "szReserved");
	}
	/**
	 * @param stVehicleLoc \ufffd\ufffd\ufffd\ufffd\u03bb\ufffd\ufffd<br>
	 * C type : PU_AREA_INFO_S<br>
	 * @param enVehicleColor \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u026b<br>
	 * C type : PU_VEHICLE_COLOR_E<br>
	 * @param enVehicleType \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_VEHICLE_TYPE_E<br>
	 * @param stVehicleFaceLoc \ufffd\ufffd\ufffd\ufffd\u03bb\ufffd\ufffd<br>
	 * C type : PU_AREA_INFO_S<br>
	 * @param szReserved \u0524\ufffd\ufffd\ufffd\u05b6\ufffd<br>
	 * C type : CHAR[64]
	 */
	public PU_VEHICLE_INFO(PU_AREA_INFO stVehicleLoc, int enVehicleColor, int enVehicleType, PU_AREA_INFO stVehicleFaceLoc, byte szReserved[]) {
		super();
		this.stVehicleLoc = stVehicleLoc;
		this.enVehicleColor = enVehicleColor;
		this.enVehicleType = enVehicleType;
		this.stVehicleFaceLoc = stVehicleFaceLoc;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public PU_VEHICLE_INFO(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PU_VEHICLE_INFO implements Structure.ByReference {
		
	};
	public static class ByValue extends PU_VEHICLE_INFO implements Structure.ByValue {
		
	};
}
