package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class RECORD_STRATEGY extends Structure {
	public NativeLong ulChannelId;
	/** \ufffd\u6d22\ufffd\ufffd\ufffd\ufffd:0\u046d\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd  1\u0363\u05b9\u00bc\ufffd\ufffd */
	public NativeLong ulStrategy;
	/** \ufffd\ufffd\u0421\u0524\u00bc\u02b1\ufffd\ufffd */
	public NativeLong ulMinRecordTime;
	/** \ufffd\ufffd\u01f0\u0524\u00bc\u02b1\ufffd\ufffd V2R3\ufffd\u6c7e 0:\ufffd\ufffd\u0524\u00bc 65535:\ufffd\ufffd\ufffd\ufffd\ufffd\u06b4\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u02b1\ufffd\ufffd\u0524\u00bc \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u8c78\ufffd\ufffd\ufffd\ufffd5-20s\ufffd\ufffd\ufffd\ufffd */
	public NativeLong ulPreAlarmRecordTime;
	/** C type : CHAR[32] */
	public byte[] szReserved = new byte[32];
	public RECORD_STRATEGY() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulChannelId", "ulStrategy", "ulMinRecordTime", "ulPreAlarmRecordTime", "szReserved");
	}
	/**
	 * @param ulStrategy \ufffd\u6d22\ufffd\ufffd\ufffd\ufffd:0\u046d\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd  1\u0363\u05b9\u00bc\ufffd\ufffd<br>
	 * @param ulMinRecordTime \ufffd\ufffd\u0421\u0524\u00bc\u02b1\ufffd\ufffd<br>
	 * @param ulPreAlarmRecordTime \ufffd\ufffd\u01f0\u0524\u00bc\u02b1\ufffd\ufffd V2R3\ufffd\u6c7e 0:\ufffd\ufffd\u0524\u00bc 65535:\ufffd\ufffd\ufffd\ufffd\ufffd\u06b4\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u02b1\ufffd\ufffd\u0524\u00bc \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u8c78\ufffd\ufffd\ufffd\ufffd5-20s\ufffd\ufffd\ufffd\ufffd<br>
	 * @param szReserved C type : CHAR[32]
	 */
	public RECORD_STRATEGY(NativeLong ulChannelId, NativeLong ulStrategy, NativeLong ulMinRecordTime, NativeLong ulPreAlarmRecordTime, byte szReserved[]) {
		super();
		this.ulChannelId = ulChannelId;
		this.ulStrategy = ulStrategy;
		this.ulMinRecordTime = ulMinRecordTime;
		this.ulPreAlarmRecordTime = ulPreAlarmRecordTime;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public RECORD_STRATEGY(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends RECORD_STRATEGY implements Structure.ByReference {
		
	};
	public static class ByValue extends RECORD_STRATEGY implements Structure.ByValue {
		
	};
}
