package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SMTP_CONFIG_INFO extends Structure {
	/**
	 * @see PU_SMTP_MAIL_TYPE<br>
	 * \ufffd\ufffd\u05be\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u00b7\ufffd\ufffd\ufffd\ufffd\ufffdor\ufffd\ufffd\ufffd\ufffd\ufffd\u057c\ufffd\ufffd\ufffd,0:\ufffd\ufffd\ufffd\ufffd,1,<br>
	 * C type : PU_SMTP_MAIL_TYPE
	 */
	public int enMailType;
	/** \ufffd\ufffd\ufffd\u00f1\ufffd\u05be */
	public boolean bSMTPEnable;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u00fb\ufffd\ufffd\ufffd<br>
	 * C type : CHAR[(32 + 4)]
	 */
	public byte[] szSenderName = new byte[32 + 4];
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : CHAR[128]
	 */
	public byte[] szSenderMail = new byte[128];
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffdIP\ufffd\ufffd\u05b7<br>
	 * C type : CHAR[16]
	 */
	public byte[] szServerIP = new byte[16];
	/** \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u02ff\ufffd */
	public NativeLong ulServerPort;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd<br>
	 * C type : PU_SMTP_SECURITY_TYPE_E
	 */
	public int enSecurityType;
	/** \ufffd\ufffd\ufffd\ufffd\u037c\u01ac\ufffd\ufffd\ufffd\ufffd */
	public boolean bPicEnable;
	/** \u037c\u01ac\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd */
	public NativeLong ulPicNum;
	/** \u05e5\ufffd\u013c\ufffd\ufffd */
	public NativeLong ulSnapTimeInterval;
	/** \ufffd\ufffd\ufffd\u00f7\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u05a4 */
	public boolean bServerCrtEnable;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u00fb\ufffd\ufffd\ufffd<br>
	 * C type : CHAR[(32 + 4)]
	 */
	public byte[] szServerName = new byte[32 + 4];
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\ufffdPwd<br>
	 * C type : CHAR[(64 + 4)]
	 */
	public byte[] szPassword = new byte[64 + 4];
	/** \ufffd\u057c\ufffd\ufffd\ufffd\ufffd\ufffd\u013f */
	public NativeLong ulReceiverNum;
	/**
	 * \ufffd\u057c\ufffd\ufffd\ufffd\ufffd\u0431\ufffd<br>
	 * C type : PU_SMTP_RECVEIVER_INFO_S[3]
	 */
	public PU_SMTP_RECVEIVER_INFO[] szReceiverInfo = new PU_SMTP_RECVEIVER_INFO[3];
	/**
	 * \u0524\ufffd\ufffd\ufffd\u05b6\ufffd<br>
	 * C type : CHAR[64]
	 */
	public byte[] szReserved = new byte[64];
	public SMTP_CONFIG_INFO() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("enMailType", "bSMTPEnable", "szSenderName", "szSenderMail", "szServerIP", "ulServerPort", "enSecurityType", "bPicEnable", "ulPicNum", "ulSnapTimeInterval", "bServerCrtEnable", "szServerName", "szPassword", "ulReceiverNum", "szReceiverInfo", "szReserved");
	}
	public SMTP_CONFIG_INFO(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends SMTP_CONFIG_INFO implements Structure.ByReference {
		
	};
	public static class ByValue extends SMTP_CONFIG_INFO implements Structure.ByValue {
		
	};
}
