package com.summit.sdk.huawei;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SNAPSHOT_PARA extends Structure {
	/** \u0368\ufffd\ufffdID */
	public NativeLong ulChannelID;
	/** \ufffd\ufffd\ufffd\ufffdID(\u013f\u01f0\ufffd\ufffd\u05a7\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd) */
	public NativeLong ulStreamID;
	/**
	 * \ufffd\u05b1\ufffd\ufffd\ufffd(\ufffd\u0772\ufffd\u05a7\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd,\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u05b1\ufffd\ufffd\ufffd\u03aa\u05fc)<br>
	 * C type : PU_RESOLUTION_TYPE_E
	 */
	public int enResolution;
	/**
	 * \u037c\u01ac\ufffd\ufffd\u02bd(\u013f\u01f0\ufffd\ufffd\u05a7\ufffd\ufffdJPEG\ufffd\ufffd\u02bd)<br>
	 * C type : PU_SNAPSHOT_FORMAT_E
	 */
	public int enPictureFormat;
	/**
	 * \u05e5\ufffd\ufffd\ufffd\u013c\ufffd\u013f\u00bc<br>
	 * C type : CHAR[512 + 4]
	 */
	public byte[] szPicPath = new byte[512 + 4];
	/**
	 * \u0524\ufffd\ufffd<br>
	 * C type : CHAR[32]
	 */
	public byte[] szReserved = new byte[32];
	public SNAPSHOT_PARA() {
		super();
	}
	protected List<String > getFieldOrder() {
		return Arrays.asList("ulChannelID", "ulStreamID", "enResolution", "enPictureFormat", "szPicPath", "szReserved");
	}
	/**
	 * @param ulChannelID \u0368\ufffd\ufffdID<br>
	 * @param ulStreamID \ufffd\ufffd\ufffd\ufffdID(\u013f\u01f0\ufffd\ufffd\u05a7\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd)<br>
	 * @param enResolution \ufffd\u05b1\ufffd\ufffd\ufffd(\ufffd\u0772\ufffd\u05a7\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd,\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u05b1\ufffd\ufffd\ufffd\u03aa\u05fc)<br>
	 * C type : PU_RESOLUTION_TYPE_E<br>
	 * @param enPictureFormat \u037c\u01ac\ufffd\ufffd\u02bd(\u013f\u01f0\ufffd\ufffd\u05a7\ufffd\ufffdJPEG\ufffd\ufffd\u02bd)<br>
	 * C type : PU_SNAPSHOT_FORMAT_E<br>
	 * @param szPicPath \u05e5\ufffd\ufffd\ufffd\u013c\ufffd\u013f\u00bc<br>
	 * C type : CHAR[512 + 4]<br>
	 * @param szReserved \u0524\ufffd\ufffd<br>
	 * C type : CHAR[32]
	 */
	public SNAPSHOT_PARA(NativeLong ulChannelID, NativeLong ulStreamID, int enResolution, int enPictureFormat, byte szPicPath[], byte szReserved[]) {
		super();
		this.ulChannelID = ulChannelID;
		this.ulStreamID = ulStreamID;
		this.enResolution = enResolution;
		this.enPictureFormat = enPictureFormat;
		if ((szPicPath.length != this.szPicPath.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szPicPath = szPicPath;
		if ((szReserved.length != this.szReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.szReserved = szReserved;
	}
	public SNAPSHOT_PARA(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends SNAPSHOT_PARA implements Structure.ByReference {
		
	};
	public static class ByValue extends SNAPSHOT_PARA implements Structure.ByValue {
		
	};
}
