package com.summit.sdk.huawei;
import com.sun.jna.Pointer;
import com.sun.jna.Union;
/**
 * <i>native declaration : E:\video\HWPuSDK.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class tagITSRegulationCfgAttch extends Union {
	/**
	 * \u0524\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u01f0\ufffd\ufffd\u02b9\ufffd\ufffd, \ufffd\ufffd\ufffd\ufffd\ufffd\u05e5\ufffd\u0132\ufffd\ufffd\ufffd,\ufffd\ufffd\u04e6\u03a5\ufffd\ufffd\ufffd\ufffd\ufffd\ufffdITS_REGULA_RUNNINGRED<br>
	 * C type : PU_ITS_RUNLIGHT_PARA_S
	 */
	public tagITSRunLightPara stRunningRed;
	/**
	 * \u0479\ufffd\ufffd,\ufffd\ufffd\u04e6\u03a5\ufffd\ufffd\ufffd\ufffd\ufffd\ufffdITS_REGULA_OVER_LANE_LINE<br>
	 * C type : PU_ITS_REGULATION_CFG_ATTCH_PRESS_LINE_UNIT_S
	 */
	public tagITSRegulationCfgAttchPressLine stPressLine;
	/**
	 * \ufffd\ufffd\u057c\ufffd\ufffd,\ufffd\ufffd\u04e6\u03a5\ufffd\ufffd\ufffd\ufffd\ufffd\ufffdITS_REGULA_MOTOR_IN_BICYCLE_LANE<br>
	 * C type : PU_ITS_REGULATION_CFG_ATTCH_INVADE_DRIVERWAY_UNIT_S
	 */
	public tagITSRegulationCfgAttchInvadeDriverWay stInvadeDriverWay;
	/**
	 * \ufffd\u01f7\ufffd\u057c\ufffd\u00f9\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd,\ufffd\ufffd\u04e6\u03a5\ufffd\ufffd\ufffd\ufffd\ufffd\ufffdITS_REGULA_OCCUPANCY_BUSLANE<br>
	 * C type : PU_ITS_REGULATION_CFG_ATTCH_INVADE_DRIVERWAY_UNIT_S
	 */
	public tagITSRegulationCfgAttchInvadeDriverWay stInvadeBusLane;
	/**
	 * \ufffd\ufffd\ufffd\ufffd\ufffd\u03a5\u0363\u02b1\ufffd\ufffd,\ufffd\ufffd\u04e6\u03a5\ufffd\ufffd\ufffd\ufffd\ufffd\ufffdITS_REGULA_ILLEGAL_PARKING<br>
	 * C type : PU_ITS_REGULATION_CFG_ATTCH_INVADE_DRIVERWAY_UNIT_S
	 */
	public tagITSRegulationCfgAttchInvadeDriverWay stIllegalParkTime;
	/**
	 * \ufffd\ufffd\ufffd\u02f5\u0234\ufffd\u02b1\ufffd\ufffd<br>
	 * C type : PU_ITS_REGULATION_CFG_ATTCH_INVADE_DRIVERWAY_UNIT_S
	 */
	public tagITSRegulationCfgAttchInvadeDriverWay stImpolitePedestriansTime;
	public tagITSRegulationCfgAttch() {
		super();
	}
	/**
	 * @param stRunningRed \u0524\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\u01f0\ufffd\ufffd\u02b9\ufffd\ufffd, \ufffd\ufffd\ufffd\ufffd\ufffd\u05e5\ufffd\u0132\ufffd\ufffd\ufffd,\ufffd\ufffd\u04e6\u03a5\ufffd\ufffd\ufffd\ufffd\ufffd\ufffdITS_REGULA_RUNNINGRED<br>
	 * C type : PU_ITS_RUNLIGHT_PARA_S
	 */
	public tagITSRegulationCfgAttch(tagITSRunLightPara stRunningRed) {
		super();
		this.stRunningRed = stRunningRed;
		setType(tagITSRunLightPara.class);
	}
	/**
	 * @param stPressLine \u0479\ufffd\ufffd,\ufffd\ufffd\u04e6\u03a5\ufffd\ufffd\ufffd\ufffd\ufffd\ufffdITS_REGULA_OVER_LANE_LINE<br>
	 * C type : PU_ITS_REGULATION_CFG_ATTCH_PRESS_LINE_UNIT_S
	 */
	public tagITSRegulationCfgAttch(tagITSRegulationCfgAttchPressLine stPressLine) {
		super();
		this.stPressLine = stPressLine;
		setType(tagITSRegulationCfgAttchPressLine.class);
	}
	/**
	 * @param stInvadeDriverWay_or_stInvadeBusLane_or_stIllegalParkTime_or_stImpolitePedestriansTime \ufffd\ufffd\u057c\ufffd\ufffd,\ufffd\ufffd\u04e6\u03a5\ufffd\ufffd\ufffd\ufffd\ufffd\ufffdITS_REGULA_MOTOR_IN_BICYCLE_LANE<br>
	 * C type : PU_ITS_REGULATION_CFG_ATTCH_INVADE_DRIVERWAY_UNIT_S, or \ufffd\u01f7\ufffd\u057c\ufffd\u00f9\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd,\ufffd\ufffd\u04e6\u03a5\ufffd\ufffd\ufffd\ufffd\ufffd\ufffdITS_REGULA_OCCUPANCY_BUSLANE<br>
	 * C type : PU_ITS_REGULATION_CFG_ATTCH_INVADE_DRIVERWAY_UNIT_S, or \ufffd\ufffd\ufffd\ufffd\ufffd\u03a5\u0363\u02b1\ufffd\ufffd,\ufffd\ufffd\u04e6\u03a5\ufffd\ufffd\ufffd\ufffd\ufffd\ufffdITS_REGULA_ILLEGAL_PARKING<br>
	 * C type : PU_ITS_REGULATION_CFG_ATTCH_INVADE_DRIVERWAY_UNIT_S, or \ufffd\ufffd\ufffd\u02f5\u0234\ufffd\u02b1\ufffd\ufffd<br>
	 * C type : PU_ITS_REGULATION_CFG_ATTCH_INVADE_DRIVERWAY_UNIT_S
	 */
	public tagITSRegulationCfgAttch(tagITSRegulationCfgAttchInvadeDriverWay stInvadeDriverWay_or_stInvadeBusLane_or_stIllegalParkTime_or_stImpolitePedestriansTime) {
		super();
		this.stImpolitePedestriansTime = this.stIllegalParkTime = this.stInvadeBusLane = this.stInvadeDriverWay = stInvadeDriverWay_or_stInvadeBusLane_or_stIllegalParkTime_or_stImpolitePedestriansTime;
		setType(tagITSRegulationCfgAttchInvadeDriverWay.class);
	}
	public tagITSRegulationCfgAttch(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends tagITSRegulationCfgAttch implements com.sun.jna.Structure.ByReference {
		
	};
	public static class ByValue extends tagITSRegulationCfgAttch implements com.sun.jna.Structure.ByValue {
		
	};
}
