server:
  port: "${WebServer_Port:22222}"
spring:
  profiles:
    active: pro
  application:
    name: "cbb-api-gateway-db"
  flyway:
    # 如果启动的时候需要flyway管理sql脚本的话，将enabled设置为true
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db
    encoding: UTF-8
    # 验证错误时 是否自动清除数据库 高危操作!
    clean-on-validation-error: true

zuul:
  ignoredServices: '*'
  routes:
    cbb_userauth:
      path: /api/userauth/**
      serviceId: cbb-userauth
    cbb_weather:
      path: /api/weather/**
      serviceId: cbb-weather
    cbb_demo:
      path: /api/demo/**
      serviceId: cbb-demo
    ppnetwork:
      path: /api/ppnetwork/**
      serviceId: ppnetwork
    web_service_skeleton:
      path: /api/webserviceskeleton/**
      serviceId: web-service-skeleton

#当zuul.routes的配置用指定url进行路由时,是zuul.host.connect-timeout-millis,zuul.host.socket-timeout-millis这两个配生效，
#当zuul.routes的配置用serviceId进行路由时,是ribbon.ReadTimeout,ribbon.SocketTimeout生效。
#熔断器超时时间要大于负载均衡器超时时间
#值设置的计算公式
#timeoutInMilliseconds = (ribbonReadTimeout + ribbonConnectTimeout) * (maxAutoRetries + 1) * (maxAutoRetriesNextServer + 1);
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 40000

ribbon:
  # 请求连接的超时时间
  ConnectTimeout: 10000
  # 请求处理的超时时间
  ReadTimeout: 10000
  httpclient:
    enable: false
  okhttp:
    enabled: true

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
    response:
      enabled: true

#登录密码密钥必须是16字节长度的
password:
  encode:
    key: summitsummitsumm

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
logging:
  file: logs/all.log