ALTER TABLE sys_user MODIFY COLUMN USERNAME VARCHAR(50) BINARY; 
ALTER TABLE sys_user_adcd MODIFY COLUMN USERNAME VARCHAR(50) BINARY; 
ALTER TABLE sys_user_dept MODIFY COLUMN USERNAME VARCHAR(50) BINARY; 
ALTER TABLE sys_user_role MODIFY COLUMN USERNAME VARCHAR(50) BINARY; 
