#开发环境
spring:
  redis:
    host: 192.168.140.155
    port: 10001
eureka:
  instance:
    #使用IP注册服务
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: "http://ucp:Summit2018@192.168.140.155:45000/eureka/"