server:
  port: "${WebServer_Port:22222}"
spring:
  profiles:
    active: pro
  application:
    name: "${projectName:api-gateway}"
  redis:
    host: localhost
    port: 6379

#zuul:
#  routes:
#    api-a:
#      path: /api/pptn/**
#      serviceId: service-pptn
#    api-b:
#      path: /api/demo/**
#      serviceId: service-demo
#    auth:
#      path: /auth/**
#      sensitiveHeaders:
#      serviceId:  auth-server
#  add-proxy-headers: true
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
logging:
  file: logs/all.log