server:
  port: 22222
spring:
  application:
    name: service-gateway
  datasource:
      url: jdbc:sqlserver://192.168.141.113:1433;DatabaseName=watf20181112
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      username: sa
      password: summit123
  redis:
    host: localhost
    port: 6379

eureka:
  instance:
    #使用IP注册服务
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://ucp:summit@localhost:8761/eureka/
#zuul:
#  routes:
#    api-a:
#      path: /api/pptn/**
#      serviceId: service-pptn
#    api-b:
#      path: /api/demo/**
#      serviceId: service-demo
#    auth:
#      path: /auth/**
#      sensitiveHeaders:
#      serviceId:  auth-server
#  add-proxy-headers: true
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
logging:
  file: logs/all.log