server:
  port: "${WebServer_Port:22222}"
spring:
  profiles:
    active: pro
  application:
    name: "${projectName:cbb_api_gateway_db}"


zuul:
  routes:
    api-a:
      path: /api/pptn/**
      serviceId: service-pptn
    cbb_demo:
      path: /api/demo/**
      serviceId: cbb_demo

#当zuul.routes的配置用指定url进行路由时,是zuul.host.connect-timeout-millis,zuul.host.socket-timeout-millis这两个配生效，
#当zuul.routes的配置用serviceId进行路由时,是ribbon.ReadTimeout,ribbon.SocketTimeout生效。
#熔断器超时时间要大于负载均衡器超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 15000

ribbon:
  # 请求连接的超时时间
  SocketTimeout: 10000
  # 请求处理的超时时间
  ReadTimeout: 10000
  httpclient:
    enable: false
  okhttp:
    enabled: true

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
logging:
  file: logs/all.log