server:
  port: 22222
spring:
  application:
    name: api-gateway
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.140.155/summit_cbb?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
      username: root
      password: Summit2017
  redis:
    host: localhost
    port: 6379

eureka:
  instance:
    #使用IP注册服务
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://ucp:Summit2018@localhost:8761/eureka/
#zuul:
#  routes:
#    api-a:
#      path: /api/pptn/**
#      serviceId: service-pptn
#    api-b:
#      path: /api/demo/**
#      serviceId: service-demo
#    auth:
#      path: /auth/**
#      sensitiveHeaders:
#      serviceId:  auth-server
#  add-proxy-headers: true
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
logging:
  file: logs/all.log