#开发环境
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.140.155/summit_cbb?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: Summit2017