#开发环境
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.140.155:49999/summit_cbb?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: Summit2017

  redis:
    host: localhost
    port: 6379
eureka:
  instance:
    #使用IP注册服务
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: "http://ucp:Summit2018@localhost:8761/eureka/"