server:
  port: "${WebServer_Port:22223}"
spring:
  profiles:
    active: pro
  application:
    name: "${projectName:cbb_demo}"

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

mybatis-plus:
  mapper-locations: classpath:com/summit/dao/*.xml
  config-location: classpath:mybatis-config.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
logging:
  file: logs/all.log