server:
  port: "${WebServer_Port:22224}"
spring:
  profiles:
    active: pro
  application:
    name: "cbb-userauth"

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: true

mybatis-plus:
  mapper-locations: classpath:com/summit/dao/*.xml
  config-location: classpath:mybatis-config.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
logging:
  file: logs/all.log