##组件配置
server:
  port: "${WebServer_Port:45004}"
spring:
  application: 
    name: "cbb-weather"
  profiles:
    active:
    - pro
  flyway:
    # 如果启动的时候需要flyway管理sql脚本的话，将enabled设置为true
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db
    encoding: UTF-8
##监控配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  file: logs/all.log
###天气组件的KEY
weather:
##需要保存历史数据的城市名
  city:
    name: 西安;武汉;雁塔区;长安区;洪山区;马尾区
  key:
  ###高德地图key
    ibs: a8c65b39006c61d78f2d02cea44bcafc
  ###聚合数据key
    juhe: 772ff93727cb12fe4565a58960ba5d20
    seniverse: c0obrbc0bvpzjriv
######保存每天天气cron表达式#########
    save:
      today:
        weather: 0 0 23 * * ?

