eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
  redis:
    host: 127.0.0.1
zuul:
  routes:
    api-a:
      path: /api/pptn/**
      serviceId: service-pptn
    api-b:
      path: /api/demo/**
      serviceId: service-demo
    auth:
      path: /auth/**
      sensitiveHeaders:
      serviceId:  auth-server
  add-proxy-headers: true
  
